'use strict';
// Question bank — Content Server Analyst (5-0155): solution design.
// Scenario questions in the style of the real exam (multiple choice and
// true/false, some multiple-response). Explanations teach; `guide` points to
// the handbook article (curriculum/guides/analyst.js). All text is original.

const TF = ['True', 'False'];

module.exports = [
  // ================================================================ an-cis — Requirements and CIS modeling
  { id: 'an-q-cis-001', domain: 'an-cis', guide: 'an-analyst-role',
    q: 'A customer asks what a “CIS model” describes. Which answer is correct?',
    options: ['The Community, Information and Security models, plus application settings', 'Content, Index and Search configuration', 'Categories, Inheritance and Storage providers', 'The connector, interface and server architecture'],
    answer: 0,
    explain: 'CIS stands for Community (users and groups), Information (how content is organised and described) and Security (how access is managed). Application settings are the fourth part: administration settings that shape the user experience.' },
  { id: 'an-q-cis-002', domain: 'an-cis', guide: 'an-analyst-role',
    q: 'During a workshop the team discusses whether drafts should be hidden from readers by using major/minor versions. Which part of the CIS model does this decision belong to?',
    options: ['Community model', 'Information model', 'Security model', 'Application settings'],
    answer: 3,
    explain: 'Versioning behaviour, notifications, audit interests, the Recycle Bin and search settings are application settings. The information model covers containers, metadata and naming; the security model covers privileges and permissions.' },
  { id: 'an-q-cis-003', domain: 'an-cis', guide: 'an-analyst-role',
    q: 'Why is the folder hierarchy so important in a Content Server design?',
    options: ['Content Server stores each folder in a separate database', 'Items inherit permissions, categories and classifications from the container they are added to', 'Search only works inside one folder', 'Folders cannot be renamed after creation'],
    answer: 1,
    explain: 'Content Server is location based. Adding an item to the right folder applies its permissions, categories and (RM) classifications automatically — which is why the top levels are designed so carefully.' },
  { id: 'an-q-cis-004', domain: 'an-cis', guide: 'an-analyst-role',
    q: 'True or false: In a CIS design, each of the four models can be finalised independently as soon as its workshop is finished.',
    options: TF, answer: 1,
    explain: 'False. The parts are interdependent — access requirements, for example, often reshape the folder structure. All decisions stay preliminary until the whole model has been considered, then it is finalised as one coherent design.' },
  { id: 'an-q-cis-005', domain: 'an-cis', guide: 'an-analyst-role',
    q: 'Which set lists the three CIS design objectives used by OpenText Professional Services?',
    options: ['Adaptable/usable, extendable, dependable', 'Fast, cheap, secure', 'Open, closed, audited', 'Scalable, redundant, replicated'],
    answer: 0,
    explain: 'Adaptable/usable (easy to understand, consistent, built for everyday use), extendable (can grow with the rollout) and dependable (low maintenance, supported by governance).' },
  { id: 'an-q-cis-006', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'What is the CIS design approach based on?',
    options: ['Rapid application development by IT alone', 'A questionnaire sent to all users', 'Joint Application Design (JAD): facilitated sessions in which business and technical people design together', 'Copying the structure of the existing file shares'],
    answer: 2,
    explain: 'CIS modeling is a JAD exercise: a facilitator, business, technical and project representatives define together how the solution will be configured.' },
  { id: 'an-q-cis-007', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'In a CIS workshop, which role is expected to know the business processes and make design decisions for the functional group?',
    options: ['Facilitator', 'Technical representative', 'Project representative', 'Business representative'],
    answer: 3,
    explain: 'The business representative is a member of the functional group who knows its processes and information and can decide for it. The facilitator brings platform knowledge and good practice.' },
  { id: 'an-q-cis-008', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'Which role in a CIS workshop provides input on technical constraints and IT policies?',
    options: ['Business representative', 'Technical representative', 'Facilitator', 'Information owner'],
    answer: 1,
    explain: 'The technical representative (IT support or system administration) brings constraints such as security policy, directory rules and infrastructure.' },
  { id: 'an-q-cis-009', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'In what order does the iterative CIS design process usually work?',
    options: ['Permissions → groups → folders → prototype', 'Prototype → requirements → folders', 'Folder structure → review against metadata → groups → access → prototype and review again', 'Application settings → workflows → folders'],
    answer: 2,
    explain: 'Start with the folder structure as a framework, then review it in the context of metadata, the group structure and access requirements, prototype in Content Server and repeat.' },
  { id: 'an-q-cis-010', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'Which two items are prerequisites for a productive CIS workshop? (Choose two.)',
    options: ['A finished build of the production system', 'A working knowledge of Content Server features (or a demo before the workshop)', 'Approval of the final retention schedule by auditors', 'An operational model: how the business works, who creates and uses which content'],
    answer: [1, 3],
    explain: 'Participants need to understand how the business works and what the platform can do. If they have never seen Content Server, schedule a demonstration first. The build comes after the design.' },
  { id: 'an-q-cis-011', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'Which deliverable is a multi-tab spreadsheet listing folders, categories, groups and permissions that is used for iterative review and for the build?',
    options: ['The design specification', 'The project charter', 'The disposition snapshot', 'The CIS model workbook'],
    answer: 3,
    explain: 'The CIS model workbook captures the configuration. The design specification is the companion document explaining design rationale, implementation and governance.' },
  { id: 'an-q-cis-012', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'True or false: A design workshop should ideally include someone from the business who has the authority to make decisions for the group.',
    options: TF, answer: 0,
    explain: 'True. Without a decision-maker every question becomes “we’ll check and come back”, and the iterative design stalls.' },
  { id: 'an-q-cis-013', domain: 'an-cis', guide: 'an-cis-workshops',
    q: 'The project has no written vision or objectives, and the workshops keep ending in debates of personal preference. What is the most likely root cause, according to the design guidelines?',
    options: ['Too few folders were proposed', 'Lack of well-defined vision and objectives to underpin the design principles', 'The prototype was built too early', 'The facilitator used Smart View'],
    answer: 1,
    explain: 'The guidelines name a missing vision and objectives as a key gotcha: design principles rest on them, so without them decisions become matters of taste.' },
  { id: 'an-q-cis-014', domain: 'an-cis', guide: 'an-requirements',
    q: 'A workshop participant insists on designing the structure around three rare exceptions in her process. What principle should the analyst apply?',
    options: ['Design for regular, everyday use and manage exceptions as exceptions (80/20)', 'Build a separate folder tree for each exception', 'Postpone the design until all exceptions are documented', 'Let her design her own top-level area'],
    answer: 0,
    explain: 'The 80/20 rule keeps the design simple for most users. Exceptions get specific handling (a sub-folder, a restricted item) rather than shaping the whole structure.' },
  { id: 'an-q-cis-015', domain: 'an-cis', guide: 'an-requirements',
    q: 'Which statement best expresses “business first, technology second”?',
    options: ['Choose features first, then find processes that fit', 'Let IT decide the structure', 'Design the structure around business processes and practices; handle permissions and records management behind the scenes', 'Avoid using any Content Server features'],
    answer: 2,
    explain: 'Users should see a structure that mirrors their work. Technical aspects such as permissions and RM are configured so they work without users having to think about them.' },
  { id: 'an-q-cis-016', domain: 'an-cis', guide: 'an-requirements',
    q: 'Why does the analyst describe users as personas?',
    options: ['To create user accounts', 'Because OTDS requires them', 'To calculate licence costs', 'To make sure the design serves different kinds of users (occasional readers, daily contributors, controllers, records staff) and their preferred ways to find content'],
    answer: 3,
    explain: 'Personas stop the design from being built for the loudest participant and show that some users browse while others search, so several routes to content are needed.' },
  { id: 'an-q-cis-017', domain: 'an-cis', guide: 'an-requirements',
    q: 'True or false: The design guidelines recommend providing users with several ways to access content, even if training only covers some of them.',
    options: TF, answer: 0,
    explain: 'True. Different users have different preferences — browsing, search, facets, shortcuts — so the design offers multiple routes and personas decide which to emphasise in training.' },
  { id: 'an-q-cis-018', domain: 'an-cis', guide: 'an-community-model',
    q: 'In the community model, which kind of group typically controls access to content, and which controls access to functionality and task assignment?',
    options: ['Role groups for content; organisational groups for functionality', 'Organisational groups for content; role groups for functionality and tasks such as workflow steps', 'External groups for both', 'System support groups for content'],
    answer: 1,
    explain: 'Organisational groups (e.g. o-HR) usually sit on content ACLs; role groups (e.g. r-ContractApprovers) control functionality and are used as workflow performers.' },
  { id: 'an-q-cis-019', domain: 'an-cis', guide: 'an-community-model',
    q: 'A customer wants group names like “HR_Recruiting_Read”. What do the CIS design guidelines recommend instead?',
    options: ['Keep underscores — they are required', 'Use spaces only', 'Use a colon or dash as separator, e.g. “HR:Recruiting:Read”, because Content Server treats an underscore as part of a word', 'Use numeric IDs for all groups'],
    answer: 2,
    explain: 'Underscores join words, which works badly for wrapping and search. Colons or dashes separate the parts clearly.' },
  { id: 'an-q-cis-020', domain: 'an-cis', guide: 'an-community-model',
    q: 'Which prefix convention does the design specification template use for group types?',
    options: ['o- organisational, r- role, ext- external, sys- system support', 'g-, u-, a-, x-', 'HR-, FIN-, LEG-, IT-', 'read-, write-, admin-'],
    answer: 0,
    explain: 'Prefixes show the group type at a glance. The exact convention can vary by customer; consistency is what matters.' },
  { id: 'an-q-cis-021', domain: 'an-cis', guide: 'an-community-model',
    q: 'Business managers complain that every change to group membership takes days because it goes through IT. Which Content Server mechanism addresses this?',
    options: ['Public Access', 'The Owner Group', 'Audit interests', 'Group leaders, who can manage membership of their own groups'],
    answer: 3,
    explain: 'Making authorised business users group leaders delegates membership management while system administrators keep control of creating groups.' },
  { id: 'an-q-cis-022', domain: 'an-cis', guide: 'an-community-model',
    q: 'Where is nesting groups most clearly beneficial?',
    options: ['For every content permission group, to hide members from the ACL', 'For granting the same functional access or privilege to many role groups, e.g. RM disposition access for all information owner groups', 'For external partners only', 'Nesting is never useful'],
    answer: 1,
    explain: 'Nesting r-InfoOwner:HR, r-InfoOwner:Finance… under one parent lets you grant RM functional access once. For content permissions, explicit flat groups on the ACL are easier to audit.' },
  { id: 'an-q-cis-023', domain: 'an-cis', guide: 'an-community-model',
    q: 'True or false: A group should be created only if it is needed for permissions or for a role.',
    options: TF, answer: 0,
    explain: 'True. Every group must be maintained; groups without a purpose in the security model or a role add clutter and risk.' },
  { id: 'an-q-cis-024', domain: 'an-cis', guide: 'an-security-model',
    q: 'Which statement correctly distinguishes privileges from permissions?',
    options: ['Privileges define what a user can do system-wide; permissions define where, on individual items', 'Privileges are per item; permissions are system-wide', 'They are the same thing', 'Permissions only apply to administrators'],
    answer: 0,
    explain: 'A privilege (e.g. create LiveReports) is useless without Add Items permission in a location; full permissions are useless for a type the user has no privilege to create.' },
  { id: 'an-q-cis-025', domain: 'an-cis', guide: 'an-security-model',
    q: 'In the typical CIS role ladder, which permissions does a Controller have beyond a Contributor?',
    options: ['See and See Contents', 'Reserve only', 'Delete Versions and Delete (and, in some designs, Edit Permissions in their own area)', 'System administration rights'],
    answer: 2,
    explain: 'Consumer: See, See Contents. Contributor: + Modify, Edit Attributes, Add Items, Reserve. Controller: + Delete Versions, Delete (often Edit Permissions in own area). Administrator: full.' },
  { id: 'an-q-cis-026', domain: 'an-cis', guide: 'an-security-model',
    q: 'A global company restricts access by region, not by function. How should the top levels of the Enterprise Workspace be organised?',
    options: ['By function, with regional permissions set item by item', 'Alphabetically by document title', 'By year of creation', 'By region, so permissions set at that level are inherited'],
    answer: 3,
    explain: 'Permissions are the main driver of the top levels: divide the workspace the way access must be divided and let inheritance do the rest.' },
  { id: 'an-q-cis-027', domain: 'an-cis', guide: 'an-design-spec',
    q: 'Which sections belong in a CIS design specification? (Choose two.)',
    options: ['Each user’s password policy exceptions', 'Solution implementation, including the roll-out plan', 'Source code of custom modules', 'Solution governance: maintenance and change management'],
    answer: [1, 3],
    explain: 'The specification covers the solution design (four models), solution implementation (initial implementation, roll-out plan) and solution governance (maintenance, change management).' },
  { id: 'an-q-cis-028', domain: 'an-cis', guide: 'an-rollout',
    q: 'Which rollout approach does the design specification template recommend?',
    options: ['Big bang across the whole organisation', 'Each department chooses its own design', 'A phased rollout starting with pilot groups, followed by a repeatable process for each new group', 'Rollout only after every workflow is automated'],
    answer: 2,
    explain: 'Phasing limits change, minimises disruption and builds adoption through incremental successes. Each new group goes through readiness assessment, go/no-go, requirements, design, development, change management, testing and deployment.' },
  { id: 'an-q-cis-029', domain: 'an-cis', guide: 'an-design-spec',
    q: 'In the typical governance model, who provides executive sponsorship, approves information governance policies and authorises funding?',
    options: ['The information governance steering committee', 'The help desk', 'Knowledge champions', 'Contributors'],
    answer: 0,
    explain: 'The steering committee, with business and technical members, governs long-term change to the information architecture. Champions and administrators handle day-to-day maintenance.' },
  { id: 'an-q-cis-030', domain: 'an-cis', guide: 'an-security-model',
    q: 'True or false: The CIS security guidelines recommend making the system as open as possible and restricting only the groups that should not have access.',
    options: TF, answer: 0,
    explain: 'True. Openness fosters collaboration and knowledge sharing; restrictions are applied where the security policy requires them, at inheritance points high in the tree.' },

  // ================================================================ an-docmgmt — Document management design
  { id: 'an-q-doc-001', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'Which three-level folder pattern do the CIS design guidelines recommend?',
    options: ['Region ▸ manager ▸ employee', 'Year ▸ quarter ▸ month', 'Document type ▸ author ▸ version', 'Function ▸ process/activity ▸ subject/document type'],
    answer: 3,
    explain: 'For example Human Resources ▸ Recruiting ▸ Job Descriptions. Functions and processes are less likely to change than the org chart.' },
  { id: 'an-q-doc-002', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'A draft hierarchy has 2026 ▸ 01 January ▸ Invoices, with a handful of documents per month. What do the guidelines suggest?',
    options: ['Add a level per week', 'Collapse levels with the naming convention, e.g. one level “2026-01”, “2026-02”…', 'Store invoices in personal workspaces', 'Replace folders with email'],
    answer: 1,
    explain: 'Collapsing levels by concatenating names saves clicks while keeping meaning; year-first dates sort correctly.' },
  { id: 'an-q-doc-003', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'How many fixed levels “above the line” do the design guidelines recommend?',
    options: ['No more than 2–3', 'Exactly 1', 'At least 6', 'There is no guideline'],
    answer: 0,
    explain: 'Keep the centrally managed top shallow. Put departments at the top level so re-orgs don’t force moves, and nest only sub-departments that won’t move.' },
  { id: 'an-q-doc-004', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'Below the line, how far should the analyst continue designing folders?',
    options: ['Down to individual documents', 'Only one level, always', 'Until the point where permissions and metadata can be set and inherited; users add folders organically below that', 'The analyst never designs below the line'],
    answer: 2,
    explain: 'Design to the inheritance point (usually 3–5 levels at most). Lower levels grow organically, guided by training and roles such as information custodians.' },
  { id: 'an-q-doc-005', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'True or false: For the information model, knowing where to add content is more important than knowing where to find it.',
    options: TF, answer: 0,
    explain: 'True. There are many ways to find content (search, facets, shortcuts, reports), but the add location decides inheritance of permissions, metadata and records rules.' },
  { id: 'an-q-doc-006', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'A department expects about one document per year in each of its proposed sub-folders. What does this suggest?',
    options: ['The structure is perfect', 'More sub-folders are needed', 'The documents should be stored outside Content Server', 'The structure is too fine-grained; merge or collapse levels'],
    answer: 3,
    explain: 'Ask how many items each folder will receive. A few hundred is comfortable; one per year is far too few and adds clicks for nothing.' },
  { id: 'an-q-doc-007', domain: 'an-docmgmt', guide: 'an-information-model',
    q: 'Which permission setting do the guidelines recommend in the fixed top levels of the hierarchy?',
    options: ['Full control for all users', 'See and See Contents only, to preserve the integrity of the structure', 'No permissions at all', 'Delete for contributors'],
    answer: 1,
    explain: 'Limiting the top levels to See and See Contents prevents users from adding, renaming or deleting the framework itself.' },
  { id: 'an-q-doc-008', domain: 'an-docmgmt', guide: 'an-taxonomy-principles',
    q: 'Users regularly hesitate between two folders when filing the same kind of document. Which AIIM taxonomy principle is violated?',
    options: ['Balanced', 'Durable', 'Unambiguous', 'Parsimonious'],
    answer: 2,
    explain: 'An unambiguous taxonomy leaves minimal or no choice about where content belongs.' },
  { id: 'an-q-doc-009', domain: 'an-docmgmt', guide: 'an-taxonomy-principles',
    q: 'Every re-organisation forces the team to move and rename top-level folders. Which principles does the structure fail? (Choose two.)',
    options: ['Durable', 'Meaningful', 'Relevant', 'Hospitable'],
    answer: [0, 3],
    explain: 'A hospitable taxonomy absorbs change without restructuring; a durable one lasts with minimal maintenance. Basing top levels on functions rather than the org chart helps both.' },
  { id: 'an-q-doc-010', domain: 'an-docmgmt', guide: 'an-taxonomy-principles',
    q: 'Which AIIM principle means “no redundancy — only the groupings that are required”?',
    options: ['Intuitive', 'Consistent and predictable', 'Balanced', 'Parsimonious'],
    answer: 3,
    explain: 'Parsimony removes redundant levels and duplicate groupings, such as levels that hold a single sub-folder.' },
  { id: 'an-q-doc-011', domain: 'an-docmgmt', guide: 'an-taxonomy-principles',
    q: 'True or false: A “balanced” taxonomy spreads content evenly in navigable, manageable volumes.',
    options: TF, answer: 0,
    explain: 'True. Avoid one folder with tens of thousands of items next to folders holding one item each.' },
  { id: 'an-q-doc-012', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'A business user asks for “Created by” and “Last modified date” attributes in the HR category. What should the analyst say?',
    options: ['Add them as mandatory fields', 'They already exist as system metadata captured automatically; don’t duplicate them', 'Put them in the document name', 'Use a classification instead'],
    answer: 1,
    explain: 'System metadata (creator, owner, dates, size, versions) is captured automatically. Duplicating it in categories adds effort and inconsistency.' },
  { id: 'an-q-doc-013', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'Documents are added through the standard Add Document page. According to the guidelines, how many category fields will users realistically complete?',
    options: ['1–2', '3–4', '8–10', '15–20'],
    answer: 1,
    explain: 'On a plain add page users won’t fill more than about 3–4 fields. Inside a workflow with a form, about 8–10 is realistic. Inherit everything else from the folder.' },
  { id: 'an-q-doc-014', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'A product attribute has 600 values that fall into 12 product lines, and users struggle with the long list. Which feature helps most?',
    options: ['Cascading attributes, so choosing the product line limits the product list', 'Attribute sets', 'Making the field free text', 'A second category'],
    answer: 0,
    explain: 'Cascading attributes minimise long pick lists by narrowing one field’s values based on another.' },
  { id: 'an-q-doc-015', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'Cost centres change monthly and are maintained in the finance system. How should the cost-centre attribute be designed to minimise maintenance?',
    options: ['A popup list edited by hand every month', 'Free text with training', 'A table key lookup based on a table fed from the finance system', 'One folder per cost centre'],
    answer: 2,
    explain: 'Table key lookups draw values from a table, so the list is maintained once at the source of truth.' },
  { id: 'an-q-doc-016', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'A design proposes attribute sets for data that a workflow will populate automatically. What caution do the guidelines give?',
    options: ['Attribute sets cannot be searched at all', 'Attribute sets delete documents', 'Attribute sets require Records Management', 'Attribute sets can be difficult to populate from a workflow or other automated process'],
    answer: 3,
    explain: 'Use attribute sets only when rows truly belong together, and test how automated processes will fill them.' },
  { id: 'an-q-doc-017', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'HR does not plan an HR-system integration this year, but the analyst still recommends an “Employee ID” attribute. Why?',
    options: ['Content Server requires an ID on every document', 'Capturing key identifiers creates the hook for a future integration', 'It improves full-text indexing speed', 'It replaces the document name'],
    answer: 1,
    explain: 'Key IDs link documents to business systems later — for example when business workspaces are introduced — even if users don’t search on them today.' },
  { id: 'an-q-doc-018', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'True or false: Wherever the folder already implies a metadata value, the design should set it on the folder so documents inherit it instead of users typing it.',
    options: TF, answer: 0,
    explain: 'True. Inherited defaults improve quality and reduce effort: a document in “Recruiting – Job Descriptions” doesn’t need the user to choose HR and Job description again.' },
  { id: 'an-q-doc-019', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'A department has 4 common attributes and two processes each needing 3 specific attributes. Which grouping is usually the best balance?',
    options: ['One category with all 10 fields on every document', 'Ten categories with one field each', 'A common category on the area plus a process category applied to each process folder', 'No categories, only document names'],
    answer: 2,
    explain: 'One big category leaves empty fields everywhere; too many categories mean many tabs and confusing searches. A common category plus process-specific ones is usually the middle ground.' },
  { id: 'an-q-doc-020', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'A customer wants an “information owner” recorded for each area, able to approve access changes and to review records disposition. What did the design guidelines recommend?',
    options: ['A group per area, placed in the Owner Group position, which can also be used to find the first disposition reviewer', 'A free-text attribute on every document', 'A classification tree of owners', 'A note in the folder description'],
    answer: 0,
    explain: 'A group does double duty: it records the owner, controls who manages membership, and can dynamically identify the first reviewer for disposition.' },
  { id: 'an-q-doc-021', domain: 'an-docmgmt', guide: 'an-findability',
    q: 'Which attribute is best shown as a facet rather than a column?',
    options: ['Contract number (unique per document)', 'Exact amount', 'Document ID', 'Region (shared by many documents)'],
    answer: 3,
    explain: 'Facets work for values common to many documents and let users drill down; columns suit values that differ for each document.' },
  { id: 'an-q-doc-022', domain: 'an-docmgmt', guide: 'an-findability',
    q: 'True or false: Columns and facets must be enabled in the administration pages, but can then be configured on folders by the business groups themselves.',
    options: TF, answer: 0,
    explain: 'True. Once enabled centrally they can be self-service, which makes them cheap, high-value parts of the design.' },
  { id: 'an-q-doc-023', domain: 'an-docmgmt', guide: 'an-findability',
    q: 'A legal team wants a simple search screen with only contract type, counterparty and expiry date, placed in their area, without a developer. Which option fits?',
    options: ['A new Content Server module', 'A custom view search (search form) built on their category attributes', 'A database view', 'An OTDS partition'],
    answer: 1,
    explain: 'Custom view search forms can be self-service with basic training. Reports and ActiveView are more powerful but require more investment.' },
  { id: 'an-q-doc-024', domain: 'an-docmgmt', guide: 'an-naming-vocabulary',
    q: 'Which naming practice do the CIS guidelines recommend for folders?',
    options: ['Use plain business language and avoid acronyms; put the broader concept first', 'Use internal acronyms to keep names short', 'Include the owner’s name in every folder', 'Number all folders with random codes'],
    answer: 0,
    explain: 'Names inform users; acronyms fail anyone outside the team. “Recruiting – Job Descriptions” sorts related folders together.' },
  { id: 'an-q-doc-025', domain: 'an-docmgmt', guide: 'an-naming-vocabulary',
    q: 'Departments, customer names and document types are spelled differently across forms and folders. What should the enterprise-level design establish?',
    options: ['A rule that every user chooses their own terms', 'More free-text fields', 'A controlled vocabulary of approved terms, ideally synchronised from the system that is the source of truth', 'Separate repositories per spelling'],
    answer: 2,
    explain: 'A controlled vocabulary feeds folder names, pick lists, lookups and classification trees so the same concept always uses the same term.' },
  { id: 'an-q-doc-026', domain: 'an-docmgmt', guide: 'an-app-settings',
    q: 'Quality wants authors to save several drafts while readers only ever see the last approved version of a procedure. Which feature fits best?',
    options: ['A separate folder per draft', 'Email the final version to readers', 'Reserve the document permanently', 'Major/minor versioning, with drafts as minor versions and published versions as major'],
    answer: 3,
    explain: 'Major/minor versioning separates drafts (1.1, 1.2) from published versions (2.0) and lets readers be limited to major versions.' },
  { id: 'an-q-doc-027', domain: 'an-docmgmt', guide: 'an-app-settings',
    q: 'An engineering manual is assembled from 14 chapter documents that must be released together as one unit. Which feature fits?',
    options: ['A collection', 'A compound document', 'A shortcut per chapter', 'A classification'],
    answer: 1,
    explain: 'Compound documents hold an ordered set of documents that are managed, released and revised together. A collection only gathers references.' },
  { id: 'an-q-doc-028', domain: 'an-docmgmt', guide: 'an-app-settings',
    q: 'Users are confused by the long Add Item menu full of object types they never use. What does the CIS approach recommend?',
    options: ['Train users to ignore it', 'Remove the Add Item menu', 'Restrict object creation privileges for rarely used types so the Add Item list is simplified', 'Give everyone system administration rights'],
    answer: 2,
    explain: 'Object creation and usage privileges control which groups may create each type; restricting them shortens the menu and prevents misuse.' },
  { id: 'an-q-doc-029', domain: 'an-docmgmt', guide: 'an-metadata-design',
    q: 'True or false: The main purpose of document metadata in a CIS design is to replicate the business data held in other systems.',
    options: TF, answer: 1,
    explain: 'False. Metadata exists to find and identify documents. Capture key IDs that link to other systems instead of copying their data.' },

  // ================================================================ an-records — Records management design
  { id: 'an-q-rm-001', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'What links an item to its retention rules in Content Server Records Management?',
    options: ['Its RM classification, which is associated with a retention schedule (RSI)', 'Its folder name', 'Its owner', 'Its MIME type'],
    answer: 0,
    explain: 'RM classifications form the file plan. Each is associated with an RSI that defines retention periods, triggers and disposition actions.' },
  { id: 'an-q-rm-002', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'True or false: The RM design guidelines recommend classifying only declared records and leaving other content unclassified.',
    options: TF, answer: 1,
    explain: 'False. Classify all content — records and non-records. Non-records get classifications with shorter, business-defined retention, so nothing is kept forever by accident.' },
  { id: 'an-q-rm-003', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'Which three options should be considered so that documents receive RM classifications without user intervention?',
    options: ['Email, print and scan', 'Owner, owner group and public access', 'Versions, renditions and shortcuts', 'Default classification, inheritance and intelligent (automatic) classification'],
    answer: 3,
    explain: 'A default classification on a container, inheritance from the parent, and intelligent classification make RM systematic rather than subjective.' },
  { id: 'an-q-rm-004', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'A records manager proposes 400 narrow record series, many with identical periods. What does current RM practice suggest?',
    options: ['Keep all 400 for precision', 'A “big bucket” approach with fewer, broader series', 'Remove retention entirely', 'One series per user'],
    answer: 1,
    explain: 'Big buckets are easier to apply by default, maintain and explain, and reduce misclassification.' },
  { id: 'an-q-rm-005', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'Which statement about Content Server classifications and RM classifications is correct?',
    options: ['CS classifications organise content by subject; RM classifications also govern retention and disposition', 'Both drive retention', 'RM classifications are only for folders', 'CS classifications replace categories'],
    answer: 0,
    explain: 'CS classifications provide subject views and search; RM classifications identify the record series and link to retention rules.' },
  { id: 'an-q-rm-006', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'Which of these is most likely a record?',
    options: ['A reminder email about lunch', 'A personal copy of a public brochure', 'A signed supplier contract', 'An early draft discarded the same day'],
    answer: 2,
    explain: 'A record is kept as evidence of business activity because a law, regulation, contract or business need requires it. Transitory items are not records.' },
  { id: 'an-q-rm-007', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'True or false: Records and non-records can be managed in the same workspace if folders carry the appropriate RM classifications that users inherit as they add content.',
    options: TF, answer: 0,
    explain: 'True. Users work in their normal structure; the right classifications are applied to folders and inherited.' },
  { id: 'an-q-rm-008', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'A customer wants a detailed list of 150 document types as RM metadata in addition to record series. What did the design guidelines advise?',
    options: ['Add the list as a mandatory field', 'Create 150 categories', 'Store document types in folder names only', 'The RM classification of record type should be sufficient; a long document-type list becomes difficult to maintain'],
    answer: 3,
    explain: 'The record series already classifies record type. Extra detailed lists add maintenance and user burden without much value.' },
  { id: 'an-q-rm-009', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'Which retention rule is time-based?',
    options: ['Destroy 10 years after the employee leaves', 'Destroy 7 years after the end of the fiscal year in which the invoice was created', 'Destroy 6 years after the contract terminates', 'Keep until the project closes, then 5 years'],
    answer: 1,
    explain: 'Time-based rules count from a date the system already knows. The others depend on a business event that must be recorded.' },
  { id: 'an-q-rm-010', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'A rule is “destroy 6 years after contract termination”. No integration provides the termination date. What do the guidelines recommend?',
    options: ['Ask users to remember to enter the date', 'Exclude contracts from RM', 'Convert to a time-based rule if possible; otherwise build the event into the process, e.g. a contract-closure workflow step that sets the status', 'Put all contracts on permanent hold'],
    answer: 2,
    explain: 'Event-based rules that rely on users are a burden and a compliance risk: untriggered records are kept forever.' },
  { id: 'an-q-rm-011', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'An item reached the end of its retention period but is subject to a legal hold. What happens?',
    options: ['Disposition is suspended until all holds are removed', 'It is destroyed at the next disposition run', 'The hold is ignored after one year', 'It is moved to the Recycle Bin'],
    answer: 0,
    explain: 'Holds always override retention. The item stays until every hold on it has been released.' },
  { id: 'an-q-rm-012', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'True or false: The RM design guidelines recommend designing the disposition process around the out-of-the-box tools — scheduling, dashboards, email notifications and settings.',
    options: TF, answer: 0,
    explain: 'True. Using standard disposition searches, review assignments and notifications automates and streamlines the process.' },
  { id: 'an-q-rm-013', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'How can the first reviewer of a disposition search for an area be identified automatically?',
    options: ['By the document name', 'By the Public Access setting', 'By the MIME type', 'By placing the area’s information owner group in the Owner Group position of the ACL'],
    answer: 3,
    explain: 'The design guidelines suggest putting the information owner group in the Owner Group position so it can be dynamically assigned as first reviewer for “their” workspace.' },
  { id: 'an-q-rm-014', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'Which two are typical disposition actions? (Choose two.)',
    options: ['Add to favorites', 'Destroy', 'Reserve', 'Export or transfer to an archive'],
    answer: [1, 3],
    explain: 'Disposition actions include destroying, exporting/transferring, changing status or moving to the next retention stage. Reserve and favourites are everyday document functions.' },
  { id: 'an-q-rm-015', domain: 'an-records', guide: 'an-retention-disposition',
    q: 'Who should normally be able to create, apply and release legal holds?',
    options: ['A small Legal Holds role', 'Every contributor', 'Public Access', 'The help desk'],
    answer: 0,
    explain: 'Holds have legal consequences, so a dedicated role manages them, separate from day-to-day contributors.' },
  { id: 'an-q-rm-016', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'Which RM role implements and runs the records management programme enterprise-wide?',
    options: ['Contributor', 'Information custodian', 'Records manager', 'Guest'],
    answer: 2,
    explain: 'The records manager maintains the file plan, schedules and disposition. Custodians support their own group; owners authorise disposition.' },
  { id: 'an-q-rm-017', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'Which RM role provides records support for its own group, for example applying classifications and correcting RM metadata?',
    options: ['Steering committee', 'Legal holds', 'System administrator', 'Information custodian'],
    answer: 3,
    explain: 'Information custodians are the group’s RM contact; the information owner authorises disposition; the records manager runs the programme.' },
  { id: 'an-q-rm-018', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'The RM roles were defined, but at go-live information owners cannot see the items in their disposition reviews. What gotcha did the design ignore?',
    options: ['Using too few categories', 'Defining roles without giving them the required permissions and RM functional access', 'Not enabling facets', 'Using major/minor versions'],
    answer: 1,
    explain: 'Each role needs both permissions (Enterprise, RM and Classifications workspaces) and RM functional access. Map this before go-live — it is hard to fix later.' },
  { id: 'an-q-rm-019', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'In the three-zone approach, how is zone 2 (reference) content handled?',
    options: ['Kept outside Content Server and auto-deleted', 'Kept permanently as corporate records', 'Kept in Content Server document workspaces and disposed of through the disposition process after a set period', 'Printed and archived'],
    answer: 2,
    explain: 'Zone 1 transitory: outside CS, auto-deleted. Zone 2 reference: CS, deleted through disposition after a set period. Zone 3 records: CS, retention schedule.' },
  { id: 'an-q-rm-020', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'True or false: In the three-zone approach, transitory content with no lasting value should be migrated into Content Server records workspaces.',
    options: TF, answer: 1,
    explain: 'False. Transitory content belongs outside Content Server (or is left behind during migration) and is deleted after a short period.' },
  { id: 'an-q-rm-021', domain: 'an-records', guide: 'an-rm-roles-zones',
    q: 'Which two kinds of access must be configured so an RM role can do its job? (Choose two.)',
    options: ['RM functional access for records functions', 'Workflow roles', 'Pulse privileges', 'Permissions on the relevant items and workspaces'],
    answer: [0, 3],
    explain: 'Item permissions decide what a role can see and change; RM functional access decides which records functions (holds, disposition, RM metadata) it can perform.' },
  { id: 'an-q-rm-022', domain: 'an-records', guide: 'an-physical-clearance',
    q: 'An organisation keeps wet-ink original contracts in boxes at an off-site store and wants to know who borrowed which file. Which module addresses this?',
    options: ['Security Clearance', 'Pulse', 'Connected Workspaces', 'Physical Objects'],
    answer: 3,
    explain: 'Physical Objects manages physical items, boxes, locations, labels and circulation, with the same RM rules as electronic records.' },
  { id: 'an-q-rm-023', domain: 'an-records', guide: 'an-physical-clearance',
    q: 'A user has Edit Permissions on a folder but lacks the clearance level of a Secret document inside it. Can the user open the document?',
    options: ['Yes — permissions override clearance', 'No — Security Clearance restricts access in addition to permissions', 'Only in Smart View', 'Only if the document is reserved'],
    answer: 1,
    explain: 'Security Clearance levels and supplemental markings restrict further; access requires permissions and sufficient clearance and markings.' },
  { id: 'an-q-rm-024', domain: 'an-records', guide: 'an-physical-clearance',
    q: 'Programme documents must be visible only to people briefed on a specific codeword programme, regardless of folder. Which feature fits?',
    options: ['A supplemental marking (Security Clearance)', 'A facet', 'A collection', 'Major versions'],
    answer: 0,
    explain: 'Supplemental markings create need-to-know compartments on top of clearance levels and permissions.' },
  { id: 'an-q-rm-025', domain: 'an-records', guide: 'an-physical-clearance',
    q: 'True or false: Physical items managed with Physical Objects can carry the same RM classifications, retention and holds as electronic records.',
    options: TF, answer: 0,
    explain: 'True. Paper and electronic records about the same matter follow the same records rules.' },
  { id: 'an-q-rm-026', domain: 'an-records', guide: 'an-rm-foundations',
    q: 'True or false: The RM design guidelines aim to implement records management with minimal impact on end users.',
    options: TF, answer: 0,
    explain: 'True. Default and inherited classifications, time-based rules and automated disposition keep RM behind the scenes.' },

  // ================================================================ an-collab — Collaboration design
  { id: 'an-q-col-001', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A 7-month office relocation needs a defined team, external stakeholders who only read, discussions and a task list with milestones. Which container fits best?',
    options: ['A community', 'A collection', 'A project', 'A classification tree'],
    answer: 2,
    explain: 'Projects suit time-bound team work and come with roles (Coordinator, Member, Guest), discussions, task lists, milestones and status.' },
  { id: 'an-q-col-002', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Which project role has full control over all items in the project and is the Owner Group of each item?',
    options: ['Guest', 'Member', 'Facilitator', 'Coordinator'],
    answer: 3,
    explain: 'Coordinators have full access; Members write and add items; Guests read. Facilitator is the community role.' },
  { id: 'an-q-col-003', domain: 'an-collab', guide: 'an-collab-design',
    q: 'True or false: Project Guests have read-only access by default.',
    options: TF, answer: 0,
    explain: 'True. Guests read; their permissions can be raised on individual items (for example, to post in one discussion).' },
  { id: 'an-q-col-004', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Why do the design guidelines suggest restricting the privilege to create projects inside governed areas?',
    options: ['Projects cannot hold documents', 'The user who creates a project becomes its Coordinator with full permissions — a “security gap”', 'Projects disable search', 'Projects ignore retention'],
    answer: 1,
    explain: 'Restricting the creation privilege ensures only intended owners create projects and receive full control.' },
  { id: 'an-q-col-005', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Every new customer implementation project should start with the same folders, documents and tasks. What should the design include?',
    options: ['Copying projects with Copy', 'A collection of the model project', 'A project template made from a model project', 'A community'],
    answer: 2,
    explain: 'Projects can’t simply be copied; a project template pre-populates new projects with the structure, documents and tasks of a source project.' },
  { id: 'an-q-col-006', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A project template must be updated with a new folder. How is this done?',
    options: ['Update the source project, then add a new version to the template', 'Edit the template directly in the database', 'Delete all projects created from it', 'Templates cannot be changed'],
    answer: 0,
    explain: 'The template is built from a project; change the source project and add a new version of the template.' },
  { id: 'an-q-col-007', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Engineers at six sites want to share tips, ask questions and accept answers about a technique, across organisational lines. Which container fits best?',
    options: ['A project', 'A personal workspace', 'A business workspace', 'A community'],
    answer: 3,
    explain: 'Communities connect people with a shared interest across teams and offer Q&A, blogs, forums, FAQs and wikis.' },
  { id: 'an-q-col-008', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Who manages membership, roles and content of a community?',
    options: ['The coordinator', 'The facilitator', 'Every guest', 'The records manager'],
    answer: 1,
    explain: 'The facilitator (by default the creator) administers the community.' },
  { id: 'an-q-col-009', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A community must be invisible to non-members and joined only by invitation of the facilitator. Which type should be chosen?',
    options: ['Unlisted', 'Public', 'Private', 'Guest'],
    answer: 0,
    explain: 'Unlisted communities are visible only to members; private ones show name and mission to everyone; public ones let everyone view contents before joining.' },
  { id: 'an-q-col-010', domain: 'an-collab', guide: 'an-collab-design',
    q: 'In a private community, how does a new person usually join?',
    options: ['They join instantly', 'An administrator adds them to Public Access', 'An existing member recommends them and the facilitator approves', 'They cannot join'],
    answer: 2,
    explain: 'Private communities show their name and mission, but membership requires a recommendation and the facilitator’s approval.' },
  { id: 'an-q-col-011', domain: 'an-collab', guide: 'an-collab-design',
    q: 'True or false: Adding a document to a collection changes the document’s permissions to match the collection.',
    options: TF, answer: 1,
    explain: 'False. Collections hold references; items keep their own permissions. The collection’s permissions only govern the collection itself.' },
  { id: 'an-q-col-012', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A quality manager wants a curated list of the 30 most important procedures, stored in many different folders, without moving them. Which tool fits?',
    options: ['A compound document', 'A new folder with copies', 'A project', 'A collection'],
    answer: 3,
    explain: 'A collection gathers references to items in other locations. Copies would create duplicates; a compound document releases items together.' },
  { id: 'an-q-col-013', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A team writes a frequently changing set of how-to pages that many people edit and comment on. Which tool fits best?',
    options: ['A records folder with major versions', 'A wiki', 'A poll', 'A milestone'],
    answer: 1,
    explain: 'Wikis are collaboratively written reference pages, ideal for procedures and FAQs that change often.' },
  { id: 'an-q-col-014', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A team needs to track who does which of 40 one-off preparation tasks before an event, grouped by phase. The tasks differ each time. What is the lightest suitable tool?',
    options: ['A workflow map with 40 steps', 'A community', 'A task list with milestones', 'An RM classification'],
    answer: 2,
    explain: 'Task lists assign and track tasks, grouped by milestones. A workflow is better for stable, repeated processes.' },
  { id: 'an-q-col-015', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Which two statements about project roles are true? (Choose two.)',
    options: ['Roles are implemented as virtual groups, so membership changes don’t require ACL edits', 'Guests can delete any item', 'Members cannot add items', 'Participants can be added and their roles changed at any time'],
    answer: [0, 3],
    explain: 'Project roles behave like groups maintained in the project. Guests read; Members can add items.' },
  { id: 'an-q-col-016', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A project produces final contracts that are corporate records. What should the collaboration design include?',
    options: ['Nothing — projects are temporary', 'Deleting the project after completion', 'Making all guests coordinators', 'A rule for records: RM classifications on the relevant project folders, or moving final documents to the functional records area at a defined point'],
    answer: 3,
    explain: 'Collaboration spaces fill with drafts; decide explicitly where finals live and how they get their retention.' },
  { id: 'an-q-col-017', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Where are community templates kept and who maintains them?',
    options: ['In each user’s personal workspace, by any user', 'In a community templates volume, maintained by administrators', 'Inside OTDS', 'In the Recycle Bin'],
    answer: 1,
    explain: 'Community templates live in a system-wide templates volume and are maintained by administrators or users with system administration rights.' },
  { id: 'an-q-col-018', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Long email threads about a project decision get lost. Which work item should the design introduce inside the project?',
    options: ['A discussion', 'A rendition', 'A hold', 'A facet'],
    answer: 0,
    explain: 'Discussions keep threaded conversations with the project content, visible to the right participants.' },
  { id: 'an-q-col-019', domain: 'an-collab', guide: 'an-collab-design',
    q: 'True or false: The CIS guidelines suggest starting a deployment with documents and email, and adding tools such as discussions and task lists where a specific requirement calls for them.',
    options: TF, answer: 0,
    explain: 'True. Start simple; the other tools are available when a requirement needs them.' },
  { id: 'an-q-col-020', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Which question best separates a project requirement from a functional folder requirement?',
    options: ['Is the content in PDF format?', 'Does the content need full-text search?', 'Does the work have a defined start, end and team?', 'Is the department in Europe?'],
    answer: 2,
    explain: 'Time-bound team work suits a project; ongoing functional work suits the folder hierarchy.' },
  { id: 'an-q-col-021', domain: 'an-collab', guide: 'an-collab-design',
    q: 'A coordinator wants participants to learn about new documents added to the project without checking manually. What should the design specify?',
    options: ['A hold on the project', 'Major/minor versioning', 'A Security Clearance level', 'Project notifications configured by the coordinator'],
    answer: 3,
    explain: 'Coordinators can configure notification options so participants are informed of new items and changes.' },
  { id: 'an-q-col-022', domain: 'an-collab', guide: 'an-collab-design',
    q: 'Which statement about communities is NOT true?',
    options: ['A community can contain sub-communities', 'A community is always restricted to one department', 'Community templates give communities a standard structure', 'Expert groups help identify subject-matter experts'],
    answer: 1,
    explain: 'Communities are designed to connect people across organisational lines; the other statements are true.' },
  { id: 'an-q-col-023', domain: 'an-collab', guide: 'an-collab-design',
    q: 'True or false: In a public community, all users can view the contents before requesting membership.',
    options: TF, answer: 0,
    explain: 'True. Public communities are open for viewing; the facilitator approves or rejects membership requests.' },

  // ================================================================ an-workspaces — Business workspace design
  { id: 'an-q-bw-001', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'What is a business workspace?',
    options: ['A user’s Personal Workspace', 'A search index partition', 'A container for all content about one business object, optionally linked to that object in a business application', 'A project template'],
    answer: 2,
    explain: 'One business object (customer, supplier, employee, contract…) ↔ one workspace, reachable from Content Server and, with Extended ECM, from the business application.' },
  { id: 'an-q-bw-002', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Which business object is the best candidate for a workspace type?',
    options: ['A supplier that accumulates contracts, certificates, orders and correspondence', 'A single payment line', 'A password reset ticket', 'A daily weather reading'],
    answer: 0,
    explain: 'Good candidates accumulate documents over a lifecycle and are how people think (“everything about this supplier”).' },
  { id: 'an-q-bw-003', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Which two elements are defined at the workspace type level? (Choose two.)',
    options: ['Each user’s password', 'The search engine partition', 'The template used to create new workspaces', 'The naming pattern and location of new workspaces'],
    answer: [2, 3],
    explain: 'A workspace type covers the template, name pattern, location, business object mapping, related workspaces and presentation.' },
  { id: 'an-q-bw-004', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Customer workspaces should be named consistently from ERP data, e.g. “100482 – ACME Corp”. How is this best achieved?',
    options: ['Users type the name each time', 'A name pattern on the workspace type built from the mapped attributes', 'A workflow renames every workspace', 'Folder names are ignored'],
    answer: 1,
    explain: 'Name patterns use business object attributes so names are consistent and include the key ID.' },
  { id: 'an-q-bw-005', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Thousands of customer workspaces would land in one folder. What should the workspace type’s location design do?',
    options: ['Group workspaces in sub-locations (e.g. by region or first letter) to keep folders balanced', 'Accept one huge folder', 'Store workspaces in personal workspaces', 'Disable browsing'],
    answer: 0,
    explain: 'The balanced principle applies to workspaces too; location rules can spread them across manageable containers.' },
  { id: 'an-q-bw-006', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'A customer has contracts, opportunities and service cases, each with its own workspace. How should users navigate between them?',
    options: ['By copying documents into each workspace', 'Through the Recycle Bin', 'Through related workspaces defined between the workspace types', 'They cannot be connected'],
    answer: 2,
    explain: 'Related workspace relationships link business objects; links can come from the business system or be added by users.' },
  { id: 'an-q-bw-007', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'True or false: Category values mapped from the business object onto the workspace can be inherited by documents filed in that workspace, reducing data entry.',
    options: TF, answer: 0,
    explain: 'True. This is one of the biggest metadata wins of workspaces: the business object supplies values such as customer number.' },
  { id: 'an-q-bw-008', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'True or false: Business workspaces can only be used when Content Server is connected to an external business application.',
    options: TF, answer: 1,
    explain: 'False. Workspaces can also represent objects that exist only in Content Server (cases, matters, internal projects); metadata is entered at creation instead of mapped.' },
  { id: 'an-q-bw-009', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Which statement reflects the recommended balance between configuration and development for business workspaces?',
    options: ['Write custom code for every workspace type', 'Avoid templates', 'Use database triggers to create workspaces', 'Use configuration (types, templates, roles, perspectives, relationships) first; reserve development for things such as new connectors or custom widgets'],
    answer: 3,
    explain: 'Most workspace design is configuration; custom development belongs on the roadmap.' },
  { id: 'an-q-bw-010', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Which object is usually NOT worth a business workspace?',
    options: ['Employee', 'Individual order line item', 'Contract', 'Customer'],
    answer: 1,
    explain: 'Order lines are too fine-grained and rarely have their own documents; their parent order or customer is a better candidate.' },
  { id: 'an-q-bw-011', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'An employee workspace should start its retention clock when the employee leaves. How should the design support this event-based rule?',
    options: ['Ask HR users to remember to update every document', 'Keep all employee files permanently', 'Let the HR system integration update the workspace status when the employee leaves, triggering retention', 'Use a poll'],
    answer: 2,
    explain: 'Building the event into the integration avoids relying on users — the same advice as for any event-based rule.' },
  { id: 'an-q-bw-012', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Where does a business user working in the ERP typically reach the workspace for a business object?',
    options: ['From inside the business application, where the linked workspace is displayed', 'Only by browsing the Enterprise Workspace', 'By email attachment', 'Through the Admin pages'],
    answer: 0,
    explain: 'With Extended ECM the same workspace is available from Content Server and from the leading application.' },
  { id: 'an-q-bw-013', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Which of these does a workspace template typically contain? (Choose two.)',
    options: ['Every user’s personal settings', 'Search engine configuration', 'The folder structure with categories and RM classifications', 'Workspace roles and their permissions'],
    answer: [2, 3],
    explain: 'The template carries the folders, categories, RM classifications, roles with permissions and standard content that each new workspace starts with.' },
  { id: 'an-q-bw-014', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Why use workspace roles rather than creating a Content Server group for each customer?',
    options: ['Groups are not allowed in workspaces', 'Roles let each workspace have its own members while the permission design lives once in the template', 'Roles are required by OTDS', 'Groups cannot have permissions'],
    answer: 1,
    explain: 'Roles give per-workspace teams without thousands of groups to maintain.' },
  { id: 'an-q-bw-015', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'An analyst fixes a permission error in the supplier template after 800 supplier workspaces exist. What happens to the existing workspaces?',
    options: ['Template changes apply to workspaces created afterwards; existing ones need a planned update', 'They are fixed automatically and instantly', 'They are deleted', 'They lose all documents'],
    answer: 0,
    explain: 'That is why templates are piloted with real objects before rollout and template changes are managed carefully.' },
  { id: 'an-q-bw-016', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Sales users and Legal users should see different tiles when opening the same customer workspace in Smart View. What is configured?',
    options: ['Two templates', 'Two workspace types for the same object', 'Perspectives with rules, e.g. by user group', 'Separate copies of the documents'],
    answer: 2,
    explain: 'Perspectives define the layout (header, metadata, team, related workspaces, documents) and can be selected by rules such as user group or workspace type.' },
  { id: 'an-q-bw-017', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'True or false: Template permissions should name the individual employees who usually work on suppliers.',
    options: TF, answer: 1,
    explain: 'False. Named users in a template end up in every new workspace. Use roles in the template and assign people per workspace.' },
  { id: 'an-q-bw-018', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'A proposed template has six folder levels. What is the main design concern?',
    options: ['Templates cannot have folders', 'Search will stop working', 'RM cannot be applied', 'Every user clicks through the depth in every workspace; keep templates to one or two levels'],
    answer: 3,
    explain: 'Because templates are copied many times, their usability problems multiply. Keep them short and flat.' },
  { id: 'an-q-bw-019', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'What is the best way to ensure every document in a contract workspace receives the correct retention?',
    options: ['Train users to choose an RM classification', 'Put RM classifications on every folder of the workspace template', 'Run a monthly script', 'Use a facet'],
    answer: 1,
    explain: 'RM classifications on template folders are inherited by each new workspace and every document filed there.' },
  { id: 'an-q-bw-020', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Which widget-based element shows who works on a workspace and in which role?',
    options: ['The Recycle Bin', 'The audit log', 'The team (roles) tile in the perspective', 'The facet panel'],
    answer: 2,
    explain: 'Perspectives typically include header, metadata, team, related workspaces, activity and documents tiles.' },
  { id: 'an-q-bw-021', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Finance must read contracts and purchase orders in every supplier workspace but must not see internal evaluations. How should this be designed?',
    options: ['In the template, give the Finance role (or group) Consumer level on Contracts and Purchase Orders and no access on Internal Evaluations', 'Give Finance full control everywhere', 'Create a separate workspace for Finance', 'Use Public Access'],
    answer: 0,
    explain: 'A role-by-folder permission table in the template expresses exactly this, using the Consumer/Contributor/Controller levels.' },
  { id: 'an-q-bw-022', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Which statement about categories in workspace templates is the better design?',
    options: ['A separate category on every folder', 'No categories at all', 'Categories only on documents, never on the workspace', 'One workspace-level category (mapped from the business object) plus a few document-type categories where needed'],
    answer: 3,
    explain: 'Too many categories mean many tabs and confusing searches; a workspace category inherited by documents provides most of the value.' },
  { id: 'an-q-bw-023', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'True or false: Perspectives control what users see; they do not change who has permission to items in the workspace.',
    options: TF, answer: 0,
    explain: 'True. Perspectives are presentation; permissions come from the template, roles and ACLs.' },
  { id: 'an-q-bw-024', domain: 'an-workspaces', guide: 'an-workspace-templates',
    q: 'Who should be involved in designing a workspace template that sales staff will open from the CRM?',
    options: ['Only system administrators', 'The sales users who will open it from the business application, together with the analyst', 'Only the records manager', 'Nobody — use the default'],
    answer: 1,
    explain: 'Templates designed without the people who use them from the business application rarely match how they think about the object.' },
  { id: 'an-q-bw-025', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'Which question should the analyst ask first when a department requests business workspaces?',
    options: ['Which business objects does the work revolve around, and do they accumulate documents over a lifecycle?', 'Which colour should the icon be?', 'How many servers are installed?', 'Which browser do users have?'],
    answer: 0,
    explain: 'Workspace design starts from business objects and their lifecycle; types, templates and perspectives follow.' },
  { id: 'an-q-bw-026', domain: 'an-workspaces', guide: 'an-workspace-design',
    q: 'True or false: A good workspace design maps one business object to one business workspace.',
    options: TF, answer: 0,
    explain: 'True. Each customer, supplier or contract has exactly one workspace; related workspaces connect objects to each other.' },

  // ================================================================ an-workflow-forms — Workflow and form design
  { id: 'an-q-wf-001', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Which elements make up a workflow map? (Choose two.)',
    options: ['A work package with attachments, attributes, comments and forms', 'A search slice', 'An OTDS partition', 'Steps connected by links'],
    answer: [0, 3],
    explain: 'A map consists of linked steps, the work package and general settings such as management permissions and due date calculations.' },
  { id: 'an-q-wf-002', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Which step type automatically routes the workflow based on conditional statements?',
    options: ['User', 'Milestone', 'Initiator', 'Evaluate'],
    answer: 3,
    explain: 'Evaluate steps check conditions — attribute values, form fields, earlier decisions — and follow the matching link.' },
  { id: 'an-q-wf-003', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Management wants to track whether contracts reach “signed” within ten days of the request. Which step type marks this checkpoint?',
    options: ['Item Handler', 'Milestone', 'Process', 'Form Task'],
    answer: 1,
    explain: 'Milestone steps mark points used to monitor the progress of a workflow against time.' },
  { id: 'an-q-wf-004', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Five processes share the same three-step legal approval. What is the best design?',
    options: ['Copy the three steps into all five maps', 'Use one huge map for all five processes', 'Model the approval once and embed it with a Sub-workflow step in each map', 'Use a task list'],
    answer: 2,
    explain: 'Sub-workflow steps embed another map; the main map pauses until it completes. One maintained approval serves many maps.' },
  { id: 'an-q-wf-005', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'After approval, the contract must be moved to “Contracts – Signed” and its category updated with the approval date — without human effort. Which step type does this?',
    options: ['Item Handler', 'Initiator', 'Milestone', 'User'],
    answer: 0,
    explain: 'Item Handler steps act on Content Server items: create folders, add versions, move or copy items, and exchange values between workflow and category attributes.' },
  { id: 'an-q-wf-006', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Which step type sends work back to the person who started the workflow, e.g. to revise a rejected request?',
    options: ['Evaluate step', 'Milestone step', 'Process step', 'Initiator step'],
    answer: 3,
    explain: 'Initiator steps are tasks for the workflow initiator.' },
  { id: 'an-q-wf-007', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'True or false: When a Sub-workflow step runs, the main workflow continues in parallel without waiting.',
    options: TF, answer: 1,
    explain: 'False. The main map pauses, an instance of the embedded map runs, and processing resumes in the main map when it completes.' },
  { id: 'an-q-wf-008', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'According to the scoping guidelines for a first phase, which proposal is in scope?',
    options: ['A new process with 12 user steps and an ERP integration', 'An existing document-centric approval with 4 user steps, one loop back and an 8-field form', 'A workflow with three loops and 25 form fields', 'A cross-system orchestration of five applications'],
    answer: 1,
    explain: 'Phase-1 guidance: an existing solution without major changes, document-centric, about 5 user steps at most, 1 loop back, a form of at most about 10 fields, no integrations.' },
  { id: 'an-q-wf-009', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'A designed map contains a loop that sends rejected documents back to review with no limit. What should the analyst add?',
    options: ['An exit for the loop, e.g. a maximum number of rounds or an escalation path', 'Nothing — loops are self-limiting', 'A second identical loop', 'A milestone at the start only'],
    answer: 0,
    explain: 'Every loop needs an exit; otherwise instances can circle indefinitely. Design for the exception path, not just the happy path.' },
  { id: 'an-q-wf-010', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'The steps of a team’s “process” change every time it runs and depend on the case. What should the analyst consider?',
    options: ['A complex workflow map covering every variant', 'Records Management', 'A lighter tool such as a task list or discussion; workflows suit stable, repeated processes', 'A new workspace type'],
    answer: 2,
    explain: 'Workflows pay off for stable, repeated, auditable processes. Highly variable work needs flexibility rather than routing.' },
  { id: 'an-q-wf-011', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'Which step type can automatically send an email or modify attributes without involving a person?',
    options: ['User step', 'Initiator step', 'Form Task step', 'Process step'],
    answer: 3,
    explain: 'Process steps perform automatic actions such as sending email, modifying attributes or copying attachments.' },
  { id: 'an-q-wf-012', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'What is the most useful first artefact when designing a workflow with business users?',
    options: ['The finished map in the Workflow Designer', 'A swimlane diagram of who does what, in what order, with which documents and decisions', 'The SQL table for the form', 'The audit report'],
    answer: 1,
    explain: 'Swimlanes are easy for business users to validate and reveal decisions, loops and data needs before the map is built.' },
  { id: 'an-q-wf-013', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'Why should a map assign steps to roles or groups instead of named users?',
    options: ['Named users are slower', 'Groups bypass permissions', 'Maps keep working when people are absent or leave, and one map can serve many teams', 'Content Server forbids named users'],
    answer: 2,
    explain: 'Hard-coded people break when they’re away and force map edits; roles and groups change in one place.' },
  { id: 'an-q-wf-014', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'One expense approval map is used by ten departments, each with its own approver. Which design keeps a single map?',
    options: ['Workflow roles filled when the workflow starts (or a user attribute chosen by the requester)', 'Ten copies of the map', 'One named approver for all', 'A community per department'],
    answer: 0,
    explain: 'Workflow roles let participants be chosen at initiation; a performer taken from a workflow attribute is another option.' },
  { id: 'an-q-wf-015', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'True or false: Workflow attributes are kept on the document after the workflow ends, so there is no need to copy them anywhere.',
    options: TF, answer: 1,
    explain: 'False. Workflow attributes belong to the process instance. Values that matter later should be copied to the document’s category, typically with an Item Handler step.' },
  { id: 'an-q-wf-016', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'An Evaluate step must route purchase requests over 10,000 to a director. Where does the amount come from?',
    options: ['The document name', 'The audit log', 'The map’s icon', 'A workflow attribute (or form field) captured earlier in the workflow'],
    answer: 3,
    explain: 'Workflow attributes and form fields supply the data that Evaluate steps test.' },
  { id: 'an-q-wf-017', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'Steps in a running workflow are stuck because the assignee is on long leave. Who should be able to fix this, according to a good design?',
    options: ['Nobody — the instance must be stopped', 'A process owner role holding management rights on the map, who can reassign the step', 'Any user with Public Access', 'Only the database administrator'],
    answer: 1,
    explain: 'Management settings decide who may see status, change attributes, reassign steps and suspend, resume or stop instances. Give these rights to a process owner role.' },
  { id: 'an-q-wf-018', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'Which two settings or decisions belong to the work package design? (Choose two.)',
    options: ['Which documents are attached at the start and what participants may do with them', 'Which workflow attributes are carried and where they are editable', 'The OTDS synchronisation schedule', 'The search federator configuration'],
    answer: [0, 1],
    explain: 'The work package holds attachments, attributes, comments and forms; each must be enabled and designed.' },
  { id: 'an-q-wf-019', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'At the end of a contract workflow, where should the approved document go so that it receives the correct permissions and retention?',
    options: ['Stay in the workflow attachments forever', 'Be emailed to the requester', 'Be moved or copied by an Item Handler step into its functional folder, where it inherits permissions and RM classification', 'Be deleted'],
    answer: 2,
    explain: 'Filing the result where governance applies is the cleanest end to a document-centric workflow.' },
  { id: 'an-q-wf-020', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'True or false: Who may start a workflow is controlled by the permissions on the workflow map itself.',
    options: TF, answer: 0,
    explain: 'True. Users need to see and use the map to initiate it; restrict access to maps that only certain groups may start.' },
  { id: 'an-q-wf-021', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'What does a form template define?',
    options: ['The retention period of the form', 'The workflow performers', 'The OTDS resource', 'The fields (and their types) and the views used by forms created from it'],
    answer: 3,
    explain: 'Forms are instances created from a form template; the template defines the data fields and how they are presented and stored.' },
  { id: 'an-q-wf-022', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'Management wants monthly reports across all submitted access-request forms. Which storage option supports this best?',
    options: ['Keep data only in the workflow work package', 'Store submissions in a SQL table associated with the form template', 'Store the data in the form’s description', 'Store data in folder names'],
    answer: 1,
    explain: 'With SQL table storage each submission becomes a row that reports and external tools can query. Work-package data is only available during the workflow.' },
  { id: 'an-q-wf-023', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'Employees should submit a leave request that automatically starts the approval process. Which form behaviour is designed?',
    options: ['Saving the form as a new version only', 'Emailing the form to HR', 'A submission that initiates a workflow from a chosen map, carrying the form data', 'A collection of forms'],
    answer: 2,
    explain: 'Forms can be configured so that submitting them initiates a workflow; the data travels in the work package.' },
  { id: 'an-q-wf-024', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'Inside a workflow, how many form fields do the CIS guidelines consider realistic for a first phase?',
    options: ['About 8–10', '2', 'About 30', 'Unlimited'],
    answer: 0,
    explain: 'Users completing a task tolerate more fields than on an add page, but about 8–10 (and at most about 10 in the scoping limits) is realistic.' },
  { id: 'an-q-wf-025', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'When should the analyst prefer a form over category attributes?',
    options: ['When the data describes a document for its whole life', 'Never — forms are obsolete', 'Only for folders', 'When capturing a request or data record in its own right — many fields, a designed layout, reporting on submissions, or starting a process'],
    answer: 3,
    explain: 'Categories describe content; workflow attributes describe a process instance; forms capture structured requests and data records.' },
  { id: 'an-q-wf-026', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'Which practice reduces errors and effort on a request form?',
    options: ['Make every field free text', 'Pre-fill what the system knows (requester, department, date) and use lists instead of free text', 'Ask for the same value twice to confirm', 'Hide all mandatory fields until the last step'],
    answer: 1,
    explain: 'Push fields from “typed” to “picked” or “pre-filled”; validate on submission rather than at final approval.' },
  { id: 'an-q-wf-027', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'True or false: If a form’s data is stored only in a workflow’s work package, that data cannot be reached through the form once the workflow data is gone.',
    options: TF, answer: 0,
    explain: 'True. Work-package storage is tied to the workflow; when longer-term access or reporting is needed, choose form versions or a SQL table.' },
  { id: 'an-q-wf-028', domain: 'an-workflow-forms', guide: 'an-forms-design',
    q: 'Which step type assigns a form to a user or group to fill in?',
    options: ['Form Task step', 'Milestone step', 'Item Handler step', 'Evaluate step'],
    answer: 0,
    explain: 'The Form Task step assigns forms to performers as part of the workflow.' },
  { id: 'an-q-wf-029', domain: 'an-workflow-forms', guide: 'an-workflow-design',
    q: 'True or false: A Milestone step assigns a task to a group of users.',
    options: TF, answer: 1,
    explain: 'False. A Milestone marks a checkpoint used to monitor progress. User steps assign tasks to users, groups or roles.' },
  { id: 'an-q-wf-030', domain: 'an-workflow-forms', guide: 'an-workflow-data',
    q: 'True or false: Role groups from the community model make good workflow performers because membership changes in one place and every map follows.',
    options: TF, answer: 0,
    explain: 'True. Assigning steps to role groups such as r-ContractApprovers keeps maps valid when people change.' },
];
