'use strict';
// Exam question bank for the Business User certification (5-0158).
// Scenario-based, original questions; about a fifth are multiple-response.

module.exports = [
  // ---------------------------------------------------------------- bu-fundamentals (10)
  { id: "bu-q-fundamentals-001", domain: "bu-fundamentals", guide: "bu-item-types",
    q: "A product manager wants to draft a proposal that no colleague should be able to see until it is ready. Where should the draft be stored?",
    options: ["In a hidden folder in the Enterprise Workspace", "In the Personal Workspace", "In a collection", "In the Categories Volume"],
    answer: 1,
    explain: "The Personal Workspace is private by default — only its owner and system administrators can see it. A “hidden” display option in the Enterprise Workspace only hides the item from lists; anyone with permission can still find it by search." },
  { id: "bu-q-fundamentals-002", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "Which component authenticates users and provides single sign-on for Content Server?",
    options: ["The Content Server Admin user", "OpenText Directory Services (OTDS)", "The Facets Volume", "Enterprise Connect"],
    answer: 1,
    explain: "OTDS synchronises users and groups (for example from Active Directory) and provides single sign-on. Enterprise Connect is a desktop client, not an identity service." },
  { id: "bu-q-fundamentals-003", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "A user has forgotten their password and the sign-in page offers a self-service reset. What happens next by default?",
    options: ["An administrator must unlock the account first", "The user enters their email address and receives a link valid for 24 hours", "A temporary password is shown on screen", "The user must sign in to Classic View and choose My Account ▸ Change Password"],
    answer: 1,
    explain: "The forgot-password link asks for the email address and sends a reset link, valid 24 hours by default. My Account ▸ Change Password is for users who are already signed in and know their old password." },
  { id: "bu-q-fundamentals-004", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "Which two statements about signing out of Content Server are true? (Choose two.)",
    options: ["Signing out destroys the session cookie", "Signing out deletes your Recent Items list", "Closing the browser also ends the session and is recommended on shared computers", "In Smart View you sign out from the Tools menu"],
    answer: [0, 2],
    explain: "The session cookie identifies you while signed in and is discarded on sign-out or when the browser closes; closing the browser also clears cached pages. Recent Items are unaffected, and Smart View's Sign out is on the profile menu." },
  { id: "bu-q-fundamentals-005", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "In Classic View, where do you find the commands you are allowed to perform on a particular document?",
    options: ["The Add Item menu", "The document's Functions menu", "The Personal menu", "Tools ▸ Search"],
    answer: 1,
    explain: "Every item has a Functions menu listing only the commands your permissions and privileges allow for that item type. The Add Item menu adds new items to the current container." },
  { id: "bu-q-fundamentals-006", domain: "bu-fundamentals", guide: "bu-item-types",
    q: "A team needs one place for everything about customer ACME: contracts, correspondence, the people involved, key data such as the customer number, and follow-up tasks. What is the best fit?",
    options: ["A folder in the Enterprise Workspace", "A collection", "A business workspace", "A compound document"],
    answer: 2,
    explain: "A business workspace represents a business object and combines documents, metadata, team roles and tasks in one Smart View page. A folder or collection holds content but not the people, data and role-based access." },
  { id: "bu-q-fundamentals-007", domain: "bu-fundamentals", guide: "bu-personalize",
    q: "Which two settings can a user change for themselves in Classic View under My Account ▸ Settings ▸ General? (Choose two.)",
    options: ["Default start page", "The system-wide password policy", "Enhanced Keyboard Accessibility Mode", "The global columns shown to all users"],
    answer: [0, 2],
    explain: "The General tab holds personal preferences such as start page, navigation style, sidebar, item link action, languages and keyboard accessibility mode. Password policy lives in OTDS and global columns are set by administrators or knowledge managers." },
  { id: "bu-q-fundamentals-008", domain: "bu-fundamentals", guide: "bu-item-types",
    q: "What does the numeric ID shown in an item's URL (objId= in Classic View, /nodes/ in Smart View) represent?",
    options: ["The current version number", "The item's unique node ID, which stays the same when the item is renamed or moved", "The ID of the folder that contains the item", "The ID of the user who created the item"],
    answer: 1,
    explain: "Every node has a permanent unique ID. Because it never changes, links and references based on it survive renames and moves." },
  { id: "bu-q-fundamentals-009", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "A user wants to import a folder tree of 300 files from a network drive, keeping the sub-folders. Which interface allows this by drag and drop?",
    options: ["Smart View", "Classic View", "Enterprise Connect", "Any of the web interfaces, if the folder is under 9,999 KB"],
    answer: 2,
    explain: "Browser drag-and-drop in Classic View and Smart View accepts files only. Enterprise Connect accepts folders and their contents." },
  { id: "bu-q-fundamentals-010", domain: "bu-fundamentals", guide: "bu-interfaces",
    q: "When you sign in, Content Server uses your identity to determine several things. Which is NOT one of them?",
    options: ["Which items you can see and what you can do with them", "Which item types you may create", "Which tasks are assigned to you", "Which version of Microsoft Office is installed on your PC"],
    answer: 3,
    explain: "Your sign-in determines permissions, privileges, your Personal Workspace, your assignments and auditing. The local Office installation has nothing to do with your Content Server identity." },

  // ---------------------------------------------------------------- bu-content (20)
  { id: "bu-q-content-001", domain: "bu-content", guide: "bu-interfaces",
    q: "In Smart View, a user selects the check boxes of six documents. Where do the actions for all six appear?",
    options: ["In the inline action bar of the first selected row", "In the action bar (toolbar) that appears above the list", "In the Functions menu", "Only in Classic View"],
    answer: 1,
    explain: "Selecting items shows a header action bar with the actions valid for every selected item. The inline action bar appears on hover and acts on one item only." },
  { id: "bu-q-content-002", domain: "bu-content", guide: "bu-organizing",
    q: "A price list maintained by Finance must also be visible in the Sales folder, always showing the latest version. What should be created in the Sales folder?",
    options: ["A copy of the price list", "A shortcut to the price list", "A generation of the price list", "A URL item with the price list's address"],
    answer: 1,
    explain: "A shortcut points to the item itself and therefore always shows the current version. A copy drifts out of date; a generation is fixed to one version; Content Server recommends shortcuts over URLs for internal items." },
  { id: "bu-q-content-003", domain: "bu-content", guide: "bu-organizing",
    q: "Which two statements about shortcuts are true? (Choose two.)",
    options: ["Deleting a shortcut also deletes the original item", "A shortcut does not give access to an original the user has no permission on", "The original's Properties ▸ References tab lists shortcuts pointing to it", "A shortcut always points to the version that existed when it was created"],
    answer: [1, 2],
    explain: "Shortcuts never override the original's permissions, and References lists the shortcuts and generations that point at an item. Deleting a shortcut removes only the pointer, and shortcuts follow the current version." },
  { id: "bu-q-content-004", domain: "bu-content", guide: "bu-organizing",
    q: "A user can see a document and open it but the Move command is missing. Which permission on the document is most likely missing?",
    options: ["Modify", "Edit Attributes", "Delete", "Reserve"],
    answer: 2,
    explain: "Moving removes the item from its current location, so it requires the Delete permission on the item (plus Add Items in the destination)." },
  { id: "bu-q-content-005", domain: "bu-content", guide: "bu-organizing",
    q: "Where does a Content Server 16.2 user restore a document they deleted this morning?",
    options: ["Smart View ▸ Properties ▸ Versions", "Classic View ▸ Tools ▸ Recycle Bin", "Personal ▸ Reserved Items", "Enterprise ▸ Facets Volume"],
    answer: 1,
    explain: "Deleted items wait in the Recycle Bin (Tools ▸ Recycle Bin) until restored or purged; the I Deleted Today view lists them. In 16.2 restore was Classic-only; newer releases add it to Smart View." },
  { id: "bu-q-content-006", domain: "bu-content", guide: "bu-organizing",
    q: "A user tries to delete a document and is refused although they have the Delete permission. What is a likely cause?",
    options: ["The document has a shortcut pointing to it", "A generation points to one of its versions", "The document is in a collection", "The document has a nickname"],
    answer: 1,
    explain: "A generation protects the version it references, so the document cannot be deleted while the generation exists. Shortcuts and collections do not prevent deletion — they simply become broken or lose the member." },
  { id: "bu-q-content-007", domain: "bu-content", guide: "bu-adding-content",
    q: "A user creates a new Word document directly from Content Server using Add Document ▸ New, types text, saves and closes. How many versions does the document have?",
    options: ["One", "Two", "Three", "None until it is unreserved"],
    answer: 1,
    explain: "Content Server first stores a blank version when the document is created and then your saved content as a second version." },
  { id: "bu-q-content-008", domain: "bu-content", guide: "bu-adding-content",
    q: "Which two are valid ways to add a document to a Content Server folder? (Choose two.)",
    options: ["Drag the file from Windows Explorer onto the folder's list in Smart View", "Send it by email to the folder if the folder is email-enabled", "Add it as a favorite", "Apply a category to the folder"],
    answer: [0, 1],
    explain: "Documents can be uploaded, dragged in, created online, emailed to an email-enabled container, added through Enterprise Connect or added in workflows. Favorites and categories do not add content." },
  { id: "bu-q-content-009", domain: "bu-content", guide: "bu-adding-content",
    q: "Which action lets a user read a document without keeping a local copy on their computer?",
    options: ["Download", "Zip & Download", "View (in the browser viewer)", "Reserve with Download"],
    answer: 2,
    explain: "View renders the document in the browser (View as Web Page, Content Suite Viewer or Intelligent Viewing). Download and Zip & Download save local copies." },
  { id: "bu-q-content-010", domain: "bu-content", guide: "bu-adding-content",
    q: "A user drags ten files into a folder whose category has a required attribute but does not supply a value. What happens?",
    options: ["The upload is rejected", "The files are added with an empty value and are visible to everyone", "The files go to an Incomplete Items folder on the user's Assignments page until the value is supplied", "The required attribute is removed from the category"],
    answer: 2,
    explain: "Items added without required values are held in Incomplete Items (Personal ▸ Assignments) and are not available to other users until completed, singly or several at once." },
  { id: "bu-q-content-011", domain: "bu-content", guide: "bu-reserve-edit",
    q: "A colleague has reserved a contract. What can you still do with it if you have See Contents permission?",
    options: ["Add a new version", "View, open and download it", "Unreserve it", "Edit it online"],
    answer: 1,
    explain: "Reservation blocks Reserve, Add Version and Edit for others, but users with access can still view, open and download the document." },
  { id: "bu-q-content-012", domain: "bu-content", guide: "bu-reserve-edit",
    q: "A user edits a Word document online with Edit and then closes Word after saving. Which statement is true?",
    options: ["The user must unreserve the document manually", "Content Server reserved the document automatically and unreserves it after the save", "The changes are saved only locally", "The document is converted to a compound document"],
    answer: 1,
    explain: "Online editing reserves automatically and unreserves when you save and close. Only a reservation you made yourself beforehand stays in place." },
  { id: "bu-q-content-013", domain: "bu-content", guide: "bu-reserve-edit",
    q: "In Classic View, which single action adds an edited file as a new version and releases the reservation?",
    options: ["Add Version", "Unreserve with Add New Version ticked", "Make Generation", "Copy"],
    answer: 1,
    explain: "The Unreserve page has an Add New Version option that uploads your file and removes the lock in one step. Add Version keeps the document reserved." },
  { id: "bu-q-content-014", domain: "bu-content", guide: "bu-reserve-edit",
    q: "A user drags “Budget v2.xlsx” onto a folder containing “Budget.xlsx”, hoping to add a version. What happens?",
    options: ["A new version is added to Budget.xlsx", "A new document named Budget v2.xlsx is created", "The upload fails with an error", "Budget.xlsx is replaced and its history deleted"],
    answer: 1,
    explain: "Drag-and-drop adds a version only when the file name matches an existing document exactly; otherwise a new document is created." },
  { id: "bu-q-content-015", domain: "bu-content", guide: "bu-organizing",
    q: "Which two items cannot be copied or moved on their own? (Choose two.)",
    options: ["A release of a compound document", "A shortcut", "Your Personal Workspace", "A text document"],
    answer: [0, 2],
    explain: "Releases and revisions travel with their compound document, and the Enterprise and Personal Workspaces themselves cannot be copied or moved. Shortcuts and text documents can." },
  { id: "bu-q-content-016", domain: "bu-content", guide: "bu-organizing",
    q: "In Smart View, while copying documents that carry categories into a folder that has its own category, which choice does the Copy dialog offer?",
    options: ["Keep original properties, apply destination properties, or combine them", "Copy only the latest version or all versions", "Copy as shortcut or as generation", "Convert to PDF or keep the format"],
    answer: 0,
    explain: "Smart View copy and move let you keep the item's own categories, take the destination's, or merge both." },
  { id: "bu-q-content-017", domain: "bu-content", guide: "bu-organizing",
    q: "Why might the URL option be missing from a user's Add Item menu even though they have Add Items permission on the folder?",
    options: ["URLs can only be added in Personal Workspaces", "Creating URL items is a privilege that has not been granted to the user", "The folder has a category applied", "URL items are only available in Enterprise Connect"],
    answer: 1,
    explain: "Item types such as URL are controlled by object (item-creation) privileges. Permissions on the folder are not enough." },
  { id: "bu-q-content-018", domain: "bu-content", guide: "bu-interfaces",
    q: "Which statement correctly compares the interfaces?",
    options: ["Enterprise Connect bypasses Content Server permissions for local files", "Smart View and Classic View show different repositories", "All three interfaces work on the same items with the same permissions", "Classic View cannot add versions"],
    answer: 2,
    explain: "Smart View, Classic View and Enterprise Connect are different windows onto the same repository; permissions apply identically everywhere." },
  { id: "bu-q-content-019", domain: "bu-content", guide: "bu-reserve-edit",
    q: "Opening a document from Enterprise Connect by double-clicking it (default configuration). Which statement is true?",
    options: ["It reserves the document until Word is closed", "It does not reserve the document; use Edit or Reserve to lock it", "It creates a briefcase", "It adds a minor version"],
    answer: 1,
    explain: "Opening is read-only and does not prevent others from editing. Edit (or Reserve) from the context menu reserves the document." },
  { id: "bu-q-content-020", domain: "bu-content", guide: "bu-collections",
    q: "A user opens a collection and selects Delete on three members. What is the result?",
    options: ["The three items are removed from the collection only", "The three original items are deleted from their folders", "The collection is deleted", "Nothing — collections are read-only"],
    answer: 1,
    explain: "Delete acts on the originals. To take items out of a collection without deleting them, use Remove Items from Collection." },

  // ---------------------------------------------------------------- bu-metadata (10)
  { id: "bu-q-metadata-001", domain: "bu-metadata", guide: "bu-categories",
    q: "What is the relationship between categories and attributes?",
    options: ["An attribute is a container of categories", "A category is a named set of attributes that can be applied to items", "Categories are system metadata; attributes are custom metadata", "They are two names for the same thing"],
    answer: 1,
    explain: "Attributes are the individual metadata fields; a category groups them so they can be applied to items together. Both are custom metadata, unlike system attributes such as created date." },
  { id: "bu-q-metadata-002", domain: "bu-metadata", guide: "bu-categories",
    q: "A category is applied to a folder that already contains 200 documents. What happens to the existing documents?",
    options: ["They receive the category immediately", "Nothing, unless the user selects Apply to Sub-Items", "They are moved to Incomplete Items", "They are locked until values are entered"],
    answer: 1,
    explain: "Folder categories are inherited by items added afterwards. Existing children only receive the category if you use Apply to Sub-Items." },
  { id: "bu-q-metadata-003", domain: "bu-metadata", guide: "bu-categories",
    q: "Which permission does a user need on a document to change its category attribute values?",
    options: ["Modify", "Edit Attributes", "Reserve", "Edit Permissions"],
    answer: 1,
    explain: "Edit Attributes allows changing attribute values. Modify covers name, description and display options." },
  { id: "bu-q-metadata-004", domain: "bu-metadata", guide: "bu-categories",
    q: "A category uses cascading attributes Country → State → City. A user tries to choose a City first and sees “No values found”. Why?",
    options: ["The City list is empty in the database", "Cascading attributes must be filled parent first", "The user lacks See Contents on the category", "Cascading attributes only work in Classic View"],
    answer: 1,
    explain: "A cascading (Table Key Lookup) child's valid values depend on the parent's value, so the parent must be chosen first." },
  { id: "bu-q-metadata-005", domain: "bu-metadata", guide: "bu-categories",
    q: "Which two statements about category design are true? (Choose two.)",
    options: ["A Flag (checkbox) attribute cannot be required", "An attribute set can be marked required as a whole", "Multi-valued attributes are limited to a maximum number of rows", "Categories cannot be changed once applied"],
    answer: [0, 2],
    explain: "A required checkbox would always have to be ticked, so flags cannot be required; multi-value attributes have a defined maximum (up to 50). Sets cannot be required — their members can — and categories are versioned and can be changed and upgraded." },
  { id: "bu-q-metadata-006", domain: "bu-metadata", guide: "bu-categories",
    q: "A knowledge manager added an attribute to a category in use. On a document's Categories tab an Upgradable indicator now appears. What does the user do to apply the new definition to that document?",
    options: ["Remove and re-add the category", "Select Upgrade", "Add a new version", "Nothing — it happens automatically overnight"],
    answer: 1,
    explain: "Category definitions are versioned; items keep their old data until upgraded with Upgrade (per item) or Upgrade Items (from the category)." },
  { id: "bu-q-metadata-007", domain: "bu-metadata", guide: "bu-metadata-display",
    q: "Which nickname would Content Server accept?",
    options: ["12345", "Q3 Report", "q3report", "q3-report"],
    answer: 2,
    explain: "Nicknames must be unique, not purely numeric, at most 40 characters, with no spaces and no special characters such as hyphens." },
  { id: "bu-q-metadata-008", domain: "bu-metadata", guide: "bu-metadata-display",
    q: "Spanish-speaking users should see the Spanish names of documents where translations exist. What must each user set?",
    options: ["The interface language on the sign-in page", "The Metadata Language in their personal settings", "A Spanish search slice", "A Spanish category"],
    answer: 1,
    explain: "Multilingual metadata stores names and descriptions per language; each user's Metadata Language decides which one they see. The interface language only translates menus and labels." },
  { id: "bu-q-metadata-009", domain: "bu-metadata", guide: "bu-metadata-display",
    q: "Which two statements about custom columns are true? (Choose two.)",
    options: ["Each data source can be used by only one column", "Any user can create custom columns in any folder", "Users add available columns for themselves under My Account ▸ Settings ▸ Columns", "The Type and Name columns can be hidden"],
    answer: [0, 2],
    explain: "Columns are created by administrators or knowledge managers in the Facets Volume, one per data source, and users choose personal columns in their settings. Type and Name are always shown." },
  { id: "bu-q-metadata-010", domain: "bu-metadata", guide: "bu-metadata-display",
    q: "An attribute “Invoice number” has thousands of distinct values. How should it be surfaced for browsing?",
    options: ["As a facet", "As a custom column", "As a nickname", "As a slice"],
    answer: 1,
    explain: "Facets suit attributes with a limited set of values (status, type, region); attributes with unlimited values are better shown as columns." },
  // ---------------------------------------------------------------- bu-versions (9)
  { id: "bu-q-versions-001", domain: "bu-versions", guide: "bu-versions",
    q: "A document uses advanced (major/minor) versioning. A user with only See Contents permission opens it. Which versions can they access?",
    options: ["All versions", "Major versions only", "Minor versions only", "Only the latest version, whatever its type"],
    answer: 1,
    explain: "Minor versions are treated as work in progress. Read-only users (See, See Contents, also Modify and Edit Attributes) see major versions only; Reserve or higher is needed for minor versions." },
  { id: "bu-q-versions-002", domain: "bu-versions", guide: "bu-versions",
    q: "With advanced versioning, what number does a newly added document get?",
    options: ["1", "1.0", "0.1", "0.0"],
    answer: 2,
    explain: "Under major/minor versioning the first upload is minor version 0.1; it becomes 1.0 only when a major version is added or a minor one is promoted." },
  { id: "bu-q-versions-003", domain: "bu-versions", guide: "bu-versions",
    q: "Which two statements about Promote to Major are true? (Choose two.)",
    options: ["It is available only with advanced versioning", "It can be undone with Demote", "The promoted minor version becomes the next major version", "Any user with See Contents can promote"],
    answer: [0, 2],
    explain: "Promotion turns a minor version into the next major version and exists only under advanced versioning. It cannot be undone, and it requires a high permission level (Edit Permissions in the course's permission table)." },
  { id: "bu-q-versions-004", domain: "bu-versions", guide: "bu-versions",
    q: "A document has versions 1–5; versions 1 and 2 are locked. The Max. Versions limit is set to 3 and version 6 is added. Which versions remain?",
    options: ["4, 5, 6", "1, 2, 4, 5, 6", "1, 2, 6", "All six"],
    answer: 1,
    explain: "The limit keeps the three most recent versions (4, 5, 6) but never deletes locked versions (1, 2) or versions referenced by generations. Only version 3 is deleted." },
  { id: "bu-q-versions-005", domain: "bu-versions", guide: "bu-versions",
    q: "A team wants a permanent pointer to the exact version of a policy that the board approved, while authors keep updating the policy. What should they create?",
    options: ["A shortcut", "A generation", "A collection", "A copy in the same folder"],
    answer: 1,
    explain: "A generation points to one specific version and protects it from deletion; a shortcut always follows the latest version." },
  { id: "bu-q-versions-006", domain: "bu-versions", guide: "bu-compound-docs",
    q: "A user reserves a compound document. What does this prevent?",
    options: ["Others from adding versions to its elements", "Others from reordering, adding or deleting its elements", "Others from viewing its elements", "Creation of shortcuts to it"],
    answer: 1,
    explain: "Reserving a compound document locks its structure only. Each element remains a normal document that others can reserve and version." },
  { id: "bu-q-versions-007", domain: "bu-versions", guide: "bu-compound-docs",
    q: "Which two statements about compound document releases and revisions are true? (Choose two.)",
    options: ["A release must exist before a revision can be created", "Revisions are numbered 1.0, 2.0, 3.0", "A release contains read-only copies of the current versions of the elements", "Releases can be moved independently of the compound document"],
    answer: [0, 2],
    explain: "Releases (1.0, 2.0) are major snapshots and revisions (1.1, 1.2) minor ones based on the latest release, so a release comes first. Releases hold read-only copies and travel with the compound document." },
  { id: "bu-q-versions-008", domain: "bu-versions", guide: "bu-compound-docs",
    q: "In a compound document's Reorganize page, what does marking an element as Master Document do?",
    options: ["It makes the element read-only", "It always displays the element first, ahead of the numbered elements", "It reserves the element to the compound document's owner", "It creates a release"],
    answer: 1,
    explain: "The master (for example a cover letter or table of contents) is shown at the top, like number 0. Other elements follow in numeric order." },
  { id: "bu-q-versions-009", domain: "bu-versions", guide: "bu-versions",
    q: "What is a rendition?",
    options: ["A shortcut to a specific version", "An alternative file format (for example PDF) attached to a particular version", "A copy of a document in another folder", "A minor version waiting for promotion"],
    answer: 1,
    explain: "Renditions are additional formats of a version, added manually or by a rendition engine, typically read-only PDF or HTML for publishing." },

  // ---------------------------------------------------------------- bu-permissions (17)
  { id: "bu-q-permissions-001", domain: "bu-permissions", guide: "bu-permissions",
    q: "A user can see a folder's name in the list but gets no list of its contents when opening it. Which permission do they have?",
    options: ["See only", "See Contents", "Modify", "Add Items"],
    answer: 0,
    explain: "See shows that an item exists. See Contents is needed to list a folder's contents or open a document." },
  { id: "bu-q-permissions-002", domain: "bu-permissions", guide: "bu-permissions",
    q: "Which three entries make up the Default Access part of an ACL? (Choose three.)",
    options: ["Owner", "Owner Group", "Public Access", "Department Group", "Group Leader"],
    answer: [0, 1, 2],
    explain: "Default access is Owner, Owner Group and Public Access (system administrators also have hidden full access). Department groups and group leaders belong to user/group administration, not ACLs." },
  { id: "bu-q-permissions-003", domain: "bu-permissions", guide: "bu-permissions",
    q: "What does the Public Access entry on an ACL represent?",
    options: ["Anonymous internet users", "All users whose account has the Public Access privilege enabled", "Members of the DefaultGroup", "The item's owner group"],
    answer: 1,
    explain: "Public Access covers every user with the Public Access privilege. Removing that entry is the quick way to make an item non-public." },
  { id: "bu-q-permissions-004", domain: "bu-permissions", guide: "bu-permissions",
    q: "A user cannot find the Permissions command on a document's Functions menu. What is the reason?",
    options: ["The document is reserved", "The user lacks the Edit Permissions permission on it", "The document has no category", "Permissions can only be viewed in Smart View"],
    answer: 1,
    explain: "The Classic Permissions page is available only to users with Edit Permissions on the item." },
  { id: "bu-q-permissions-005", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "Raj adds a document to a folder owned by Ana. Which statement describes the new document's ACL?",
    options: ["Ana is the owner and has full control", "Raj is the owner and receives the folder's owner permissions; other entries are copied from the folder", "Raj is the owner with Edit Permissions, regardless of the folder", "The document has an empty ACL until permissions are set"],
    answer: 1,
    explain: "The parent's ACL is copied to the new item, but the creator becomes the owner and gets the permission set the folder defines for its owner." },
  { id: "bu-q-permissions-006", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "A manager grants group Auditors See Contents on a folder with Apply To: This Item. What happens to the 50 documents already in the folder?",
    options: ["They inherit the new entry automatically", "Nothing — they keep their own ACLs", "They become hidden", "They are moved to the Auditors' workspace"],
    answer: 1,
    explain: "Inheritance happens by copying at creation time. To change existing children, apply the change to Sub-Items or This Item & Sub-Items." },
  { id: "bu-q-permissions-007", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "A confidential report is moved from a restricted folder into a folder that everyone can read. Who can read the report after the move?",
    options: ["Everyone who can read the destination folder", "Only users on the report's own ACL", "Only the person who moved it", "Nobody until permissions are reset"],
    answer: 1,
    explain: "A moved item keeps its own permissions. A copy, by contrast, would take on the destination's ACL." },
  { id: "bu-q-permissions-008", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "Which two things happen when a user copies a document to another folder? (Choose two.)",
    options: ["The copy takes the permissions of the destination folder", "The copy keeps the original's ACL", "The user who copies becomes the owner of the copy", "The original is moved to the Recycle Bin"],
    answer: [0, 2],
    explain: "A copy behaves like a newly added item: it receives the destination's ACL and the copier becomes its owner." },
  { id: "bu-q-permissions-009", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "During Apply to Sub-Items, which items are skipped? (Choose two.)",
    options: ["Items on which the user does not have Edit Permissions", "Documents with more than ten versions", "Project workspaces", "Items with categories"],
    answer: [0, 2],
    explain: "You can only change ACLs you are allowed to edit, and project permissions are governed by project roles, so projects are never changed by a parent folder update. Work items are skipped unless their type is included." },
  { id: "bu-q-permissions-010", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "On the Edit Sub-Items Permissions page, which action adds a group to sub-items where it is missing and overwrites its permissions where it already exists?",
    options: ["Add", "Replace", "Add & Replace", "Remove Group/User"],
    answer: 2,
    explain: "Add & Replace does both. Add only adds missing entries or extra permissions; Replace only changes existing entries." },
  { id: "bu-q-permissions-011", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "Which two statements about eDiscovery rights are true? (Choose two.)",
    options: ["They are granted by an administrator and switched on by the user with eDiscovery Mode", "They let the user change any item's permissions", "Use of eDiscovery Mode is audited", "They are a permission set on each folder's ACL"],
    answer: [0, 2],
    explain: "eDiscovery rights are a user privilege; the user enables eDiscovery Mode in settings (an orange bar shows it is on) to see contents of all items for search, browse and collection. It is audited and grants no right to change items or ACLs." },
  { id: "bu-q-permissions-012", domain: "bu-permissions", guide: "bu-permissions-inheritance",
    q: "An information manager needs to see, across a whole folder branch, which groups have which permissions on each item. Which tool is designed for this?",
    options: ["Permissions Explorer", "The Recycle Bin", "A virtual folder", "The Reserved Items page"],
    answer: 0,
    explain: "Permissions Explorer shows a branch as a tree with a grid of users/groups and their permissions, so broken inheritance or excessive rights stand out, and allows adjustments where you hold Edit Permissions." },
  { id: "bu-q-permissions-013", domain: "bu-permissions", guide: "bu-perspectives",
    q: "A department lead with Edit Permissions on the Finance folder wants to redesign the folder's Smart View page but sees no Edit page option. What is missing?",
    options: ["See Contents on the folder", "The perspective editing (Perspective Manager) usage privilege granted by an administrator", "A category on the folder", "Pulse enabled on the folder"],
    answer: 1,
    explain: "Editing perspectives needs a usage privilege granted by an administrator in addition to permission on the container (local) or perspective item (global). Folder permissions alone are not enough." },
  { id: "bu-q-permissions-014", domain: "bu-permissions", guide: "bu-permissions",
    q: "Collections, discussions and task lists use a simpler permission model. Which levels does it have?",
    options: ["See, See Contents, Modify, Delete", "None, Read, Write, Administer", "Viewer, Editor, Owner", "Guest, Member, Coordinator"],
    answer: 1,
    explain: "Work items use None, Read, Write and Administer. Guest/Member/Coordinator are project roles." },
  { id: "bu-q-permissions-015", domain: "bu-permissions", guide: "bu-users-groups",
    q: "A user has Add Items on a folder but cannot add a workflow map there. What is the most likely cause?",
    options: ["They lack See Contents", "They lack the object privilege to create workflow maps", "The folder is reserved", "Workflow maps can only be added in Personal Workspaces"],
    answer: 1,
    explain: "Which item types a user can create is controlled by object (item-creation) privileges, separately from ACL permissions." },
  { id: "bu-q-permissions-016", domain: "bu-permissions", guide: "bu-users-groups",
    q: "What can a group leader do?",
    options: ["Grant System Administration rights", "Add and remove members of that group and delete the group", "Change every ACL in the system", "Reset other users' passwords in OTDS"],
    answer: 1,
    explain: "A group leader manages that one group's membership (and can delete it) without needing user-administration privileges." },
  { id: "bu-q-permissions-017", domain: "bu-permissions", guide: "bu-permissions",
    q: "Which practice reduces the effort of maintaining access as staff change roles?",
    options: ["Grant permissions to individual users on each document", "Grant permissions to groups and manage group membership", "Give every user Edit Permissions", "Remove the Owner entry from every item"],
    answer: 1,
    explain: "Granting access to groups means a role change is a single membership change. Long user-by-user ACLs are slow to maintain and hurt performance." },

  // ---------------------------------------------------------------- bu-search (17)
  { id: "bu-q-search-001", domain: "bu-search", guide: "bu-search",
    q: "Two users run the same search and get different numbers of results. What is the most likely explanation?",
    options: ["The index is different per user", "Search results are filtered by each user's permissions", "One user searched in Smart View", "Results are random"],
    answer: 1,
    explain: "The index covers all content, but results are filtered so each user sees only items they have permission to see." },
  { id: "bu-q-search-002", domain: "bu-search", guide: "bu-search",
    q: "Which slice searches the current folder and everything beneath it?",
    options: ["Enterprise", "From Here", "Enterprise [All Versions]", "Help"],
    answer: 1,
    explain: "From Here limits the search to the current container and its descendants. Enterprise covers the Enterprise Workspace and your Personal Workspace." },
  { id: "bu-q-search-003", domain: "bu-search", guide: "bu-search",
    q: "A phrase that was deleted from the current version of a document appears only in an older version. Which slice will find it?",
    options: ["From Here", "Enterprise", "Enterprise [All Versions]", "Help"],
    answer: 2,
    explain: "Standard slices search only the latest versions; Enterprise [All Versions] searches every version." },
  { id: "bu-q-search-004", domain: "bu-search", guide: "bu-search",
    q: "Which query finds documents containing the word “solar” but not the word “energy”?",
    options: ["solar OR energy", "solar AND-NOT energy", "\"solar energy\"", "solar* energy"],
    answer: 1,
    explain: "AND-NOT (or &!) excludes the second term. OR finds either word, and quotes search the exact phrase." },
  { id: "bu-q-search-005", domain: "bu-search", guide: "bu-search",
    q: "A user searches for “camp” and expects to also find “camping” and “campsite”. What should they type?",
    options: ["camp", "camp*", "camp?", "\"camp\""],
    answer: 1,
    explain: "The * wildcard matches any ending and is never added automatically. ? matches exactly one character." },
  { id: "bu-q-search-006", domain: "bu-search", guide: "bu-search",
    q: "Which two statements about the search bar are true? (Choose two.)",
    options: ["Search terms are case-sensitive", "Leaving the search field empty is the same as searching for *", "The search also covers metadata such as names and attributes", "The search bar only searches the current folder"],
    answer: [1, 2],
    explain: "An empty query equals * (useful with type or date filters), and the index includes metadata as well as content. Terms are not case-sensitive and the scope depends on the chosen slice." },
  { id: "bu-q-search-007", domain: "bu-search", guide: "bu-search",
    q: "After a search returns 400 results, a user wants to narrow them to PDF files authored by one colleague without re-entering the query. What should they use?",
    options: ["A new slice", "The search filters (facets) on the results page", "A prospector", "The Recycle Bin"],
    answer: 1,
    explain: "Search filters list the most common values in the current result set (file type, author, date, category…) and narrow it in place." },
  { id: "bu-q-search-008", domain: "bu-search", guide: "bu-search",
    q: "A user knows a document's nickname is “safetyplan”. What is the fastest way to open it?",
    options: ["Full-text search for safetyplan in the Help slice", "Search type Nickname, enter safetyplan, action Open", "Browse the Enterprise Workspace", "Create a prospector"],
    answer: 1,
    explain: "The Nickname search type finds the item with that exact nickname and can open it or its properties directly." },
  { id: "bu-q-search-009", domain: "bu-search", guide: "bu-advanced-search",
    q: "Which page lets you search for documents whose Contract Status attribute equals Signed?",
    options: ["The search bar's Nickname search", "The Advanced Search page with the category added to the form", "The Recent Items page", "Personal ▸ Reserved Items"],
    answer: 1,
    explain: "On Advanced Search, add Categories, select the category and fill in the attribute values to search on." },
  { id: "bu-q-search-010", domain: "bu-search", guide: "bu-advanced-search",
    q: "Every Monday a team lead runs exactly the same search and wants colleagues to run it too. What should be created?",
    options: ["A personal search form", "A saved search query with permissions for the colleagues", "A snapshot", "A Search Results Template"],
    answer: 1,
    explain: "A saved query is an item that re-runs its full criteria on current content and can be shared via permissions. A snapshot freezes results; a search form is a reusable framework." },
  { id: "bu-q-search-011", domain: "bu-search", guide: "bu-advanced-search",
    q: "What is the key difference between a search form and a saved query?",
    options: ["A search form is shared automatically with everyone", "A search form preserves a framework of criteria, with or without terms; a saved query stores complete criteria as an item that can be shared", "A saved query stores results; a search form re-runs them", "There is no difference"],
    answer: 1,
    explain: "Use a form when you start from the same set-up but add different terms; use a query when you run the same search repeatedly." },
  { id: "bu-q-search-012", domain: "bu-search", guide: "bu-advanced-search",
    q: "A compliance officer wants to be told whenever newly indexed documents mention “recall notice”. Which feature fits?",
    options: ["A snapshot", "A prospector with email notification", "A virtual folder", "A LiveReport"],
    answer: 1,
    explain: "Prospectors continuously scan newly indexed content for matches and can email results on a schedule." },
  { id: "bu-q-search-013", domain: "bu-search", guide: "bu-advanced-search",
    q: "Which two statements about LiveReports are true? (Choose two.)",
    options: ["They query the Content Server database and can return information a search cannot, such as user and group data", "They search the full text of documents", "Most users are allowed to run them but not to create them", "They are stored only in Personal Workspaces"],
    answer: [0, 2],
    explain: "LiveReports run against the database (results as tables or charts) and cannot search document text. Creating them needs SQL knowledge and a privilege; most users only run them. Most live in the Reports Volume." },
  { id: "bu-q-search-014", domain: "bu-search", guide: "bu-advanced-search",
    q: "On the Advanced Search page, which Within option restricts a full-text search to names, descriptions and attributes?",
    options: ["All", "Content", "Metadata", "Synonyms of"],
    answer: 2,
    explain: "Within: Metadata searches only the metadata. Content searches the text of the item; All searches both. Synonyms of is a Modifier." },
  { id: "bu-q-search-015", domain: "bu-search", guide: "bu-advanced-search",
    q: "A user is unsure whether a supplier is spelled “Thomson” or “Thompson”. Which Advanced Search modifier helps?",
    options: ["Word ends with", "Sounds like", "Related to", "Exact phrase"],
    answer: 1,
    explain: "Sounds like broadens the query to words that sound similar, useful when spelling is uncertain." },
  { id: "bu-q-search-016", domain: "bu-search", guide: "bu-metadata-display",
    q: "A user filters a folder with facets (Owner = me, Content type = Document) and wants to reopen exactly this filtered, always-current view next week. What should they save?",
    options: ["A snapshot", "A virtual folder", "A collection", "A generation"],
    answer: 1,
    explain: "A virtual folder saves the facet selection and the location; opening it re-applies the filters to current content. A snapshot would freeze today's list." },
  { id: "bu-q-search-017", domain: "bu-search", guide: "bu-search",
    q: "Which two actions can be applied directly to selected items on a Classic search results page? (Choose two.)",
    options: ["Add to Collection", "Apply Categories", "Promote to Major", "Create Release"],
    answer: [0, 1],
    explain: "Search results offer actions such as Add to Collection, Apply Categories, Zip & Download, Zip & Email, Print and Save Your Results. Promoting versions and creating releases are item-specific functions." },
  // ---------------------------------------------------------------- bu-collab (8)
  { id: "bu-q-collab-001", domain: "bu-collab", guide: "bu-email",
    q: "A user must send three documents to an external auditor who has no Content Server account. Which option is appropriate?",
    options: ["Email Link", "Zip & Email with Attach Archive set to As File", "Zip & Email with Attach Archive set to As URL reference", "Copy link in Smart View"],
    answer: 1,
    explain: "External recipients cannot follow Content Server links, so the zip must travel as an attachment. Links (and URL references) suit internal users with permission." },
  { id: "bu-q-collab-002", domain: "bu-collab", guide: "bu-email",
    q: "Which two statements about email-enabled containers are true? (Choose two.)",
    options: ["Sending a document whose name already exists in the container adds a new version", "Anyone on the internet can add items by email", "A container with required attribute values rejects items sent by email", "Enabling it requires only See Contents on the folder"],
    answer: [0, 2],
    explain: "Matching names become versions, and required attributes block email additions (the sender gets an error). Senders must be Content Server users with Add Items, and enabling needs Edit Permissions." },
  { id: "bu-q-collab-003", domain: "bu-collab", guide: "bu-email",
    q: "An email-enabled folder is set to store the Full message. What is created when an email with two attachments arrives?",
    options: ["Two documents only", "A compound document named after the subject containing the message body and the attachments", "A single .msg file", "A discussion topic"],
    answer: 1,
    explain: "Full message stores a compound document with the body (and headers) plus the attachments. Attachments only keeps just the files; Email object keeps the message." },
  { id: "bu-q-collab-004", domain: "bu-collab", guide: "bu-email",
    q: "What does an email folder offer that an ordinary folder does not?",
    options: ["Automatic forwarding of mail", "Extra columns such as From, To, Subject, Sent Date and Received Date", "Its own email address by default", "Version control for emails"],
    answer: 1,
    explain: "Email folders display email metadata columns so large volumes of mail can be scanned. An email address comes from email-enabling a container, which is separate." },
  { id: "bu-q-collab-005", domain: "bu-collab", guide: "bu-email",
    q: "Emailed links to items open their Properties page, but a user prefers links that open the item itself. What can the user change?",
    options: ["Nothing — only an administrator can change it", "The Item Link Action in My Account ▸ Settings ▸ General", "The item's nickname", "The notification report format"],
    answer: 1,
    explain: "The administrator sets the default link action, and each user can override it with the Item Link Action setting." },
  { id: "bu-q-collab-006", domain: "bu-collab", guide: "bu-personalize",
    q: "Which two statements about favorites are true? (Choose two.)",
    options: ["Favorites are private to the user", "The All tab on My Favorites cannot be removed", "Deleting a favorite deletes the original item", "Favorites can be shared with a team"],
    answer: [0, 1],
    explain: "Favorites are personal bookmarks; the All tab always exists. Remove Favorite never deletes the item (Delete is not even offered on that page). To share a list, use a collection." },
  { id: "bu-q-collab-007", domain: "bu-collab", guide: "bu-personalize",
    q: "Where in Classic View does a visually impaired user turn on keyboard-driven navigation for use with a screen reader?",
    options: ["Help ▸ For This Page", "My Account ▸ Settings ▸ General ▸ Enhanced Keyboard Accessibility Mode", "Personal ▸ Notification", "Tools ▸ Search"],
    answer: 1,
    explain: "Enhanced Keyboard Accessibility Mode is a personal setting on the General tab supporting keyboard-only use and screen readers." },
  { id: "bu-q-collab-008", domain: "bu-collab", guide: "bu-email",
    q: "Outlook emails about one issue were filed in Content Server. How can a user list the related replies and forwards?",
    options: ["Show Conversation on one of the emails", "Make Generation", "Search with the Help slice", "Open the Recycle Bin"],
    answer: 0,
    explain: "Content Server stores the Outlook conversation ID; Show Conversation lists the other filed messages from the same thread." },

  // ---------------------------------------------------------------- bu-reminders (10)
  { id: "bu-q-reminders-001", domain: "bu-reminders", guide: "bu-reminders",
    q: "What is the main purpose of a reminder in Content Server?",
    options: ["To report events that already happened in a folder", "To schedule a follow-up action on an item and track its status until completed", "To lock a document against edits", "To route a document through approval steps"],
    answer: 1,
    explain: "Reminders schedule future action (renewals, reviews) on a specific item with activation, escalation and status. Notifications report past events; workflows route steps." },
  { id: "bu-q-reminders-002", domain: "bu-reminders", guide: "bu-reminders",
    q: "Which reminder statuses does a user move through when working a reminder?",
    options: ["New, Open, Closed", "Active, In Progress, Completed", "Draft, Reviewed, Approved", "OK, Late, Suspended"],
    answer: 1,
    explain: "After activation a reminder is Active; assignees set In Progress while working and Completed when done. OK/Late/Suspended are workflow statuses." },
  { id: "bu-q-reminders-003", domain: "bu-reminders", guide: "bu-reminders",
    q: "In a reminder, what does the Activation setting control?",
    options: ["Who may edit the reminder", "How long before the due date the reminder becomes active and emails the assignees", "When the item is deleted", "The priority"],
    answer: 1,
    explain: "Activation is relative to the due date — e.g. one month before — optionally only on business days. Escalation alerts additional people closer to the due date if it is not completed." },
  { id: "bu-q-reminders-004", domain: "bu-reminders", guide: "bu-reminders",
    q: "Creating a reminder fails when a group is chosen as assignee. What is a likely cause?",
    options: ["Groups can never be assignees", "At least one member of the group has no email address in their profile", "The item is reserved", "The reminder has a High priority"],
    answer: 1,
    explain: "Every user involved — including all members of an assigned group — needs an email address, because reminders are delivered by email." },
  { id: "bu-q-reminders-005", domain: "bu-reminders", guide: "bu-reminders",
    q: "In Smart View, how do you add a reminder to a document?",
    options: ["Properties ▸ Versions ▸ Add Reminder", "More actions ▸ Add Reminder on the inline action bar", "Tools ▸ Reminders", "Drag the document onto the Reminders tile"],
    answer: 1,
    explain: "Add Reminder is on the inline action bar's More actions menu (for documents, folders and workspaces where reminders are allowed). The dialog can be maximised to show all fields." },
  { id: "bu-q-reminders-006", domain: "bu-reminders", guide: "bu-reminders",
    q: "Which two settings can be configured when designating reminder substitutes? (Choose two.)",
    options: ["A period of validity during which substitutes handle your reminders", "A different period for each substitute", "Duplicate to me, so you still receive copies", "Automatic deletion of your reminders"],
    answer: [0, 2],
    explain: "One validity period applies to all substitutes; for each substitute you can limit reminder types and choose Duplicate to me." },
  { id: "bu-q-reminders-007", domain: "bu-reminders", guide: "bu-workflows",
    q: "A user going on leave wants new workflow steps to also appear for a colleague. Which two statements about the workflow proxy are true? (Choose two.)",
    options: ["It is set in My Account ▸ Settings ▸ Workflow", "The proxy can in turn pass the steps to their own proxy", "The proxy must be a user, not a group", "It also covers task-list tasks"],
    answer: [0, 2],
    explain: "The proxy is set on the Workflow settings tab, must be a single user and works one level deep. Task-list assignments are not forwarded." },
  { id: "bu-q-reminders-008", domain: "bu-reminders", guide: "bu-notifications-pulse",
    q: "A workflow manager wants an email when any workflow they manage becomes late. What should they configure?",
    options: ["A reminder on the workflow map", "A general notification interest “A workflow I manage is late” on a report with email delivery", "A prospector", "A Pulse follow on the initiator"],
    answer: 1,
    explain: "Workflow events are general (system-wide) notification interests; link them to a notification report with email delivery enabled." },
  { id: "bu-q-reminders-009", domain: "bu-reminders", guide: "bu-notifications-pulse",
    q: "Which two statements about notification interests are true? (Choose two.)",
    options: ["Specific interests are set on an item with Set Notification", "General interests apply system-wide", "Each user may have unlimited notification reports", "Group default notifications override a user's own settings"],
    answer: [0, 1],
    explain: "Specific interests attach to an item; general ones cover the whole system. Users have three reports, and group defaults only seed new users and stop applying once users set their own." },
  { id: "bu-q-reminders-010", domain: "bu-reminders", guide: "bu-reminders",
    q: "On Personal ▸ Reminders, a user marked a reminder Completed and it disappeared from the list. Why?",
    options: ["Completed reminders are deleted", "The default status filter shows Active and In Progress only", "The reminder was escalated", "The substitute took it over"],
    answer: 1,
    explain: "Completed reminders are hidden by the default filter; tick Completed and Show to see them again." },

  // ---------------------------------------------------------------- bu-wikis (9)
  { id: "bu-q-wikis-001", domain: "bu-wikis", guide: "bu-wikis",
    q: "A Smart View wiki has three pages and no main page set. Which page opens when a user opens the wiki?",
    options: ["The first page created", "The Overview page listing the pages", "The most recently edited page", "An error page"],
    answer: 1,
    explain: "Smart View opens the main page if set, the single page if there is only one, and otherwise the automatically generated Overview page." },
  { id: "bu-q-wikis-002", domain: "bu-wikis", guide: "bu-wikis",
    q: "What is the Classic View equivalent of Smart View's main page in a wiki?",
    options: ["The orphaned page", "The index page", "The sidebar", "The overview page"],
    answer: 1,
    explain: "Classic View requires an index page; Smart View calls the same concept the main page, set with Set as Main page." },
  { id: "bu-q-wikis-003", domain: "bu-wikis", guide: "bu-wikis",
    q: "Which two statements about wiki sidebars are true? (Choose two.)",
    options: ["A sidebar is displayed beside the overview and every page of the wiki", "Each wiki can have only one sidebar", "Sidebars can be moved up or down to change their order", "Sidebars are separate wikis"],
    answer: [0, 2],
    explain: "Sidebars hold content such as key facts or links shown next to all pages; a wiki can have several, and they can be edited, deleted and reordered." },
  { id: "bu-q-wikis-004", domain: "bu-wikis", guide: "bu-wikis",
    q: "A wiki page was accidentally overwritten. Where can an editor find the earlier text in Smart View?",
    options: ["Page history", "The Recycle Bin", "Recently Accessed", "The sidebar"],
    answer: 0,
    explain: "Each save creates a version; Page history (Version History in Classic) lists them so the earlier text can be viewed and restored." },
  { id: "bu-q-wikis-005", domain: "bu-wikis", guide: "bu-wikis",
    q: "A wiki page links to a confidential document. What happens when a reader without permission on that document selects the link?",
    options: ["The document opens because the wiki grants access", "They get an error; links do not override the target's permissions", "The link is converted to a copy", "The wiki owner is notified and access is granted"],
    answer: 1,
    explain: "Wiki links respect the target's permissions. Readers need their own access to the linked item." },
  { id: "bu-q-wikis-006", domain: "bu-wikis", guide: "bu-collections",
    q: "A team must gather 40 existing contracts from many folders for an audit and apply an Audit category to all of them. Which feature fits best?",
    options: ["A wiki", "A collection", "Favorites", "A compound document"],
    answer: 1,
    explain: "A collection gathers references to items wherever they live and supports bulk actions such as Apply Categories. A wiki is for writing new interlinked pages." },
  { id: "bu-q-wikis-007", domain: "bu-wikis", guide: "bu-collections",
    q: "Which two statements about collections are true? (Choose two.)",
    options: ["Permissions on a collection do not change the permissions of its items", "Remove Items from Collection deletes the originals", "A collection can be shared with other users", "Items must be moved into the collection's folder first"],
    answer: [0, 2],
    explain: "Collections use their own None/Read/Write/Administer permissions while items keep their ACLs; they are shared items stored in folders. Remove only takes items off the list, and items stay where they are." },
  { id: "bu-q-wikis-008", domain: "bu-wikis", guide: "bu-wikis",
    q: "A support team wants to write and maintain interlinked how-to pages that everyone in the team can edit and that keep a history. What should they use?",
    options: ["A collection", "A wiki", "A search form", "A virtual folder"],
    answer: 1,
    explain: "Wikis are for authoring linked web pages collaboratively with version history, permissions and search." },
  { id: "bu-q-wikis-009", domain: "bu-wikis", guide: "bu-collections",
    q: "In Classic View, which multi-select button adds selected items to a new or existing collection?",
    options: ["Collect", "Zip & Download", "Email Link", "Make Shortcut"],
    answer: 0,
    explain: "Collect opens the Items to Collect page where you choose Create New, Recently Used, Favorites or browse to a collection." },

  // ---------------------------------------------------------------- bu-workflows (20)
  { id: "bu-q-workflows-001", domain: "bu-workflows", guide: "bu-workflows",
    q: "What happens when a workflow map is initiated?",
    options: ["The map itself starts moving between users", "A workflow instance is created with a copy of the map's steps and its own work package", "The map is locked until the workflow completes", "A compound document is created"],
    answer: 1,
    explain: "Initiation copies the map's steps and work package into a new instance, so the same map can run many times in parallel." },
  { id: "bu-q-workflows-002", domain: "bu-workflows", guide: "bu-workflows",
    q: "Which permission does a user need on a workflow map to initiate it?",
    options: ["See Contents", "Edit Permissions", "Delete", "Reserve"],
    answer: 0,
    explain: "Users with See Contents on the map can initiate it. Creating or editing maps is a separate privilege." },
  { id: "bu-q-workflows-003", domain: "bu-workflows", guide: "bu-workflows",
    q: "Who defines which users can manage instances of a workflow and what each manager may do?",
    options: ["The initiator", "The workflow map author (designer)", "Each performer", "The system automatically gives all participants full rights"],
    answer: 1,
    explain: "Managers and their permissions are set in the map, so every instance of that map has the same management set-up." },
  { id: "bu-q-workflows-004", domain: "bu-workflows", guide: "bu-workflows",
    q: "While processing a step, a performer adds a document with Copy item from Content Server and edits it. What happens to the original document?",
    options: ["It receives the edits", "Nothing — the attachment is a separate copy", "It is reserved until the workflow ends", "It is deleted"],
    answer: 1,
    explain: "Copy item from Content Server attaches a copy; changes to the attachment and the original are independent." },
  { id: "bu-q-workflows-005", domain: "bu-workflows", guide: "bu-workflows",
    q: "A step is assigned to the Purchasing group. What must the first member who opens it do?",
    options: ["Delegate it back to the group", "Accept the assignment, which removes it from the other members' lists", "Wait until every member has opened it", "Ask the manager to reassign it"],
    answer: 1,
    explain: "Group steps must be accepted; once accepted by one member, the step leaves the others' assignments." },
  { id: "bu-q-workflows-006", domain: "bu-workflows", guide: "bu-workflows",
    q: "Which two parts of a step's work package can be required before the performer completes the step? (Choose two.)",
    options: ["Attributes", "Comments", "The Map View", "The Audit trail"],
    answer: [0, 1],
    explain: "Map authors can require attribute values and comments. Map View and Audit are monitoring pages for managers." },
  { id: "bu-q-workflows-007", domain: "bu-workflows", guide: "bu-workflows",
    q: "Kurt cannot process an approval step before his holiday. The map allows delegation. What should Kurt do?",
    options: ["Set a reminder substitute", "Use Delegate to on the step and choose a colleague", "Stop the workflow", "Archive the step"],
    answer: 1,
    explain: "Delegation hands one step to another user or group when the map permits it. Reminder substitutes only cover reminders; stopping ends the whole workflow." },
  { id: "bu-q-workflows-008", domain: "bu-workflows", guide: "bu-workflows",
    q: "Which two statements about email-enabled workflow steps are true? (Choose two.)",
    options: ["The performer can complete the step from the email using disposition buttons", "Workflow attributes can always be updated by email", "The step also appears in the performer's Assignments", "Email-enabled steps bypass permissions"],
    answer: [0, 2],
    explain: "Email steps carry action buttons and still appear in Assignments. Updating attributes or authenticating by email is not supported, so such steps must be completed in Content Server." },
  { id: "bu-q-workflows-009", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "In Smart View, how can a user start a review workflow on four documents at once?",
    options: ["Select the four documents and choose Start workflow, then pick the map", "Open each document's Versions tab", "Create a compound document first", "Workflows can only be started from Classic View"],
    answer: 0,
    explain: "Selecting documents and choosing Start workflow lets you pick a map; the selected documents become attachments." },
  { id: "bu-q-workflows-010", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "A workflow map was designed for Classic View. What happens when a user starts it from Smart View?",
    options: ["It cannot be started", "The Classic initiate page opens; afterwards the user returns to Smart View", "It is converted to a Smart View workflow permanently", "It starts without attachments"],
    answer: 1,
    explain: "Classic-designed maps open their Classic pages even when launched from Smart View; maps with Smart View steps show Smart View forms." },
  { id: "bu-q-workflows-011", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "A manager pauses a workflow while waiting for a supplier's information and intends to continue it later. Which action?",
    options: ["Stop", "Suspend", "Archive", "Delete"],
    answer: 1,
    explain: "Suspend pauses an instance so it can be resumed. A stopped workflow cannot be restarted." },
  { id: "bu-q-workflows-012", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "Which two actions are available to a manager for a completed workflow? (Choose two.)",
    options: ["Archive", "Resume", "Delete", "Reassign a step"],
    answer: [0, 2],
    explain: "Completed or stopped workflows can be archived or deleted. Resume applies to suspended workflows, and completed steps cannot be reassigned." },
  { id: "bu-q-workflows-013", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "In a workflow's Map View, what does a green border around a step indicate?",
    options: ["The step was completed", "The step is currently active", "The step was skipped", "The step is late"],
    answer: 1,
    explain: "Green marks the active step; blue marks steps already processed after which the workflow moved on." },
  { id: "bu-q-workflows-014", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "The performer of a pending step has left the company. Who can move the step to someone else, and how?",
    options: ["Any user, by delegating it", "A workflow manager, using Reassign To on the step from the Step List or Map View", "The initiator, by restarting the map", "Nobody — the workflow must be stopped"],
    answer: 1,
    explain: "Managers with sufficient rights reassign steps that are not yet completed to another user or group." },
  { id: "bu-q-workflows-015", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "Where does an initiator see the status of workflows they started?",
    options: ["Personal ▸ Workflows (Statuses tab)", "Personal ▸ Reserved Items", "Tools ▸ Recycle Bin", "The Categories Volume"],
    answer: 0,
    explain: "My Workflows lists instances you initiated or manage, with status, and its Assignments tab lists your steps." },
  { id: "bu-q-workflows-016", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "An auditor asks who approved a purchase order step and when. Which part of the workflow instance answers this?",
    options: ["The Audit trail (and step details)", "The Attachments page", "The workflow map's Specific tab", "The initiator's Personal Workspace"],
    answer: 0,
    explain: "The audit lists every event with performer, action and time; step details in the Step List or Map View show disposition and comments." },
  { id: "bu-q-workflows-017", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "What is the effect of stopping a workflow?",
    options: ["It is paused and can be resumed", "It ends and cannot be restarted", "It is archived automatically", "It restarts from the first step"],
    answer: 1,
    explain: "Stop ends the instance permanently. Use Suspend if you might want to continue." },
  { id: "bu-q-workflows-018", domain: "bu-workflows", guide: "bu-workflows-manage",
    q: "In Classic View, how do you give a new workflow instance a meaningful name before starting it?",
    options: ["Rename the workflow map", "Change Initiate As on the initiate page", "Add a nickname to the map", "Set a category on the map"],
    answer: 1,
    explain: "Initiate As names the instance (e.g. “PO 4711 laptops”), which then appears in assignments and status lists." },
  { id: "bu-q-workflows-019", domain: "bu-workflows", guide: "bu-business-workspaces",
    q: "A team member in a customer business workspace wants to start an approval for two contracts filed in the workspace. What should they do?",
    options: ["Copy the contracts to their Personal Workspace first", "Select the documents in the workspace and use Start workflow, choosing from the maps offered", "Ask an administrator to initiate it", "Email the contracts to the workflow map"],
    answer: 1,
    explain: "Workflows can be started on documents inside a business workspace in Smart View; which maps are offered depends on the workspace configuration." },
  { id: "bu-q-workflows-020", domain: "bu-workflows", guide: "bu-workflows",
    q: "Which role in a workflow chooses dispositions such as Approve or Reject?",
    options: ["The map designer", "The performer of the step", "The system administrator", "The owner group"],
    answer: 1,
    explain: "Performers process steps and choose the disposition buttons the map provides; designers only define which buttons exist." },

  // ---------------------------------------------------------------- bu-viewing (7)
  { id: "bu-q-viewing-001", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "Which two are benefits of Intelligent Viewing? (Choose two.)",
    options: ["Viewing Office files, PDFs and CAD drawings in the browser without the native application", "Automatically granting access to restricted documents", "Comparing two versions of a document with differences highlighted", "Replacing the need for permissions"],
    answer: [0, 2],
    explain: "Intelligent Viewing is a universal browser viewer with review tools such as markups, comments and compare. It never bypasses permissions." },
  { id: "bu-q-viewing-002", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "A reviewer adds arrows and text boxes to a contract in Intelligent Viewing and saves. What happens to the contract file?",
    options: ["A new major version is created with the arrows embedded", "The file is unchanged; markups are stored as a separate layer", "The file is converted to PDF", "The file is reserved to the reviewer"],
    answer: 1,
    explain: "Markups live in a layer associated with the version; the original file is not modified." },
  { id: "bu-q-viewing-003", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "A user draws redaction boxes over salary figures and then emails the original document to an external party. What is the risk?",
    options: ["None — redactions are always burned into the file", "The salary figures are still in the original file and are exposed", "The email will be blocked automatically", "The recipient sees blank pages"],
    answer: 1,
    explain: "Unpublished redactions are only an overlay. Only a published output with the redactions burned in removes the content." },
  { id: "bu-q-viewing-004", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "What does burning in markups and redactions do?",
    options: ["Deletes all markups", "Flattens them into a new output file (typically PDF) so they cannot be removed from that copy", "Prints the document", "Locks the original version against deletion"],
    answer: 1,
    explain: "Publishing with burn-in creates a new output where markups are part of the page and redacted content is gone; the source keeps its editable layer." },
  { id: "bu-q-viewing-005", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "Two reviewers disagree about a highlighted clause. How can they discuss it in Intelligent Viewing so the discussion stays with the clause?",
    options: ["Create a Pulse status update", "Add a comment to the markup and reply to it, forming a thread", "Email each other a link", "Add a reminder"],
    answer: 1,
    explain: "Comments and replies attach to the markup itself, keeping the discussion pinned to the exact spot, with authors and times recorded." },
  { id: "bu-q-viewing-006", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "Which two ways of redacting does Intelligent Viewing support? (Choose two.)",
    options: ["Selecting an area on the page", "Searching for text or patterns and redacting the matches", "Changing the document's permissions to None", "Deleting the version"],
    answer: [0, 1],
    explain: "Redaction can be manual (area) or search-based (text and pattern matching). Permissions and version deletion are unrelated." },
  { id: "bu-q-viewing-007", domain: "bu-viewing", guide: "bu-intelligent-viewing",
    q: "What is the safest way to give an external party a redacted document while keeping the full original internally?",
    options: ["Share the original with redaction markups", "Publish a burned-in PDF as a separate item or rendition with its own permissions and share only that", "Rename the original", "Remove Public Access from the folder"],
    answer: 1,
    explain: "Keep the original protected and distribute only the burned-in publication, controlled by its own permissions." },

  // ---------------------------------------------------------------- bu-perspectives (7)
  { id: "bu-q-perspectives-001", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "Which three are perspective types in Smart View? (Choose three.)",
    options: ["Landing page", "Container", "Workspace", "Recycle Bin", "Notification"],
    answer: [0, 1, 2],
    explain: "Perspectives define the Home (landing page), container pages (folders and similar) and business workspace pages." },
  { id: "bu-q-perspectives-002", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "What distinguishes a local perspective from a global one?",
    options: ["A local perspective belongs to one container (optionally cascading to sub-containers); a global one is applied by rules across the system", "Local perspectives work only in Classic View", "Global perspectives cannot contain widgets", "There is no difference"],
    answer: 0,
    explain: "Global perspectives are stored centrally and matched by rules in order; local perspectives are attached to a specific container." },
  { id: "bu-q-perspectives-003", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "Several global perspectives have rules that match the same user. Which one is shown?",
    options: ["The newest", "The first one in order whose rule evaluates to true", "A random one", "All of them, stacked"],
    answer: 1,
    explain: "Rules are evaluated in order and the first match wins, which is why administrators manage the order of global perspectives." },
  { id: "bu-q-perspectives-004", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "Which widget lets a department editor put their own welcome text, images and links on a landing page?",
    options: ["Node browsing table", "HTML Tile", "My Assignments", "Recently Accessed"],
    answer: 1,
    explain: "The HTML Tile displays rich content written by the page editor." },
  { id: "bu-q-perspectives-005", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "An Activity Feed widget on a department page stays empty. Which prerequisite is most likely missing?",
    options: ["Pulse is not enabled", "The folder has no nickname", "The users lack Edit Permissions", "Advanced versioning is off"],
    answer: 0,
    explain: "The Activity Feed displays Pulse activity, so Pulse (and the object types that generate updates) must be enabled by an administrator." },
  { id: "bu-q-perspectives-006", domain: "bu-perspectives", guide: "bu-perspectives",
    q: "Which two are required for a user to edit a global perspective? (Choose two.)",
    options: ["The Perspective Manager usage privilege granted by an administrator", "Sufficient permission on the perspective item", "Membership of the DefaultGroup", "eDiscovery rights"],
    answer: [0, 1],
    explain: "Editing perspectives combines a usage privilege with permission on what is changed — the perspective item for global, the container for local." },
  { id: "bu-q-perspectives-007", domain: "bu-perspectives", guide: "bu-notifications-pulse",
    q: "Which two statements about Activity Feed filtering are true? (Choose two.)",
    options: ["Readers can narrow the feed to types of activity such as content or status updates", "Filters let readers see posts about items they have no permission on", "A feed can be scoped to a container and everything below it", "Filters delete posts from the feed permanently"],
    answer: [0, 2],
    explain: "Feeds can be scoped (system, container, single item) and filtered by activity type. Permissions always apply and filtering does not delete anything." },
];
