'use strict';
// Question bank, business workspaces part A: course 2-0108 chapters 1, 2, 3
// and 16 (introduction, using workspaces, installation and rights, accessing,
// using and editing workspaces). All questions are original.
// Format: curriculum/CONTENT.md.

module.exports = [
  // ---------------------------------------------------------------- ws-concepts
  { id: 'bw-qa-concepts-001', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'A sales director asks why the company should use business workspaces instead of department folders for customers. Which answer best captures the idea?',
    options: ['Workspaces are only a new icon for folders', 'Workspaces store files more cheaply than folders', 'Each customer gets one container that combines its business data, content, people and tasks, built the same way every time', 'Workspaces replace the need for permissions'],
    answer: 2,
    explain: 'A business workspace fuses business data, content, people and tasks around one business object and is created from rules and templates, so every customer workspace is consistent. Permissions still apply — through roles.' },
  { id: 'bw-qa-concepts-002', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'Which two items belong to the “people” ingredient of a business workspace? (Choose two.)',
    options: ['Team roles with their permissions', 'Category attributes such as the invoice number', 'Participants added to the workspace', 'Task lists and reminders'],
    answer: [0, 2],
    explain: 'People = roles (defined in the template, carrying permissions) and the participants placed in them. Attributes are business data; task lists and reminders are tasks.' },
  { id: 'bw-qa-concepts-003', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'Which statement explains why business data is called the “context” of content?',
    options: ['It is stored in a separate database that users never see', 'It replaces document versions', 'It is only used by the leading application', 'It makes the content relevant, searchable and actionable — documents can be found by invoice number or case ID'],
    answer: 3,
    explain: 'Category attributes on the workspace give documents their business meaning; they feed search, the name, the header and widgets.' },
  { id: 'bw-qa-concepts-004', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'An HR manager wants a place per employee for onboarding documents, promotions and disciplinary records with strict role-based access. A colleague suggests a single shared HR folder. What is the better design?',
    options: ['A discussion per employee', 'A personal workspace for each HR clerk', 'A collection per employee', 'A business workspace type “Employee” with roles in its template'],
    answer: 3,
    explain: 'Employee files are a classic workspace use case: one workspace per employee, consistent structure, roles controlling who sees what.' },
  { id: 'bw-qa-concepts-005', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'In the procurement example, how does a buyer get a 360° view of the purchasing process from a purchase-order workspace?',
    options: ['By running a LiveReport per order', 'By exporting the audit log', 'Through categories and related workspaces that lead to the supplier and contract workspaces', 'By opening every folder in the Enterprise workspace'],
    answer: 2,
    explain: 'Procurement metadata is shown through the workspace’s categories, and related workspace widgets navigate between related business objects.' },
  { id: 'bw-qa-concepts-006', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'Which two statements about tiles and widgets are correct? (Choose two.)',
    options: ['A widget is the UI component that shows information', 'A tile is the box on a Smart View page in which a widget is displayed', 'Tiles are configured on the workspace type’s sidebar settings', 'Widgets only exist in Classic View'],
    answer: [0, 1],
    explain: 'The widget is the component (Team, Metadata, Favorites…); the tile is where it appears on the page. Sidebar widgets are a Classic View concept.' },
  { id: 'bw-qa-concepts-007', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'What decides WHEN a particular perspective is used for a workspace?',
    options: ['Its rules — for example workspace type, template or user group', 'The name pattern', 'The Recently Accessed settings', 'The layout'],
    answer: 0,
    explain: 'Rules decide when a perspective applies; the layout decides what it shows (tabs, widgets, positions).' },
  { id: 'bw-qa-concepts-008', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'What is the difference between an ActiveView override and an ActiveView perspective?',
    options: ['They are two names for the same thing', 'An override applies to workflows only', 'An override changes how a component looks in Classic View; a perspective changes how it looks in Smart View', 'An override is for documents; a perspective is for folders'],
    answer: 2,
    explain: 'ActiveView serves both interfaces: overrides for Classic View, perspectives for Smart View.' },
  { id: 'bw-qa-concepts-009', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'A designer builds pages for “the account managers” as one audience with shared information needs. What does the course call such a group?',
    options: ['A rule', 'A persona', 'A facet', 'A partition'],
    answer: 1,
    explain: 'A persona represents a group of users with a common role; perspectives are designed per persona.' },
  { id: 'bw-qa-concepts-010', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'Which object publishes metadata changes of a workspace to its activity feed?',
    options: ['The activity manager', 'The Perspective Manager', 'The classification tree', 'The Saved Queries volume'],
    answer: 0,
    explain: 'An activity manager object tracks changes (e.g. attribute values) and sends them to the activity feed in the header (Pulse in Classic View).' },
  { id: 'bw-qa-concepts-011', domain: 'ws-concepts', guide: 'bw-terminology',
    q: 'Which two settings are held by the workspace type rather than the workspace template? (Choose two.)',
    options: ['The folder structure', 'The location under the root folder where workspaces are stored', 'The team roles and their permissions', 'The name pattern'],
    answer: [1, 3],
    explain: 'The type controls naming, location, icons and sidebar widgets; the template holds folders, documents, categories, classification and roles.' },

  // ---------------------------------------------------------------- ba-bw-fundamentals
  { id: 'bw-qa-fund-001', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which module must be enabled together with Business Workspaces because it supplies reusable workspace templates?',
    options: ['eDiscovery', 'Archive Center', 'Template Workspaces', 'Physical Objects'],
    answer: 2,
    explain: 'Template Workspaces (with Document Templates, Case Management and other components) is the underlying module; both are enabled together.' },
  { id: 'bw-qa-fund-002', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which three are dependencies of Business Workspaces named in the course? (Choose three.)',
    options: ['Intelligent Viewing', 'Archive Center', 'Classifications', 'Records Management', 'Document Templates'],
    answer: [2, 3, 4],
    explain: 'The list is Classifications, Records Management, Case Management, Document Templates and Template Workspaces.' },
  { id: 'bw-qa-fund-003', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'An administrator enables Business Workspaces on a test server to “have a look” and plans to switch it off afterwards. What should you tell them?',
    options: ['That is fine; it can be disabled on the same page', 'Enabling cannot be undone, needs a license for Business Workspaces and Template Workspaces, and requires a restart', 'Only Template Workspaces can be disabled', 'It disables itself after 30 days'],
    answer: 1,
    explain: 'Once enabled, the modules cannot be disabled; licensing and a Content Server restart are part of enabling.' },
  { id: 'bw-qa-fund-004', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'What role does the Classifications module play for business workspaces?',
    options: ['It stores the metadata values', 'It schedules reminders', 'It renders the Smart View header', 'It controls what kind of business workspace can be created in which folder'],
    answer: 3,
    explain: 'A template is offered in a folder when the folder and the template share a classification.' },
  { id: 'bw-qa-fund-005', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which are the three major areas of business workspace configuration?',
    options: ['Design, test, transport', 'Users, groups, roles', 'Install, patch, upgrade', 'Identify business processes, refine metadata and events, build workspaces'],
    answer: 3,
    explain: 'The course groups configuration into identifying business processes (root folder, classification), refining metadata and events (category, columns, activity manager) and building workspaces (type, template, roles, perspective, search).' },
  { id: 'bw-qa-fund-006', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which two configuration steps belong to the “refine metadata and events” area? (Choose two.)',
    options: ['Create the workspace template', 'Create the category', 'Create the root folder', 'Create an activity manager object'],
    answer: [1, 3],
    explain: 'Category, optional custom columns and optional activity manager refine metadata and events. The root folder belongs to identifying processes; the template to building workspaces.' },
  { id: 'bw-qa-fund-007', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'What does Extended ECM Platform add on top of business workspaces in Content Server?',
    options: ['Integration with leading business applications, so workspaces get their context from ERP, CRM or HR data', 'A second database for documents', 'A replacement for Smart View', 'Records Management'],
    answer: 0,
    explain: 'Extended ECM Platform connects content with context from business applications (CRM, ERP, HRMS, FMS) — content, context and value.' },
  { id: 'bw-qa-fund-008', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'In Content Server 22.1, why are Business Workspaces and Template Workspaces disabled on a new installation even though they ship with the core product?',
    options: ['Because they are still beta', 'Because they conflict with Smart View', 'Because they require a separate database', 'Because not every customer is licensed for them'],
    answer: 3,
    explain: 'The modules are part of core and patched with it, but stay disabled until a system administrator enables them for licensed customers.' },
  { id: 'bw-qa-fund-009', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which statement about configuring for Smart View versus Classic View is correct?',
    options: ['Classic View needs no configuration at all', 'Smart View does not use categories', 'They need two completely separate configurations', 'Most steps are shared; the differences are mainly in the workspace layout'],
    answer: 3,
    explain: 'Categories, classifications, folders, types, templates, roles and privileges serve both; perspectives (Smart View) and sidebar widgets (Classic View) differ.' },
  { id: 'bw-qa-fund-010', domain: 'ba-bw-fundamentals', guide: 'bw-admin-page-volume',
    q: 'Which link on the Business Workspaces administration page imports workspace types, business object types and unique names?',
    options: ['Set up Outlook Add-in', 'Configure Business Workspaces', 'Import Configuration', 'Migration Administration'],
    answer: 2,
    explain: 'Import Configuration handles those imports; Migration Administration moves binders and cases into workspaces.' },
  { id: 'bw-qa-fund-011', domain: 'ba-bw-fundamentals', guide: 'bw-admin-page-volume',
    q: 'An organisation still has binders and cases from older Template Workspaces solutions. Where are they converted into business workspaces?',
    options: ['Migration Administration on the Business Workspaces admin page', 'The Saved Queries volume', 'Perspective Manager', 'Workspace Types ▸ Advanced'],
    answer: 0,
    explain: 'Migration Administration manages the migration of binders and cases to business workspaces.' },
  { id: 'bw-qa-fund-012', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Who usually configures business workspaces in the model the course follows?',
    options: ['A group of business administrators (such as Business Administrators) with specific permissions and privileges', 'Only the built-in Admin account', 'OpenText Support', 'Each end user for their own workspaces'],
    answer: 0,
    explain: 'The course, following the Configuration Guide, delegates workspace administration to a group; the simpler alternative is to do everything with an administrator account.' },
  { id: 'bw-qa-fund-013', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which two components are bundled with Template Workspaces? (Choose two.)',
    options: ['Transport Warehouse', 'Intelligent Viewing', 'Partner Database', 'Calendar Attribute'],
    answer: [2, 3],
    explain: 'Template Workspaces includes Barcode, Calendar Attribute, Case Management components, Partner Database, Document Templates and Interview.' },
  { id: 'bw-qa-fund-014', domain: 'ba-bw-fundamentals', guide: 'bw-dependencies-modules',
    q: 'Which configuration step requires system administrator access even in a delegated setup?',
    options: ['Creating variables for replacement tags', 'Creating workspace types', 'Allowing workspace templates to be created for the Business Workspace subtype (848)', 'Creating roles and teams'],
    answer: 2,
    explain: 'Types, roles, variables and saved queries need the Business Administration – Business Workspaces usage privilege; allowing templates for subtype 848 needs a system administrator.' },

  // ---------------------------------------------------------------- ba-bw-infra
  { id: 'bw-qa-infra-001', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Where does a business administrator find the Business Workspaces volume?',
    options: ['Global Menu Bar ▸ Enterprise ▸ Business Workspaces', 'Personal ▸ Business Workspaces', 'Tools ▸ Business Workspaces', 'Only in the admin pages'],
    answer: 0,
    explain: 'The volume is linked from the Enterprise menu; the admin page is a separate place for system-level switches.' },
  { id: 'bw-qa-infra-002', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Which three items are found in the Business Workspaces volume? (Choose three.)',
    options: ['Saved Queries Volume', 'Workspace Types', 'Document Templates', 'Enable Business Workspaces', 'Variables for Replacement Tags'],
    answer: [0, 1, 4],
    explain: 'The volume holds Categories, Classifications, Facets, (Outlook Add-in Configuration), Perspectives, Saved Queries Volume, Variables for Replacement Tags and Workspace Types. Templates are in the Document Templates volume; enabling is on the admin page.' },
  { id: 'bw-qa-infra-003', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'What is the Saved Queries Volume used for?',
    options: ['Holding workspace templates', 'Storing deleted workspaces', 'Storing simple, predefined searches that help users find business workspaces quickly', 'Keeping the audit trail of workspace changes'],
    answer: 2,
    explain: 'It holds predefined saved queries; working with it needs the Business Administration – Business Workspaces usage privilege.' },
  { id: 'bw-qa-infra-004', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'A designer wants access to parts of each new workspace to be restricted to generated groups based on a variable. Where are such variables defined?',
    options: ['The Recycle Bin settings', 'Variables for Replacement Tags in the Business Workspaces volume', 'Configure Smart View', 'The Facets volume'],
    answer: 1,
    explain: 'Variables for Replacement Tags define variables used for group replacement to restrict access to the workspace or portions of it.' },
  { id: 'bw-qa-infra-005', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Users must save Outlook emails only into the Email folder of a customer workspace, not anywhere they like. What do you configure?',
    options: ['Outlook Add-in Configuration in the Business Workspaces volume', 'An email-enabled folder in the Personal Workspace', 'A search form', 'The workspace type name pattern'],
    answer: 0,
    explain: 'By default the add-in lets users browse or search and pick a folder; the configuration can force a specific folder or Email folder.' },
  { id: 'bw-qa-infra-006', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Where is the Outlook add-in manifest file obtained?',
    options: ['The Saved Queries Volume', 'The Facets volume', 'Configure Smart View', 'Set up Outlook Add-in on the Business Workspaces admin page'],
    answer: 3,
    explain: 'Set up Outlook Add-in downloads the manifest and configures tracing; the filing rules are in Outlook Add-in Configuration.' },
  { id: 'bw-qa-infra-007', domain: 'ba-bw-infra', guide: 'bw-dependencies-modules',
    q: 'What is the purpose of the root folder for a workspace type?',
    options: ['It stores the perspectives', 'It is the Recycle Bin for workspaces', 'It is the folder where workspaces of that type are stored; sub-folders may be generated from metadata', 'It holds the templates'],
    answer: 2,
    explain: 'One folder serves as the root for workspaces of one type; it shares the template’s classification.' },
  { id: 'bw-qa-infra-008', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'To make the workspace link reference field (ECMWkspLinkRefTypeID) query-able, where does a system administrator go?',
    options: ['Pulse Administration', 'Search Administration ▸ System Object Volume ▸ Enterprise Data Source folder', 'Configure Smart View', 'Object Privileges'],
    answer: 1,
    explain: 'Search settings for the field live in the Enterprise data source in the System Object Volume.' },
  { id: 'bw-qa-infra-009', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Which two statements about the Perspectives item of the Business Workspaces volume are true? (Choose two.)',
    options: ['It stores layouts designed with the Perspective Manager', 'For workspaces the Perspective Manager offers a reduced, workspace-focused set of options', 'It stores workspace templates', 'Perspectives created there apply only to Classic View'],
    answer: [0, 1],
    explain: 'Perspectives are Smart View layouts made with Perspective Manager, which uses a reduced feature set for workspace perspectives.' },
  // ---------------------------------------------------------------- ba-admin-roles
  { id: 'bw-qa-admin-001', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'The workspace administrator group must be able to create, change and delete configuration items in the Categories volume but must not change who has access. Which permission set fits?',
    options: ['Modify only', 'Full Control including Edit Permissions', 'Every permission up to and including Delete, but not Edit Permissions', 'See and See Contents only'],
    answer: 2,
    explain: 'The course grants all permissions up to Delete — leaving out Edit Permissions — on This Item & Sub-Items.' },
  { id: 'bw-qa-admin-002', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Which two volumes does the workspace administrator group need Delete-level permissions on? (Choose two.)',
    options: ['Document Templates volume', 'Recycle Bin', 'Saved Queries volume', 'Personal Workspace of each user'],
    answer: [0, 2],
    explain: 'The list: root location in the Enterprise workspace, Business Workspaces volume, Categories, Classifications, Facets, Outlook Add-in configuration, Saved Queries and Document Templates volumes.' },
  { id: 'bw-qa-admin-003', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Which object privilege is NOT needed by the business workspace administrator group?',
    options: ['Appearance', 'Category', 'Classification Tree', 'ActiveView'],
    answer: 0,
    explain: 'Needed: Category, Category Folder, Classification Tree, Classification, Custom View, Facet Tree, Facet, Facet Folder, ActiveView, LiveReports (WebReports and Activity Manager when used). Appearance is not on the list.' },
  { id: 'bw-qa-admin-004', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'An administrator adds the Business Administrators group to the Facet object privilege, but nothing changes for anyone else. Why?',
    options: ['The privilege was unrestricted, so everyone could already create facets', 'Object privileges need a restart', 'Facets cannot be restricted', 'The group must be added twice'],
    answer: 0,
    explain: 'An unrestricted privilege belongs to everyone. Only after clicking Restrict does the list of users and groups limit who has it.' },
  { id: 'bw-qa-admin-005', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'A key user gets “not allowed” when moving a workspace to another folder, although she has Delete on the workspace and Add Items on the target. What is missing?',
    options: ['The ActiveView – Perspectives Tab usage privilege', 'The Business Workspaces – Move Business Workspaces usage privilege', 'System Administration rights', 'The Category object privilege'],
    answer: 1,
    explain: 'Only users with the Move Business Workspaces usage privilege can move a workspace, in addition to the usual permissions.' },
  { id: 'bw-qa-admin-006', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'What does the usage privilege “Business Workspaces – Edit attributes relevant for group mapping” control?',
    options: ['Who may create categories', 'Who may map users to departments', 'Who may rename groups in OTDS', 'Who may edit the attributes that decide which generated groups get access to a workspace (group replacement)'],
    answer: 3,
    explain: 'When group replacement uses attribute values, changing those values changes access; this privilege restricts who may edit them.' },
  { id: 'bw-qa-admin-007', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Attributes used in a workspace’s reference number have changed and the reference must be rebuilt. Which usage privilege allows a user to do that?',
    options: ['Perspectives Tab', 'Move Business Workspaces', 'Regenerate Reference', 'Warehouse Manager'],
    answer: 2,
    explain: 'Business Workspaces – Regenerate Reference lets a user generate a new reference number.' },
  { id: 'bw-qa-admin-008', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'When does the workspace administrator group need Warehouse Administration – Warehouse Manager?',
    options: ['To open the Business Workspaces volume', 'To create classifications', 'To edit perspectives', 'Only if it will move configuration to another Content Server instance with Transport'],
    answer: 3,
    explain: 'The Transport Warehouse privilege is optional — needed only when the group transports objects between instances.' },
  { id: 'bw-qa-admin-009', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Which two usage privileges relate to designing Smart View layouts and to configuring workspace types? (Choose two.)',
    options: ['Business Administration – Business Workspaces', 'Business Workspaces – Regenerate Reference', 'Warehouse Administration – Warehouse Manager', 'ActiveView – Perspectives Tab'],
    answer: [0, 3],
    explain: 'Perspectives Tab opens the Perspective Manager; Business Administration – Business Workspaces covers workspace types, roles and teams, saved queries, variables and the Outlook add-in.' },
  { id: 'bw-qa-admin-010', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Where do you add a group to the Category object privilege?',
    options: ['Configure Smart View', 'Business Workspaces ▸ Workspace Types', 'Categories volume ▸ Permissions', 'Content Server Administration ▸ Core System – Feature Configuration ▸ Object Privileges ▸ Edit Restrictions'],
    answer: 3,
    explain: 'Object privileges are on the Object Privileges admin page; Edit Restrictions ▸ search the group ▸ Add to group ▸ Submit.' },
  { id: 'bw-qa-admin-011', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Creating categories for workspaces needs which combination?',
    options: ['Warehouse Manager only', 'Business Administration – Data Policies usage privilege and the Category object privilege', 'Perspectives Tab and ActiveView', 'Move Business Workspaces and Regenerate Reference'],
    answer: 1,
    explain: 'The course pairs the Data Policies usage privilege with the Category object privilege (plus permissions on the Categories volume).' },
  { id: 'bw-qa-admin-012', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Custom columns for workspace widgets require which combination?',
    options: ['ActiveView object privilege only', 'Category Folder object privilege', 'Business Administration – Facets and Columns usage privilege and the Column object privilege', 'Regenerate Reference'],
    answer: 2,
    explain: 'Columns (and facets, facet trees, facet folders) need the Facets and Columns usage privilege plus the matching object privileges.' },
  { id: 'bw-qa-admin-013', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'A company wants a small team, separate from the general Business Administrators group, to run workspaces. Which approach does the course recommend?',
    options: ['Create a dedicated group (e.g. “BW Management”), give it the business administration and workspace privileges and permissions, and add the team to it', 'Give each person System Administration rights', 'Grant privileges user by user', 'Share the Admin account with that team'],
    answer: 0,
    explain: 'For more granularity, create a group, assign the workspace-related rights to it, and manage membership.' },
  { id: 'bw-qa-admin-014', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'What is the difference between an object privilege and a usage privilege?',
    options: ['They are the same thing with two names', 'Usage privileges are granted in the Permissions page of an item', 'Object privileges control who may create an item type; usage privileges control who may use a feature', 'Object privileges are per item; usage privileges are per folder'],
    answer: 2,
    explain: 'Object privilege = create a type (Category, Facet, ActiveView…). Usage privilege = use a function (Move Business Workspaces, Perspectives Tab…). Permissions are per item.' },
  { id: 'bw-qa-admin-015', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Which two object privileges are only needed when the corresponding widgets or features are used? (Choose two.)',
    options: ['Classification', 'WebReports', 'Category', 'Activity Manager'],
    answer: [1, 3],
    explain: 'WebReports (when widgets use WebReports) and Activity Manager (to monitor metadata changes in the activity feed) are conditional; Category and Classification are always needed.' },

  // ---------------------------------------------------------------- ws-using
  { id: 'bw-qa-using-001', domain: 'ws-using', guide: 'bw-navigate-smart-view',
    q: 'A project manager needs to know who leads the team of a workspace. Where does she look in Smart View?',
    options: ['The Metadata tile', 'The Recently Accessed tile', 'The Discussion tile', 'The expanded Team tile ▸ Roles tab ▸ role details'],
    answer: 3,
    explain: 'The team lead is a property of a role and is shown in the role details on the Roles tab.' },
  { id: 'bw-qa-using-002', domain: 'ws-using', guide: 'bw-navigate-smart-view',
    q: 'A reader clicks the Training Time field in the Metadata tile but cannot type. What explains this?',
    options: ['Inline editing requires the Edit Attributes permission, which readers usually lack', 'Only Classic View can show metadata', 'The workspace is reserved', 'The tile is broken'],
    answer: 0,
    explain: 'With Edit Attributes users click a field, change it and press Enter; with See/See Contents the values are read-only.' },
  { id: 'bw-qa-using-003', domain: 'ws-using', guide: 'bw-navigate-smart-view',
    q: 'Which two settings must both be in place for a user to see the navigation tree on a workspace’s Documents tab? (Choose two.)',
    options: ['The workspace type has a widget icon', 'The user has the Move Business Workspaces privilege', 'The administrator enabled the Simple User Profile in Configure Smart View', 'The user switched on Navigation tree in the Business Workspace section of their profile settings'],
    answer: [2, 3],
    explain: 'The option only appears in the user’s settings when the Simple User Profile is enabled; then the user turns it on.' },
  { id: 'bw-qa-using-004', domain: 'ws-using', guide: 'bw-navigate-smart-view',
    q: 'After the Simple User Profile is enabled, what changes on a user’s profile page?',
    options: ['Users can edit other users’ profiles', 'The Following, Followers and Activity tabs are no longer shown', 'The email address is hidden', 'The profile can no longer be opened'],
    answer: 1,
    explain: 'The simple profile drops the social tabs (Following, Followers, Activity).' },
  { id: 'bw-qa-using-005', domain: 'ws-using', guide: 'bw-navigate-classic',
    q: 'In Classic View, which panel on the right of a workspace lists tasks and workflow steps related to it?',
    options: ['Attributes', 'Recent Changes', 'WS Reference', 'Work Items'],
    answer: 3,
    explain: 'Work Items shows assignments such as tasks and workflow steps for the workspace.' },
  { id: 'bw-qa-using-006', domain: 'ws-using', guide: 'bw-navigate-classic',
    q: 'In Classic View a user wants to change a value shown under Attributes on the right of a workspace. What should she do?',
    options: ['Open the workspace Functions menu ▸ Properties ▸ Categories', 'Use the Business Workspaces menu ▸ Search', 'Use Edit Page', 'Click the value in the panel'],
    answer: 0,
    explain: 'The Attributes sidebar widget is display-only; attributes are edited through Properties ▸ Categories.' },
  { id: 'bw-qa-using-007', domain: 'ws-using', guide: 'bw-navigate-classic',
    q: 'Which statement about the WS Reference sidebar widget is correct?',
    options: ['It shows the workspace’s permissions', 'It links to the template', 'It shows a reference number held in a category attribute that points to a business object', 'It lists all participants'],
    answer: 2,
    explain: 'WS Reference displays a reference (via a category attribute) to the business object; with Extended ECM it can open the object in the business application.' },
  { id: 'bw-qa-using-008', domain: 'ws-using', guide: 'bw-using-classic',
    q: 'Users drag ten files into a workspace folder whose category has required attributes. What is the quickest way to fill those attributes?',
    options: ['Ask an administrator to remove the category', 'Delete the files and upload them one by one', 'Show the incomplete items ▸ select all ▸ Complete Selected Items ▸ Submit All Changes ▸ Accept', 'Edit the workspace’s Metadata tile'],
    answer: 2,
    explain: 'The yellow band leads to the incomplete items, which can be completed together on the Edit Attributes page.' },
  { id: 'bw-qa-using-009', domain: 'ws-using', guide: 'bw-using-classic',
    q: 'After filling the attributes of documents inside a workspace, a user notices the workspace’s Attributes panel did not change. Why?',
    options: ['The update failed', 'Document attributes belong to the documents; the workspace has its own category values', 'The panel only refreshes overnight', 'Attributes are shown only in Smart View'],
    answer: 1,
    explain: 'Items inside a workspace usually carry different categories from the workspace itself.' },
  { id: 'bw-qa-using-010', domain: 'ws-using', guide: 'bw-using-classic',
    q: 'A column showing a document attribute must appear in one folder inside a workspace. Which two steps are required besides creating the column? (Choose two.)',
    options: ['Add the column under Local Columns in that folder’s Properties ▸ Columns', 'Restart the search engine', 'Give users the Move Business Workspaces privilege', 'Set the column’s availability to that folder'],
    answer: [0, 3],
    explain: 'A column must be available where it is used, and then added to the folder’s displayed columns.' },
  { id: 'bw-qa-using-011', domain: 'ws-using', guide: 'bw-using-classic',
    q: 'Columns added on a root folder also show inside each workspace, where they are useless. How do you stop that for a workspace?',
    options: ['Remove the workspace category', 'Move the workspace', 'Delete the columns', 'In the workspace’s Properties ▸ Columns, clear Include for the inherited columns'],
    answer: 3,
    explain: 'Inherited columns can be excluded per container in the Inherited Columns section.' },
  { id: 'bw-qa-using-012', domain: 'ws-using', guide: 'bw-using-smart-view',
    q: 'A team lead adds a new colleague to a workspace in Smart View. What decides what the colleague can do there?',
    options: ['The order in which participants were added', 'The role selected in Assign role', 'The colleague’s department', 'The perspective'],
    answer: 1,
    explain: 'Participants are added to roles, and the role’s permissions (from the template) define their access.' },
  { id: 'bw-qa-using-013', domain: 'ws-using', guide: 'bw-using-smart-view',
    q: 'An auditor asks for a list of everyone with access to a workspace. What can the team lead provide quickly from Smart View?',
    options: ['A CSV export of the selected participants from the Team page', 'A screenshot of the Metadata tile', 'The workspace template', 'The perspective XML'],
    answer: 0,
    explain: 'On the expanded Team tile, participants (and roles) can be selected and downloaded as CSV.' },
  { id: 'bw-qa-using-014', domain: 'ws-using', guide: 'bw-using-smart-view',
    q: 'A user clicks a task list on a workspace’s Documents tab to add a task. Where does she end up?',
    options: ['In Classic View, inside the task list, where Add Item ▸ Task is used', 'In the Notification Center', 'In the workflow designer', 'In a Smart View task dialog'],
    answer: 0,
    explain: 'Task lists are handled in Classic View; Smart View opens them there.' },
  { id: 'bw-qa-using-015', domain: 'ws-using', guide: 'bw-using-smart-view',
    q: 'A designer adds a Workspaces widget to a page. Which setting is required for it?',
    options: ['A search form', 'A facet tree', 'A workspace type', 'A LiveReport'],
    answer: 2,
    explain: 'The Workspaces widget (default title “My workspaces”) lists workspaces of the workspace type configured on it.' },
  { id: 'bw-qa-using-016', domain: 'ws-using', guide: 'bw-using-smart-view',
    q: 'Users complain that business workspaces never appear in the Recently Accessed tile of their landing page. What fixes this?',
    options: ['Enable Insights on every workspace', 'An administrator selects the Business Workspace object type under Recently Accessed Items in Configure Smart View', 'Users mark every workspace as a favorite', 'Restart the Admin server'],
    answer: 1,
    explain: 'The Recently Accessed Items section decides which object types the tile tracks.' },
  { id: 'bw-qa-using-017', domain: 'ws-using', guide: 'bw-editing',
    q: 'Which three permissions or privileges are needed for Edit page to appear in the Smart View Profile menu? (Choose three.)',
    options: ['System Administration rights', 'ActiveView – Perspectives Tab usage privilege', 'ActiveView object privilege', 'Modify permission on the perspective in the Perspectives volume', 'Move Business Workspaces'],
    answer: [1, 2, 3],
    explain: 'All three are required; neither Move Business Workspaces nor System Administration rights are part of it.' },
  { id: 'bw-qa-using-018', domain: 'ws-using', guide: 'bw-editing',
    q: 'A designer tries to change the Team widget of a workspace page with Edit page and cannot. Why?',
    options: ['The Team widget is read-only for everyone', 'Edit page only works in Classic View', 'She needs Regenerate Reference', 'Edit page does not support Business Workspaces widgets; workspace perspectives are edited in Perspective Manager'],
    answer: 3,
    explain: 'Edit page cannot edit Business Workspaces widgets, the Content Intelligence carousel or custom widgets with custom property types.' },
  { id: 'bw-qa-using-019', domain: 'ws-using', guide: 'bw-editing',
    q: 'A workspace was created under Customers ▸ EMEA because its Region attribute said EMEA. The customer moves to APAC and the attribute is changed. What happens?',
    options: ['The workspace is renamed to APAC', 'The change is rejected', 'The workspace moves to Customers ▸ APAC automatically', 'The workspace stays in EMEA until someone with the Move Business Workspaces privilege moves it'],
    answer: 3,
    explain: 'The location is worked out at creation; changing the attribute later does not move the workspace.' },
  { id: 'bw-qa-using-020', domain: 'ws-using', guide: 'bw-editing',
    q: 'A workspace is moved from a plain folder into another business workspace. Which two outcomes are correct? (Choose two.)',
    options: ['The workspace is converted into a folder', 'Inherited team roles and permissions are removed', 'Team roles assigned directly to the moved workspace remain', 'All participants are deleted'],
    answer: [1, 2],
    explain: 'On a move inherited roles go; directly assigned roles stay. Roles of the new parent are copied in only when the “always inherit from target destination” option is on.' },
  { id: 'bw-qa-using-021', domain: 'ws-using', guide: 'bw-editing',
    q: 'The header of a workspace should show a short summary under its name. Which property does the default Header widget use for that?',
    options: ['The node description, via {description}', 'The template name', 'The classification', 'The owner group'],
    answer: 0,
    explain: 'The Header widget’s description option defaults to {description}, so editing the workspace description changes the header text.' },
  { id: 'bw-qa-using-022', domain: 'ws-using', guide: 'bw-editing',
    q: 'Last month the template of the Customer type gained a “Compliance” folder. What happens to the 400 customer workspaces created before?',
    options: ['Nothing — templates are copied only at creation; existing workspaces need a deliberate change', 'They are recreated from the new template', 'They switch to a new workspace type', 'They get the folder at the next login'],
    answer: 0,
    explain: 'There is no live link between a workspace and its template; existing workspaces must be updated separately.' },
  { id: 'bw-qa-using-023', domain: 'ws-using', guide: 'bw-editing',
    q: 'A workspace was created with the wrong workspace type. What is the realistic fix?',
    options: ['Change the classification of the workspace', 'Edit the perspective rules', 'Change the type in Properties ▸ General', 'Create a workspace of the right type and move the content into it'],
    answer: 3,
    explain: 'There is no action that switches an existing workspace to another type; create the right one and move the content.' },
  { id: 'bw-qa-using-024', domain: 'ws-using', guide: 'bw-editing',
    q: 'A category’s reference number schema is changed and all existing workspaces are upgraded to the new category version. The workspace names were generated from the reference. What happens to the names?',
    options: ['The workspaces lose their category', 'They are regenerated automatically', 'The reference attribute changes, but the generated workspace names do not', 'The workspaces are moved'],
    answer: 2,
    explain: 'Updating objects with the changed category only changes the attribute; the generated workspace name stays as it was.' },
  { id: 'bw-qa-using-025', domain: 'ws-using', guide: 'bw-editing',
    q: 'Which two edits can be made to an existing workspace according to the course? (Choose two.)',
    options: ['Adding or removing categories', 'Copying or moving it to another folder', 'Changing its template', 'Changing the workspace type'],
    answer: [0, 1],
    explain: 'Attributes, categories, link, sharing, rename, copy/move, delete, comments and favorites can be changed; the template and type cannot.' },
  { id: 'bw-qa-using-026', domain: 'ws-using', guide: 'bw-editing',
    q: 'Users try to copy a project workspace but the Copy action is not offered for workspaces of that type. What is the most likely reason?',
    options: ['Copying needs the Regenerate Reference privilege', 'The workspace has no perspective', 'The template is missing a classification', 'Workspace copying is not allowed in the workspace type settings'],
    answer: 3,
    explain: 'Whether users may copy workspaces is a setting of the workspace type.' },

  // ---------------------------------------------------------------- bu-collab
  { id: 'bw-qa-collab-001', domain: 'bu-collab', guide: 'bw-navigate-smart-view',
    q: 'A user wants to be informed of every new answer in a workspace discussion. What should she do in the Discussion tile?',
    options: ['Add the discussion to a collection', 'Reserve the discussion', 'Click Follow all', 'Mark the workspace as a favorite'],
    answer: 2,
    explain: 'Follow all follows the whole discussion; unfollow later with the arrow next to Following all.' },
  { id: 'bw-qa-collab-002', domain: 'bu-collab', guide: 'bw-using-smart-view',
    q: 'A team lead wants changes in a workspace to show up in her Notification Center. What must she do?',
    options: ['Create a facet tree', 'Enable Insights on the workspace', 'Add a Recently Accessed tab', 'Grant herself Move Business Workspaces'],
    answer: 1,
    explain: 'Insights subscribe the user to the workspace’s events; notifications arrive after a short delay.' },
  { id: 'bw-qa-collab-003', domain: 'bu-collab', guide: 'bw-using-smart-view',
    q: 'Where can a user see the list of workspaces for which she has enabled Insights?',
    options: ['Notification Center ▸ Settings', 'Personal ▸ Assignments', 'The Metadata tile', 'The Business Workspaces volume'],
    answer: 0,
    explain: 'The Notification Center settings list the workspaces with insights enabled.' },
  { id: 'bw-qa-collab-004', domain: 'bu-collab', guide: 'bw-using-smart-view',
    q: 'Which two things happen when a user posts in the Comments page of a workspace? (Choose two.)',
    options: ['A New Updates button appears after a few seconds', 'All participants are emailed immediately', 'The workspace is reserved', 'The comment joins the workspace’s activity feed'],
    answer: [0, 3],
    explain: 'Comments sit in the activity feed alongside activity messages; a New Updates button signals new entries.' },
  { id: 'bw-qa-collab-005', domain: 'bu-collab', guide: 'bw-using-classic',
    q: 'A team member posts a new topic in the workspace forum from Classic View. Where else will the team see it?',
    options: ['In the Metadata tile', 'In the Notification Center Settings', 'Only in Classic View', 'In the Discussion tile of the workspace in Smart View'],
    answer: 3,
    explain: 'The Discussion tile shows posts and replies of the workspace’s forum, whichever interface they were posted in.' },
  { id: 'bw-qa-collab-006', domain: 'bu-collab', guide: 'bw-using-smart-view',
    q: 'Which statement about the activity messages in a workspace header is correct?',
    options: ['They replace the Team tile', 'They are shown on every tab', 'They are shown only on the Overview tab', 'They are shown only in Classic View'],
    answer: 2,
    explain: 'The header activity feed is visible on the Overview tab; switching to another tab hides it — use the Comments button to see the messages again.' },
  { id: 'bw-qa-collab-007', domain: 'bu-collab', guide: 'bw-using-smart-view',
    q: 'With Extended ECM for Microsoft 365 (Office 365 in 22.1), which widget shows the email conversations of the shared inbox of the Microsoft team connected to a workspace?',
    options: ['Team Notebook widget', 'Calendar widget', 'Conversations widget', 'Header widget'],
    answer: 2,
    explain: 'The Conversations widget shows the shared inbox; Calendar shows the team calendar; Team Notebook the shared notebook.' },

  // ---------------------------------------------------------------- bu-content
  { id: 'bw-qa-content-001', domain: 'bu-content', guide: 'bw-navigate-smart-view',
    q: 'A user uploads “Customer Feedback for Product X.pdf” to a workspace folder and must give it the business name “Heated Tents Feedback”. How is that done most directly in Smart View?',
    options: ['Download, rename locally and upload again', 'Edit the Metadata tile', 'Ask the administrator to change the name pattern', 'Hover the document ▸ Rename (or … ▸ Rename) and replace the whole name'],
    answer: 3,
    explain: 'The Inline Action Bar offers Rename; on narrow screens it is under More actions.' },
  { id: 'bw-qa-content-002', domain: 'bu-content', guide: 'bw-navigate-smart-view',
    q: 'Which three actions can appear on the Inline Action Bar of a document in a workspace’s Documents tab? (Choose three.)',
    options: ['Add version', 'Start Workflow', 'Collect', 'Enable Business Workspaces', 'Regenerate Reference'],
    answer: [0, 1, 2],
    explain: 'Document actions include Properties, Copy link, Share, Edit, Rename, View permissions, Download, Reserve, Copy, Move, Add version, Delete, Collect and Start Workflow — limited to the user’s permissions.' },
  { id: 'bw-qa-content-003', domain: 'bu-content', guide: 'bw-navigate-classic',
    q: 'Which three ways does the course name to reach a business workspace? (Choose three.)',
    options: ['Searching for it', 'Opening the workspace template', 'Through the Recycle Bin', 'Navigating the folder hierarchy', 'Recently accessed or favorites'],
    answer: [0, 3, 4],
    explain: 'Browse, recently accessed, favorites and search. Opening the template shows the master copy, not the workspace.' },
  { id: 'bw-qa-content-004', domain: 'bu-content', guide: 'bw-navigate-classic',
    q: 'A user in Smart View needs a Classic View function on the folder she is looking at. What happens to her location when she switches to Classic View?',
    options: ['She lands on the Enterprise workspace', 'She stays on the same container', 'She lands in her Personal Workspace', 'She is signed out'],
    answer: 1,
    explain: 'Switching views in either direction keeps the current location.' },
  { id: 'bw-qa-content-005', domain: 'bu-content', guide: 'bw-using-smart-view',
    q: 'A user drops a PDF into a workspace folder in Smart View and an Upload file dialog asks for Language and Price level. Why?',
    options: ['Smart View always asks for these fields', 'The PDF is too large', 'The user lacks Add Items', 'The folder carries a category with required attributes that new documents get'],
    answer: 3,
    explain: 'When the target folder has a category with required attributes, the upload dialog collects them.' },
  { id: 'bw-qa-content-006', domain: 'bu-content', guide: 'bw-using-smart-view',
    q: 'How can several business workspaces be gathered in one place for a review without moving them?',
    options: ['Change their workspace type', 'Rename them with a common prefix', 'Select them and choose Collect to add them to a collection', 'Copy them into a new folder'],
    answer: 2,
    explain: 'Business workspaces can be added to a collection — a set of pointers — like other items.' },
  { id: 'bw-qa-content-007', domain: 'bu-content', guide: 'bw-using-classic',
    q: 'Hundreds of customer workspaces sit in one folder. A sales manager needs only those of one sales rep. What is the quickest way in Classic View?',
    options: ['Create a new workspace type per rep', 'Open the Content Filter sidebar and click the sales rep’s value', 'Open each workspace', 'Export the folder to Excel'],
    answer: 1,
    explain: 'Where a facet tree is available on the root folder, the Content Filter filters workspaces by attribute values.' },

  // ---------------------------------------------------------------- more multiple-response
  { id: 'bw-qa-concepts-012', domain: 'ws-concepts', guide: 'bw-intro-concepts',
    q: 'Which two reasons does OpenText give for building business workspaces? (Choose two.)',
    options: ['End users resisted EIM systems that added work without clear benefit', 'Administrators struggled with large, rigid systems that were hard to change', 'Content Server could not store documents before', 'Leading applications required a new database'],
    answer: [0, 1],
    explain: 'Workspaces answer an adoption problem on both sides: simpler daily work for users, rules and templates that are easy to change for administrators.' },
  { id: 'bw-qa-infra-010', domain: 'ba-bw-infra', guide: 'bw-admin-page-volume',
    q: 'Which two tasks are done on the Business Workspaces administration page rather than in the Business Workspaces volume? (Choose two.)',
    options: ['Downloading the Outlook add-in manifest', 'Creating a workspace type', 'Creating a saved query', 'Enabling Business Workspaces'],
    answer: [0, 3],
    explain: 'Enable, Configure, Import Configuration, Migration Administration and Set up Outlook Add-in are on the admin page; types and saved queries are configuration objects in the volume.' },
  { id: 'bw-qa-admin-016', domain: 'ba-admin-roles', guide: 'bw-rights',
    q: 'Which two settings does the course use when granting the administrator group access to a configuration volume? (Choose two.)',
    options: ['Apply To: This Item only', 'Full Control including Edit Permissions', 'All permissions except Edit Permissions', 'Apply To: This Item & Sub-Items'],
    answer: [2, 3],
    explain: 'Permissions up to Delete (no Edit Permissions), applied to the item and its sub-items so existing configuration objects are covered too.' },
  { id: 'bw-qa-using-027', domain: 'ws-using', guide: 'bw-navigate-classic',
    q: 'Which two sidebar widgets appear on the right of a business workspace in Classic View in the course example? (Choose two.)',
    options: ['Navigation tree', 'Recent Changes', 'WS Reference', 'Team Notebook'],
    answer: [1, 2],
    explain: 'The course example shows Attributes, Recent Changes, Work Items and WS Reference. Team Notebook is a Microsoft 365 widget; the navigation tree is a Smart View option.' },
  { id: 'bw-qa-collab-008', domain: 'bu-collab', guide: 'bw-navigate-smart-view',
    q: 'Which two actions can a user take from the Discussion tile of a workspace? (Choose two.)',
    options: ['Ask a question', 'Search discussions for questions', 'Change the workspace type', 'Grant the Perspectives Tab privilege'],
    answer: [0, 1],
    explain: 'The tile lets users read the latest posts, reply, ask questions, follow and search; configuration changes are elsewhere.' },
];
