'use strict';
// Practice questions for the Extended ECM (Content Server) Cloud Practitioner
// credential. They test GENERAL managed-cloud delivery practice only. They do
// not quote or predict OpenText's "Practitioner Access to the Cloud: General
// Guidelines", which is provided in the OpenText Learning Platform course and
// governs wherever it differs.

module.exports = [
  // ============================================================ cp-model
  {
    id: 'cp-q-model-001', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'In a managed cloud deployment of Extended ECM, who is normally responsible for the servers, database, storage and backups?',
    options: ['The cloud provider operating the service', 'The customer’s business administrator', 'The partner consultant on the project', 'Each end user'],
    answer: 0,
    explain: 'In managed delivery the provider runs the platform and is accountable for infrastructure, backups and availability; practitioners work in the application.',
  },
  {
    id: 'cp-q-model-002', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'A consultant needs a new optional module installed in the customer’s cloud environment. What is the appropriate path?',
    options: ['Raise a service request with cloud operations', 'Ask for remote desktop access to the server and install it', 'Install it through a custom script in production', 'Ask a user with System Administration rights to do it'],
    answer: 0,
    explain: 'Installing modules and patches is a platform change performed by the provider through a scheduled, approved request.',
  },
  {
    id: 'cp-q-model-003', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Which two tasks are typically performed by the customer or partner practitioner inside the application? (Choose two.)',
    options: ['Creating workspace types and templates', 'Configuring perspectives and facets', 'Applying operating system patches', 'Resizing database storage', 'Changing firewall rules'],
    answer: [0, 1],
    explain: 'Application configuration is the practitioner’s area; operating system, database and network changes belong to the provider.',
  },
  {
    id: 'cp-q-model-004', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Why do managed cloud services restrict direct server access for practitioners?',
    options: ['To preserve the provider’s accountability, consistency of the platform, auditability and security', 'Because servers do not exist in the cloud', 'To make projects slower on purpose', 'Because Content Server cannot be administered'],
    answer: 0,
    explain: 'The provider can only guarantee availability and security if it controls platform changes and keeps them traceable.',
  },
  {
    id: 'cp-q-model-005', domain: 'cp-model', guide: 'cp-environments-change',
    q: 'What is the purpose of a separate test environment in a cloud subscription?',
    options: ['To accept exactly what will go live, with representative test data, before production', 'To store production backups', 'To let users work when production is slow', 'To keep old documents'],
    answer: 0,
    explain: 'Test/QA is where integration and acceptance tests run on the same configuration that will be promoted.',
  },
  {
    id: 'cp-q-model-006', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'A user deleted an important folder last month and the Recycle Bin has already purged it. What is the right action?',
    options: ['Request a restore from the cloud provider through the agreed process', 'Ask for database access to recover it', 'Recreate the documents from memory', 'Copy them from a consultant’s laptop'],
    answer: 0,
    explain: 'Backups and restores are provider services; use the formal request path.',
  },
  {
    id: 'cp-q-model-007', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Which statement describes shared responsibility in a managed cloud correctly?',
    options: ['The provider is responsible for everything, including business content decisions', 'The provider runs the platform and its operations; the customer (with partners) owns its content, users and application configuration within the agreed scope', 'The customer runs the infrastructure; the provider only sends invoices', 'Responsibilities are decided ad hoc per incident'],
    answer: 1,
    explain: 'The contract and the provider’s guidelines define the line; typically platform with the provider, business use and configuration with the customer.',
  },
  {
    id: 'cp-q-model-008', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Which two items normally require a request to cloud operations? (Choose two.)',
    options: ['Changing a server-level configuration setting', 'Obtaining server log files', 'Adding a folder to a workspace template', 'Assigning a user to a workspace role', 'Creating a facet'],
    answer: [0, 1],
    explain: 'Server settings and server logs are below the application line. Templates, roles and facets are configured in the application.',
  },
  {
    id: 'cp-q-model-009', domain: 'cp-model', guide: 'cp-environments-change',
    q: 'Where should a practitioner experiment with a new perspective layout?',
    options: ['In the development environment', 'Directly in production during business hours', 'In production at night', 'On a personal laptop installation with copied production data'],
    answer: 0,
    explain: 'Experimenting belongs in development; production only receives tested, approved changes.',
  },
  {
    id: 'cp-q-model-010', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'A practitioner finds a performance problem that seems to come from the database. What is the appropriate step?',
    options: ['Report it to cloud operations with evidence (what, when, which users, steps to reproduce)', 'Ask for database credentials to tune it', 'Restart the services yourself', 'Ignore it'],
    answer: 0,
    explain: 'Collect evidence at application level and hand the platform issue to the provider.',
  },
  {
    id: 'cp-q-model-011', domain: 'cp-model', guide: 'cp-prepare',
    q: 'Which certifications must be held before enrolment in the Cloud Practitioner course?',
    options: ['Business User (5-0158) and Business Administrator (5-0159)', 'Developer (5-0157) only', 'Analyst (5-0155) and Administrator (5-0156)', 'None'],
    answer: 0,
    explain: 'Both prerequisite certifications must be earned and their badges accepted before enrolment.',
  },
  {
    id: 'cp-q-model-012', domain: 'cp-model', guide: 'cp-prepare',
    q: 'Where does a practitioner find the official guidelines for working in OpenText Cloud environments?',
    options: ['In the Cloud Practitioner course on the OpenText Learning Platform', 'In the Content Server admin pages', 'In the Business Scenario packages', 'In OTDS'],
    answer: 0,
    explain: 'The guidelines are provided inside the course and govern; general practice material does not replace them.',
  },
  {
    id: 'cp-q-model-013', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Which two reasons explain why customers on a standardised managed platform are discouraged from unmanaged changes? (Choose two.)',
    options: ['They can break upgrades and supportability', 'They are not traceable through the change process', 'They make the platform faster', 'They reduce licence costs', 'They are required for Smart View'],
    answer: [0, 1],
    explain: 'Unmanaged changes undermine upgrades, support and auditability.',
  },
  {
    id: 'cp-q-model-014', domain: 'cp-model', guide: 'cp-environments-change',
    q: 'What kind of data should normally be used in a development environment?',
    options: ['Synthetic or approved anonymised test data', 'A full copy of production', 'Customer data emailed by users', 'Any data the consultant has'],
    answer: 0,
    explain: 'Development rarely has production-grade controls; use test data unless an approved process says otherwise.',
  },
  {
    id: 'cp-q-model-015', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'Users must be added and assigned to roles in the new workspaces. Who typically handles this, and how?',
    options: ['Customer administrators, through the customer’s identity and access process', 'The cloud provider’s database team via SQL', 'Any consultant with the Admin password', 'End users themselves for any role'],
    answer: 0,
    explain: 'Identity and access are owned by the customer’s process (often OTDS synchronised from the corporate directory); role membership is application administration.',
  },
  {
    id: 'cp-q-model-016', domain: 'cp-model', guide: 'cp-operating-model',
    q: 'A practitioner is unsure whether a task is within their permitted scope in the cloud environment. What should they do?',
    options: ['Check the official guidelines and the project agreement, and ask through the formal channel before acting', 'Do it and explain later', 'Find a workaround that avoids the question', 'Ask a colleague to do it under their account'],
    answer: 0,
    explain: 'When in doubt, the governing guidelines and formal channels decide — not convenience.',
  },

  // ============================================================ cp-change
  {
    id: 'cp-q-change-001', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'How should a new workspace type, its template and perspective be moved from development to production?',
    options: ['Package them with Transport, deploy to test, accept, then deploy the same package to production', 'Re-create them by hand in production', 'Copy database tables', 'Email the configuration to users'],
    answer: 0,
    explain: 'Transport packages promote configuration consistently; the tested package is what goes live.',
  },
  {
    id: 'cp-q-change-002', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'A defect is found in production configuration that came from a transport package. What is the recommended fix path?',
    options: ['Fix in development, build a new package, test it, and promote it', 'Edit production directly and leave development unchanged', 'Delete the configuration', 'Ask users to work around it permanently'],
    answer: 0,
    explain: 'Fixing at the source keeps environments aligned; otherwise the next transport reintroduces the defect.',
  },
  {
    id: 'cp-q-change-003', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Which approach is preferred in a managed cloud when a requirement can be met either by configuration or by custom code?',
    options: ['Configuration', 'Custom code', 'Direct database changes', 'A browser plug-in'],
    answer: 0,
    explain: 'Configuration is supported, transportable and survives upgrades; customization needs approval and may block upgrades.',
  },
  {
    id: 'cp-q-change-004', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Which three steps belong in a change before it reaches production? (Choose three.)',
    options: ['Impact assessment and rollback plan', 'Testing in a non-production environment', 'Approval and an agreed time window', 'Skipping documentation to save time', 'Testing directly with production users’ data in development'],
    answer: [0, 1, 2],
    explain: 'Assess, test, approve and schedule. Documentation is part of the change, and production data does not belong in development tests.',
  },
  {
    id: 'cp-q-change-005', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'How is an OpenText Business Scenario introduced in a cloud landscape?',
    options: ['Deploy its packages in development first, adapt, then promote your adapted configuration through test to production', 'Deploy directly to production and adapt there', 'Build it from scratch in production', 'Install it as custom code on the server'],
    answer: 0,
    explain: 'Scenarios are transport packages and follow the same promotion path as any configuration.',
  },
  {
    id: 'cp-q-change-006', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Why should transport packages be versioned and stored with the change record?',
    options: ['So you know exactly what was deployed when, and can redeploy or compare', 'Because Content Server deletes them otherwise', 'To make them smaller', 'To share them with users'],
    answer: 0,
    explain: 'Traceability of what changed in each environment is a core change-management principle.',
  },
  {
    id: 'cp-q-change-007', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'A business user asks for a “quick fix” to a perspective directly in production because the release is next week. What is the best response?',
    options: ['Make the change in development, test it, and promote it through the normal change process (expedited if justified)', 'Edit production now and update development later', 'Give the user rights to edit production perspectives', 'Refuse any change'],
    answer: 0,
    explain: 'Urgency changes the speed of the process, not the path. Emergency/expedited changes still follow controls.',
  },
  {
    id: 'cp-q-change-008', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Which two are signs of a well-prepared production deployment? (Choose two.)',
    options: ['The package was accepted in test', 'Users were informed, for example with a system message', 'The change was made first in production', 'There is no rollback plan', 'Only the consultant knows what changed'],
    answer: [0, 1],
    explain: 'Tested packages and communication are hallmarks of controlled change; undocumented, untested production edits are not.',
  },
  {
    id: 'cp-q-change-009', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Which of these is a customization rather than a configuration?',
    options: ['A custom OScript module deployed to the server', 'A new workspace template', 'A new facet', 'A smart document type with bots'],
    answer: 0,
    explain: 'Custom code is customization; templates, facets and smart document types are configuration.',
  },
  {
    id: 'cp-q-change-010', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'A transport to the cloud test environment fails because a category is missing there. What should the practitioner do?',
    options: ['Include the category in the workbench (or deploy it first) and redeploy', 'Create the category by hand differently in test', 'Ask for database access to insert it', 'Skip test and go to production'],
    answer: 0,
    explain: 'Resolve dependencies within Transport so every environment receives the same objects.',
  },
  {
    id: 'cp-q-change-011', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'What should happen after a production deployment?',
    options: ['Smoke-test, communicate, close the change with evidence and update the configuration register', 'Nothing', 'Delete the transport package', 'Change production again to tidy up'],
    answer: 0,
    explain: 'Verification and documentation close the loop and make the next change easier.',
  },
  {
    id: 'cp-q-change-012', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Which two practices help keep environments consistent? (Choose two.)',
    options: ['Promote configuration only through Transport packages', 'Never make untracked manual changes in test or production', 'Let each environment be configured by different people independently', 'Rebuild configuration manually per environment', 'Keep development out of date'],
    answer: [0, 1],
    explain: 'One source of truth plus controlled promotion avoids drift between environments.',
  },
  {
    id: 'cp-q-change-013', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'Who should approve a configuration change going to production?',
    options: ['The responsible business/change owner through the agreed change process, coordinated with the provider where needed', 'Any user who requested it', 'The consultant alone', 'Nobody; configuration needs no approval'],
    answer: 0,
    explain: 'Production changes need an accountable approver and coordination with operations.',
  },
  {
    id: 'cp-q-change-014', domain: 'cp-change', guide: 'cp-environments-change',
    q: 'A customer wants a feature that would require modifying product code in their managed cloud tenant. What is the best first step?',
    options: ['Look for a configuration-based alternative and, if code is still needed, follow the provider’s approved process for extensions', 'Patch the product files directly', 'Ask a user with admin rights to upload the code', 'Tell the customer it is impossible without investigating'],
    answer: 0,
    explain: 'Configuration first; any extension must go through the provider’s approved path, if allowed at all.',
  },

  // ============================================================ cp-security
  {
    id: 'cp-q-sec-001', domain: 'cp-security', guide: 'cp-security-data',
    q: 'A colleague asks you to share your administrator account password so he can finish a task tonight. What do you do?',
    options: ['Refuse; he must use his own named account with the rights he needs, requested through the proper process', 'Share it by email', 'Share it by chat and change it tomorrow', 'Write it in the project wiki'],
    answer: 0,
    explain: 'Accounts are personal; sharing credentials destroys accountability and breaches security practice.',
  },
  {
    id: 'cp-q-sec-002', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Which account setup follows least privilege for a consultant configuring perspectives and facets?',
    options: ['A named account with business administration privileges only for the needed functions, for the duration of the task', 'The built-in Admin account', 'A shared “consultant” account with System Administration rights', 'An end-user account of a customer employee'],
    answer: 0,
    explain: 'Grant only what the task requires, to a named person, for as long as needed.',
  },
  {
    id: 'cp-q-sec-003', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Which two are appropriate ways to handle log files needed for troubleshooting? (Choose two.)',
    options: ['Request them through the provider and share only the relevant excerpt', 'Remove or mask personal data before sharing', 'Post them in a public forum to get help', 'Keep them on a USB stick indefinitely', 'Email full logs to all project members'],
    answer: [0, 1],
    explain: 'Minimise and protect: obtain logs through approved channels, share the minimum, mask personal data, delete when done.',
  },
  {
    id: 'cp-q-sec-004', domain: 'cp-security', guide: 'cp-security-data',
    q: 'You need realistic documents to test a smart document type in development. Which data should you use?',
    options: ['Synthetic or approved anonymised samples', 'Production contracts downloaded to your laptop', 'Documents a user emailed you', 'Any documents found in production search'],
    answer: 0,
    explain: 'Test data should not expose real customer information unless an explicit, approved process allows it.',
  },
  {
    id: 'cp-q-sec-005', domain: 'cp-security', guide: 'cp-security-data',
    q: 'You accidentally pasted an API token into a support ticket. What should you do?',
    options: ['Report it and have the token revoked/rotated through the proper process', 'Delete the ticket comment and say nothing', 'Ignore it; tickets are private', 'Post a new token in the same ticket'],
    answer: 0,
    explain: 'Exposed credentials must be treated as compromised: report and rotate.',
  },
  {
    id: 'cp-q-sec-006', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Which access path is appropriate for a practitioner in a managed cloud environment?',
    options: ['The application UI and APIs through the provider’s approved sign-in', 'Direct database connections from a laptop', 'Remote desktop to the application server', 'Disabling MFA to speed up sign-in'],
    answer: 0,
    explain: 'Use approved interfaces and sign-in; never bypass controls.',
  },
  {
    id: 'cp-q-sec-007', domain: 'cp-security', guide: 'cp-security-data',
    q: 'A business user asks you to export all HR documents to a shared drive “for convenience”. What is the right approach?',
    options: ['Only proceed with proper authorisation, using approved features and destinations, and record it — otherwise decline', 'Export immediately', 'Export to your laptop first', 'Email the documents in batches'],
    answer: 0,
    explain: 'Exports of customer data need authorisation, approved channels and traceability.',
  },
  {
    id: 'cp-q-sec-008', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Which two practices protect customer data in documentation and training material? (Choose two.)',
    options: ['Use test data in screenshots', 'Mask names, numbers and content when real screens must be shown', 'Use real customer names to make examples realistic', 'Include production passwords in setup guides', 'Store screenshots on public file shares'],
    answer: [0, 1],
    explain: 'Documentation spreads widely; keep it free of real customer data and secrets.',
  },
  {
    id: 'cp-q-sec-009', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Your task requiring elevated privileges is finished. What should happen to those privileges?',
    options: ['They are removed or returned as agreed', 'They stay in case they are needed again', 'They are passed on to a colleague', 'They are documented in a public wiki'],
    answer: 0,
    explain: 'Least privilege applies over time as well: elevated rights should be time-limited.',
  },
  {
    id: 'cp-q-sec-010', domain: 'cp-security', guide: 'cp-security-data',
    q: 'Where should service account credentials for an integration be kept?',
    options: ['In the customer’s approved secret-management process', 'In the integration’s source code', 'In a spreadsheet on the consultant’s desktop', 'In the workspace description'],
    answer: 0,
    explain: 'Service accounts belong to the customer and are handled with approved secret storage, never in code or documents.',
  },
];
