'use strict';
// Developer certification 5-0157 — exam question bank. All questions original.
// Weights follow the outline: dev-oscript 53 %, dev-rest 35 %, dev-schema 12 %.

module.exports = [
  // ================================================================ dev-schema
  { id: 'dev-q-schema-001', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'A report must show the file size of the current version of each document. Which table holds the size?',
    options: ['DTree', 'DVersData', 'ProviderData', 'LLAttrData'], answer: 1,
    explain: 'DVersData has one row per version with DataSize and MimeType. Join it to DTree on DocID = DataID and Version = VersionNum to get the current version only. ProviderData says where the bytes are stored, not how big they are.' },
  { id: 'dev-q-schema-002', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which column of DTree identifies the type of an item, such as folder or document?',
    options: ['OwnerID', 'SubType', 'Catalog', 'PermID'], answer: 1,
    explain: 'SubType is the node type: 0 folder, 144 document, 136 compound document, 202 project, 299 LiveReport and so on. OwnerID is the (negative) volume.' },
  { id: 'dev-q-schema-003', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'You need every document anywhere below folder 51000, at any depth, in one simple query. Which table makes this easiest?',
    options: ['DTreeAncestors', 'KUAFChildren', 'DAuditNew', 'WSubWorkTask'], answer: 0,
    explain: 'DTreeAncestors stores a row for each node and each of its ancestors, so WHERE AncestorID = 51000 returns the whole subtree with one join. A recursive query on ParentID works too, but is slower and vendor-specific.' },
  { id: 'dev-q-schema-004', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which two tables do you join to list the direct members of a group named “Finance”? (Choose two.)',
    options: ['KUAF', 'KUAFChildren', 'DTreeACL', 'DVersData', 'LLAttrData'], answer: [0, 1],
    explain: 'KUAF holds users and groups (find the group by Name and Type = 1, and resolve member names); KUAFChildren maps the group ID to each ChildID. DTreeACL is about permissions on items, not membership.' },
  { id: 'dev-q-schema-005', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'In KUAF, how is a group distinguished from a user?',
    options: ['Groups have a negative ID', 'The Type column: 0 for users, 1 for groups', 'Groups have no Name', 'Groups are stored in a separate KGROUP table'], answer: 1,
    explain: 'Users and groups share KUAF; Type tells them apart (0 user, 1 group). Membership is in KUAFChildren.' },
  { id: 'dev-q-schema-006', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'A query on LLAttrData returns the same document three times for one attribute. What is the most likely reason?',
    options: ['The category is applied three times', 'Values are stored per version and the query did not restrict VerNum to the current version', 'LLAttrData is a view', 'The attribute is required'], answer: 1,
    explain: 'LLAttrData keeps attribute values for each version (VerNum). Join on the node\'s current version unless you want history. Multi-value attributes (EntryNum) can also repeat rows, but version history is the classic cause.' },
  { id: 'dev-q-schema-007', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which table records events such as “item created” or “permissions changed” with the performer and date?',
    options: ['DAuditNew', 'DTreeCore', 'KIni', 'WWork'], answer: 0,
    explain: 'DAuditNew holds the audit trail: AuditStr (event), DataID, PerformerID, AuditDate. Which events are recorded depends on the audit settings.' },
  { id: 'dev-q-schema-008', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'A LiveReport is defined with the query `SELECT Name FROM DTree WHERE ParentID = %1 AND CreatedBy = %2`. What is substituted for %2?',
    options: ['The second column of the result', 'The value the user enters for the second input', 'The ID of the user running the report, always', 'The DataID of the report'], answer: 1,
    explain: 'Placeholders are positional: %1 takes the first input, %2 the second. If you want the current user, define a user input (or a mechanism your release provides) — %2 is not magically the runner.' },
  { id: 'dev-q-schema-009', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'A LiveReport lists document names in a confidential folder to users who cannot open that folder. What is the cause?',
    options: ['The search index exposes them', 'LiveReport SQL runs against the database without permission filtering', 'The report is cached', 'Users have Public Access'], answer: 1,
    explain: 'The query runs as the Content Server database account. Unless the SQL joins DTreeACL with the user\'s groups, it returns rows regardless of permissions. Restrict the report or filter in SQL.' },
  { id: 'dev-q-schema-010', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'Which two are valid ways to make a LiveReport safe when its results include restricted items? (Choose two.)',
    options: ['Limit See permission on the report to people allowed to see all the results', 'Join DTreeACL and KUAFChildren in the SQL to filter rows for the current user', 'Rename the report', 'Run it only in Smart View', 'Add ORDER BY'], answer: [0, 1],
    explain: 'Either control who can run the report, or filter in SQL by the permissions of the running user. Renaming, ordering or the UI used change nothing about what the SQL returns.' },
  { id: 'dev-q-schema-011', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'Managers want to click an author\'s name in a “documents per author” LiveReport and see that author\'s documents. What should you configure?',
    options: ['A sub-report that takes the author as its input', 'A workflow', 'A second category', 'A WebLingo override'], answer: 0,
    explain: 'Link the author column to a detail LiveReport; the clicked value is passed as the sub-report\'s input (%1).' },
  { id: 'dev-q-schema-012', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'Which query result is best suited to a pie or bar chart output?',
    options: ['A list of DataIDs', 'One label column and one numeric column from a GROUP BY', 'A single text value', 'A row per audit event with many text columns'], answer: 1,
    explain: 'Charts plot a numeric value per label: `SELECT k.Name, COUNT(*) … GROUP BY k.Name` is the typical shape.' },
  { id: 'dev-q-schema-013', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which two statements about writing to Content Server tables are correct? (Choose two.)',
    options: ['Direct UPDATEs on DTree bypass audit, indexing and callbacks', 'Changes to nodes should go through the APIs (OScript, REST or CWS)', 'Direct INSERTs into DTree are the supported way to bulk-load', 'KUAF can be edited freely because OTDS ignores it', 'LiveReports are the recommended way to update metadata'], answer: [0, 1],
    explain: 'SQL is for reading. Writes go through the APIs so permissions, audit, search indexing and callbacks all run. Bulk loading uses supported tools or the APIs.' },
  { id: 'dev-q-schema-014', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which table gives you the step, performer and due date of active workflow tasks?',
    options: ['WMap', 'WSubWorkTask', 'DAuditNew', 'DVersData'], answer: 1,
    explain: 'WSubWorkTask holds the tasks (steps) of each sub-workflow, including performer and dates. WMap holds map definitions and WWork the workflow instances.' },
  { id: 'dev-q-schema-015', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Items directly inside a project have a ParentID that is the negative of the project\'s DataID. Why does this matter for SQL?',
    options: ['It does not matter', 'A query on ParentID = projectID misses them; use the negative value or DTreeAncestors', 'Those items are deleted', 'Projects store children in DVersData'], answer: 1,
    explain: 'Volume-like containers such as projects point their children at the container\'s volume (negative ID). Handle both signs or walk with DTreeAncestors.' },
  { id: 'dev-q-schema-016', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which two columns of DTree record who created an item and when? (Choose two.)',
    options: ['CreatedBy', 'CreateDate', 'OwnerID', 'ReservedBy', 'VersionNum'], answer: [0, 1],
    explain: 'CreatedBy is the KUAF ID of the creator and CreateDate the timestamp. OwnerID is the volume; ReservedBy is who has the item reserved.' },
  { id: 'dev-q-schema-017', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'A LiveReport uses `DATEADD(day, -30, GETDATE())`. What should the author note?',
    options: ['It works on every supported database', 'It is SQL Server syntax and must be rewritten for Oracle or PostgreSQL', 'It is OScript', 'It needs a sub-report'], answer: 1,
    explain: 'Date functions differ between SQL Server, Oracle and PostgreSQL. Joins and filters are portable; vendor functions are not.' },
  { id: 'dev-q-schema-018', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which table links a document version to the storage location of its file?',
    options: ['ProviderData, reached through DVersData.ProviderID', 'DTreeACL', 'KUAFChildren', 'CatRegionMap'], answer: 0,
    explain: 'DVersData.ProviderID points to ProviderData, which tells the storage provider (for example the External File Store) where the content is.' },
  { id: 'dev-q-schema-019', domain: 'dev-schema', guide: 'dev-livereports',
    q: 'Which input type should a LiveReport use so that users choose a folder with a picker and the report receives its ID?',
    options: ['Text', 'An item (node) input', 'Date', 'Boolean'], answer: 1,
    explain: 'Item, user and group inputs present pickers and pass numeric IDs into the %n placeholder.' },
  { id: 'dev-q-schema-020', domain: 'dev-schema', guide: 'dev-schema-sql',
    q: 'Which table holds the permission entries (owner, owner group, Public Access, assigned users and groups) of a node?',
    options: ['DTreeACL', 'KUAF', 'DTreeAncestors', 'DAuditNew'], answer: 0,
    explain: 'DTreeACL has a row per entry: DataID, RightID, ACLType and the Permissions bitmask.' },

  // ================================================================ dev-oscript (1/2)
  // --- language basics
  { id: 'dev-q-oscript-001', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'What does this code print? `List l = { "a", "b", "c" }` then `Echo( l[ 2 ] )`',
    options: ['a', 'b', 'c', 'An index error'], answer: 1,
    explain: 'OScript lists are 1-based: l[1] is "a", l[2] is "b". Strings and RecArrays are 1-based too.' },
  { id: 'dev-q-oscript-002', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Which OScript type should you declare for a variable that maps keys such as "name" and "owner" to values?',
    options: ['List', 'Assoc', 'RecArray', 'String'], answer: 1,
    explain: 'An Assoc is a key → value map, created with Assoc.CreateAssoc(). A List is ordered values; a RecArray is rows with named fields.' },
  { id: 'dev-q-oscript-003', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'A variable is declared `Dynamic x` and never assigned. Which test is true?',
    options: ['x == 0', 'x == ""', 'IsUndefined( x )', 'IsError( x )'], answer: 2,
    explain: 'Unassigned variables hold Undefined. IsDefined / IsUndefined test for it; it is not 0, not an empty string and not an Error.' },
  { id: 'dev-q-oscript-004', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'How is a block such as `if`, `for` or `while` closed in OScript?',
    options: ['With a closing brace }', 'With the keyword end', 'With endif / endfor', 'By indentation'], answer: 1,
    explain: 'Every block ends with `end`; `elseif` and `else` sit inside an if block. Indentation is for readers only.' },
  { id: 'dev-q-oscript-005', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Which two loop forms are valid OScript? (Choose two.)',
    options: ['`for i = 1 to 10` … `end`', '`for item in myList` … `end`', '`foreach (item : myList) { }`', '`loop i from 1 to 10 endloop`', '`for (i = 0; i < 10; i++)`'], answer: [0, 1],
    explain: 'OScript has a counting loop (`for i = 1 to n`) and an element loop (`for x in list`), plus while and repeat. C-style and Java-style loops do not exist.' },
  { id: 'dev-q-oscript-006', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'What type does a SELECT executed with CAPI.Exec return on success?',
    options: ['A List of Strings', 'A RecArray (rows of Records)', 'An Assoc', 'A JSON string'], answer: 1,
    explain: 'Query results come back as a RecArray; loop over it with `for rec in recs` and read fields by name (rec.DataID). On failure you get an Error value.' },
  { id: 'dev-q-oscript-007', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'How do built-in OScript functions usually report failure?',
    options: ['By throwing a Java exception', 'By returning an Error value that you test with IsError()', 'By writing to the audit log', 'By returning -1 always'], answer: 1,
    explain: 'OScript does not use exceptions like Java. Built-ins return an Error value; check it with IsError() before using the result.' },
  { id: 'dev-q-oscript-008', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Content Server code often returns an Assoc from functions. Which two keys does the common convention use? (Choose two.)',
    options: ['ok', 'errMsg', 'status_code', 'exception', 'result_set'], answer: [0, 1],
    explain: 'The convention is an Assoc with ok (Boolean) and errMsg (String), plus whatever data the function returns. Callers check rtn.ok first.' },
  { id: 'dev-q-oscript-009', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Which statement builds a new list with 4 appended to `ids`?',
    options: ['`ids = { @ids, 4 }`', '`ids.append( 4 )`', '`ids[] = 4`', '`push( ids, 4 )`'], answer: 0,
    explain: 'The @ operator splices a list into a list literal, so { @ids, 4 } is ids followed by 4. OScript lists have no append method.' },
  { id: 'dev-q-oscript-010', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Which package provides functions such as Upper, Trim, Elements and Format?',
    options: ['List', 'Str', 'OS', 'DAPI'], answer: 1,
    explain: 'String functions live in the Str package: Str.Upper, Str.Trim, Str.Elements (split), Str.Format (%1-style substitution).' },
  { id: 'dev-q-oscript-011', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'What does `Echo( "Count: ", 3 )` do?',
    options: ['Returns the string to the browser', 'Writes the values to the server console/log output', 'Creates an audit entry', 'Raises an error'], answer: 1,
    explain: 'Echo writes its arguments to the console and log output, which CSIDE shows while running the server. Use it for tracing, and remove it before production.' },
  { id: 'dev-q-oscript-012', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Which two statements about OScript functions are true? (Choose two.)',
    options: ['A function declares its return type, e.g. `function Integer Add(…)`', 'Parameters can have default values', 'Functions cannot have parameters', 'A function must be declared in a separate .os file per function', 'Return types are optional and ignored'], answer: [0, 1],
    explain: 'Functions declare a return type (or Void) and typed parameters, which may have defaults. A script feature may contain helper functions after its main function.' },
  { id: 'dev-q-oscript-013', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'In a `switch` statement, how do you make one case handle both "approved" and "published"?',
    options: ['Write `case "approved", "published"`', 'Write two cases that fall through without end', 'It is impossible; use if', 'Use `case "approved" || "published"`'], answer: 0,
    explain: 'A case can list several values separated by commas; each case and the default end with their own `end`. There is no fall-through.' },
  { id: 'dev-q-oscript-014', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'Code reads a field as `rec.DATAID` but the SQL selected `DataID`. On Oracle the column comes back as DATAID. What happens?',
    options: ['It fails on SQL Server only', 'It works: Record field access is case-insensitive', 'It always returns Undefined', 'It returns the column position'], answer: 1,
    explain: 'OScript names, including Record field names, are not case-sensitive, so the same code works on Oracle, SQL Server and PostgreSQL.' },
  { id: 'dev-q-oscript-015', domain: 'dev-oscript', guide: 'dev-oscript-basics',
    q: 'What does `Length( "Content" )` return?',
    options: ['6', '7', '8', 'An Error'], answer: 1,
    explain: 'Length works on strings, lists and RecArrays; "Content" has 7 characters.' },

  // --- objects, OSpaces, orphans
  { id: 'dev-q-oscript-016', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'You must change the behaviour of an object delivered in another module\'s OSpace. What is the supported approach?',
    options: ['Edit the object in its OSpace', 'Create an orphan of it in your own OSpace and override features there', 'Copy the delivered .oll into your module', 'Patch the database'], answer: 1,
    explain: 'An orphan is a child of the delivered object kept in your OSpace. It inherits everything and overrides only what you change, survives updates of the parent module and is removed with yours.' },
  { id: 'dev-q-oscript-017', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'Which statement best describes OScript inheritance?',
    options: ['Classes inherit from several interfaces', 'Each object has one parent and sees all the parent\'s features until it overrides them', 'Objects copy their parent\'s features once at creation and never see later changes', 'There is no inheritance in OScript'], answer: 1,
    explain: 'OScript is prototype-based with single inheritance: a child sees its parent\'s features (values and scripts) and overrides by defining a feature with the same name.' },
  { id: 'dev-q-oscript-018', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'A script defined on a parent reads `.fHTMLFile`. It is called on a child that sets fHTMLFile = "child.html". What value does the script see?',
    options: ['The parent\'s value', '"child.html"', 'Undefined', 'An error, because the script is on the parent'], answer: 1,
    explain: 'this is the object the script was called on, so the child\'s override is used. This late binding lets one generic script serve many children.' },
  { id: 'dev-q-oscript-019', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'What is an OSpace?',
    options: ['A database schema', 'A saved collection of OScript objects, compiled into a file that a module ships', 'A Smart View perspective', 'A storage provider'], answer: 1,
    explain: 'Objects live in OSpaces; a module ships one or more of them and the server loads them at start-up.' },
  { id: 'dev-q-oscript-020', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'Which two are features of an OScript object? (Choose two.)',
    options: ['A value such as an Integer, String or List', 'A script containing code', 'A database table', 'A WebLingo file', 'An OTDS partition'], answer: [0, 1],
    explain: 'Features are either values or scripts. WebLingo files and tables are separate artefacts that objects may refer to.' },
  { id: 'dev-q-oscript-021', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'How does code in one module usually reach shared objects of another OSpace, for example the node subsystem?',
    options: ['Through a $ global named after the OSpace, e.g. $LLIAPI.LLNodeSubsystem', 'By file path', 'Through a REST call', 'By SQL'], answer: 0,
    explain: 'Each OSpace\'s Globals object is published as a $ global; its features point at shared objects such as $LLIAPI.LLNodeSubsystem.' },
  { id: 'dev-q-oscript-022', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'During Execute, a developer stores the current user\'s name in a feature of the permanent handler object in the OSpace. What is the risk?',
    options: ['None', 'The value is shared and leaks into other requests on that thread', 'The OSpace is deleted', 'The name is encrypted'], answer: 1,
    explain: 'Permanent objects are shared across requests. Keep run-time state in locals or temporary objects (created with OS.NewTemp or a New() script).' },
  { id: 'dev-q-oscript-023', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'Which two are good reasons to use orphans rather than editing delivered objects? (Choose two.)',
    options: ['Delivered OSpaces are replaced by updates, losing in-place edits', 'Your module can be uninstalled cleanly', 'Orphans run faster than any other object', 'Orphans bypass permissions', 'Orphans need no restart'], answer: [0, 1],
    explain: 'Orphans keep your changes in your own module, which survives updates and can be removed. They are not faster, do not bypass permissions, and new registrations still need a restart.' },
  { id: 'dev-q-oscript-024', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'Many delivered objects have a script named “0 Setup”. What is it for?',
    options: ['It runs for every user request', 'The developer runs it to set the object\'s own feature values (build-time configuration)', 'It uninstalls the module', 'It is the OUnit runner'], answer: 1,
    explain: '0 Setup is a convention for (re)writing an object\'s features, such as a prototype list, when building — not run-time code.' },
  { id: 'dev-q-oscript-025', domain: 'dev-oscript', guide: 'dev-oscript-objects',
    q: 'An override of a parent script must still perform the parent\'s logic and then add one step. What should the developer do?',
    options: ['Copy the parent\'s code into the override', 'Call the parent\'s implementation from the override, then add the step', 'Edit the parent', 'Delete the override'], answer: 1,
    explain: 'Overriding replaces the parent\'s script. Calling the parent implementation keeps your code correct when the parent changes; copied code goes stale after an update.' },

  // --- features, subsystems, initialization
  { id: 'dev-q-oscript-026', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'A developer adds a new request handler, builds and loads the OSpace and restarts, but func=acme.report is still unknown. Which feature should be checked first?',
    options: ['fEnabled', 'fHTMLMimeType', 'fExtraHeaders', 'fError'], answer: 0,
    explain: 'Registries only collect children whose fEnabled is TRUE. Delivered parents ship with FALSE, so a child that forgets to set it is never registered.' },
  { id: 'dev-q-oscript-027', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'When are request handlers, node types and callbacks registered in their subsystems?',
    options: ['At each request', 'When Content Server starts and loads the OSpaces', 'When the user signs in', 'Only when an administrator clicks Register'], answer: 1,
    explain: 'Subsystems scan their parent objects\' enabled children at start-up. This is why new objects need a restart.' },
  { id: 'dev-q-oscript-028', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'Which call returns the LLNode registered for documents?',
    options: ['`$LLIAPI.LLNodeSubsystem.GetItem( $TypeDocument )`', '`DAPI.GetNodeByID( 144 )`', '`$WebNode.GetDocument()`', '`CAPI.Exec( "LLNode 144" )`'], answer: 0,
    explain: 'Node types are registered in the LLNode subsystem keyed by subtype; GetItem returns the registered object. $TypeDocument is the global constant for 144.' },
  { id: 'dev-q-oscript-029', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'Which two checks belong on the list when a new item type does not appear in Add Item? (Choose two.)',
    options: ['fEnabled is TRUE on the LLNode and WebNode orphans', 'The server was restarted after the OSpace was loaded', 'The user\'s browser cache was cleared', 'The search index was rebuilt', 'A LiveReport was created'], answer: [0, 1],
    explain: 'Registration needs fEnabled TRUE and happens at start-up. Browser caches and the search index have nothing to do with the registry.' },
  { id: 'dev-q-oscript-030', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'Nightly clean-up work should not run inside a user\'s request. Where does it belong?',
    options: ['In a WebLingo page', 'In an agent run on a schedule by the server', 'In a LiveReport', 'In the module ini file'], answer: 1,
    explain: 'Agents are objects registered with the agent framework and run on schedules outside user requests.' },
  { id: 'dev-q-oscript-031', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'What should start-up (initialisation) code of an OSpace avoid?',
    options: ['Publishing globals', 'Long-running work and database writes', 'Reading constants', 'Being short'], answer: 1,
    explain: 'Initialisation runs whenever the OSpace loads, on every start. Keep it short — set up globals and lookups — and leave real work to handlers or agents.' },
  { id: 'dev-q-oscript-032', domain: 'dev-oscript', guide: 'dev-features-init',
    q: 'What does a name starting with $ refer to in OScript?',
    options: ['A local variable', 'A global, such as an OSpace\'s Globals object or a constant like $TypeFolder', 'A SQL parameter', 'A WebLingo output'], answer: 1,
    explain: '$ names are globals: OSpace globals ($LLIAPI, $WebNode) and constants ($TypeFolder, $TypeDocument).' },

  // --- CSIDE and modules
  { id: 'dev-q-oscript-033', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'What is CSIDE?',
    options: ['A Content Server plug-in for Eclipse used to write, build and debug OScript', 'A command-line SQL tool', 'The Smart View UI SDK', 'A SOAP testing tool'], answer: 0,
    explain: 'CSIDE (Content Server IDE) is the Eclipse-based environment that replaced the older Builder for module development.' },
  { id: 'dev-q-oscript-034', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'Which Content Server should CSIDE be attached to?',
    options: ['Production, so changes are live immediately', 'A development server of the same release, with its own database', 'Any server of any release', 'The OTDS server'], answer: 1,
    explain: 'CSIDE builds, loads and restarts the server it manages. Use a private development instance matching the production release.' },
  { id: 'dev-q-oscript-035', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'Which two folders are part of a typical built module? (Choose two.)',
    options: ['ospace — compiled OSpace files', 'html — WebLingo templates', 'dtree — node rows', 'otds — user partitions', 'recyclebin — deleted items'], answer: [0, 1],
    explain: 'A module folder holds its ini file, the ospace folder, html for WebLingo and support for static files (and optionally help).' },
  { id: 'dev-q-oscript-036', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'What does the support folder of a module contain?',
    options: ['OScript sources', 'Static files such as images, CSS and JavaScript served by the web server', 'SQL scripts only', 'The module licence'], answer: 1,
    explain: 'support holds static files the web server serves directly; WebLingo files go in html.' },
  { id: 'dev-q-oscript-037', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'What does a module folder name such as acmetools_1_2_0 encode?',
    options: ['The build date', 'The module name and its version', 'The database type', 'The number of OSpaces'], answer: 1,
    explain: 'Module folders carry their version in the name; the installer compares versions when upgrading.' },
  { id: 'dev-q-oscript-038', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'What does the module\'s ini file record? (Choose two.)',
    options: ['The module\'s identity and version', 'The modules it depends on', 'Every user\'s password', 'The list of documents it created', 'The search index location'], answer: [0, 1],
    explain: 'The ini file describes the module — name, version, OSpaces to load — and its dependencies, which the installer checks.' },
  { id: 'dev-q-oscript-039', domain: 'dev-oscript', guide: 'dev-cside',
    q: 'A developer rebuilt an OSpace in CSIDE but the server still runs the old code. What is the most likely cause?',
    options: ['The OSpace was compiled but not (re)loaded into the running server', 'The database is read-only', 'The browser blocks OScript', 'fError is set'], answer: 0,
    explain: 'Building and loading are separate steps. Reload/restart so the server uses the new OSpace; CSIDE shows loaded OSpaces with a distinct icon.' },

  // --- request handlers
  { id: 'dev-q-oscript-040', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'In the URL `…/cs.exe?func=acme.hello&objId=2000`, what does func select?',
    options: ['The database table', 'The request handler that will process the request', 'The WebLingo file directly', 'The user\'s language'], answer: 1,
    explain: 'The dispatcher looks up the registered request handler by its func name and calls it with the remaining arguments.' },
  { id: 'dev-q-oscript-041', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Which handler script contains the request\'s business logic?',
    options: ['SetPrototype', 'Execute', '0 Setup', 'HTMLPrefix'], answer: 1,
    explain: 'Execute( ctxIn, ctxOut, request ) does the work; SetPrototype describes arguments; 0 Setup configures features at build time.' },
  { id: 'dev-q-oscript-042', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'What is the purpose of a request handler\'s prototype (fPrototype)?',
    options: ['It lists the URL arguments the handler accepts, with their types and whether they are optional', 'It holds the HTML output', 'It stores the user\'s permissions', 'It defines the database connection'], answer: 0,
    explain: 'The dispatcher checks and converts arguments against the prototype before Execute runs, so r.objId arrives as an Integer.' },
  { id: 'dev-q-oscript-043', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Which two features would you set on a handler so that it renders a WebLingo page returning XML instead of HTML? (Choose two.)',
    options: ['fHTMLFile', 'fHTMLMimeType', 'fSubType', 'fEnabled = FALSE', 'fFuncPrefix on every user'], answer: [0, 1],
    explain: 'fHTMLFile names the template that produces the output and fHTMLMimeType sets the content type, e.g. text/xml. fEnabled must stay TRUE.' },

  // ================================================================ dev-oscript (2/2)
  { id: 'dev-q-oscript-044', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Where does a request handler get the user\'s session, database connection and DAPI session?',
    options: ['From the program context the framework supplies (fPrgCtx)', 'By opening a new database connection in Execute', 'From a cookie parsed in WebLingo', 'From the module ini file'], answer: 0,
    explain: 'The framework gives each handler a program context; prgCtx.DapiSess() and prgCtx.fDBConnect come from it. Do not create your own connections.' },
  { id: 'dev-q-oscript-045', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'A handler must make the browser save its output as report.xml. Which feature does a community example set in Execute?',
    options: ['fExtraHeaders with a Content-Disposition header', 'fPrototype', 'fEnabled', 'fSubType'], answer: 0,
    explain: 'fExtraHeaders adds HTTP headers to the response; Content-Disposition: attachment;filename=… makes the browser download the file.' },
  { id: 'dev-q-oscript-046', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Which two practices are recommended for request handlers? (Choose two.)',
    options: ['Gather all data in Execute and let WebLingo only display it', 'Rely on the APIs that honour the user\'s permissions instead of trusting objId from the URL', 'Run SQL from WebLingo for speed', 'Store per-user state in permanent features', 'Accept state-changing requests by GET without any token'], answer: [0, 1],
    explain: 'Execute is the controller and WebLingo the view; DAPI/LLNode calls run as the user. SQL in templates, shared state and unprotected state-changing GETs are anti-patterns.' },
  { id: 'dev-q-oscript-047', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'The classic URL `?func=ll&objId=2000&objAction=browse` is handled how?',
    options: ['By a request handler named ll that passes the action to the node type\'s WebNode', 'Directly by the database', 'By the REST API', 'By OTDS'], answer: 0,
    explain: 'll is itself a request handler; it looks up the node and dispatches objAction to the WebNode registered for its subtype.' },
  { id: 'dev-q-oscript-048', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Execute finds that the requested item does not exist. How should it report this?',
    options: ['Set the handler\'s error feature (fError) so the standard error page is shown', 'Echo the message and continue', 'Return HTTP 200 with an empty page', 'Delete the handler'], answer: 0,
    explain: 'Setting the handler\'s error lets the framework render its standard error page instead of the template.' },
  { id: 'dev-q-oscript-049', domain: 'dev-oscript', guide: 'dev-request-handlers',
    q: 'Read this code: `function Dynamic Execute( Dynamic ctxIn, Dynamic ctxOut, Record r )` … `.fNode = DAPI.GetNodeByID( .fPrgCtx.DapiSess(), DAPI.BY_DATAID, r.objId )`. What will the WebLingo page most likely use?',
    options: ['`.fNode` to display the node', 'A new SQL query', 'r.objId only', 'The REST API'], answer: 0,
    explain: 'Execute stores the node in a feature of the handler; the page runs in the handler\'s context and reads .fNode (e.g. `node.pName`).' },

  // --- WebLingo
  { id: 'dev-q-oscript-050', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'In a WebLingo file, what does the line `;if IsDefined( node )` represent?',
    options: ['An HTML comment', 'An OScript statement embedded in the page', 'A localisation key', 'A CSS rule'], answer: 1,
    explain: 'A line starting with ; is OScript. The if block continues until a `;end` line.' },
  { id: 'dev-q-oscript-051', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'How do you write the value of `node.pName` into a WebLingo page?',
    options: ['`<%= node.pName %>`', 'Between backticks: `` `node.pName` ``', '`{{node.pName}}`', '`$node.pName`'], answer: 1,
    explain: 'WebLingo writes the value of an expression enclosed in backticks into the output.' },
  { id: 'dev-q-oscript-052', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'Which directive includes another WebLingo file and passes it arguments?',
    options: ['`;;call <file>( args )`', '`#include file`', '`;import file`', '`<weblingo src="file">`'], answer: 0,
    explain: ';;call runs another WebLingo file (often built with .HTMLPrefix() or .ModHTMLPrefix()) with arguments. Stock pages assemble mastheads and menus this way.' },
  { id: 'dev-q-oscript-053', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'A developer wants a webscript called with ;;call to return a RecArray to the calling page. What is the problem?',
    options: ['Webscripts behave like procedures: they write output and do not return values', 'RecArrays cannot exist in WebLingo', 'All webscripts must return Strings', 'Nothing — that is the normal pattern'], answer: 0,
    explain: 'Webscripts produce output; they do not return data. Gather the data in the handler before the page runs.' },
  { id: 'dev-q-oscript-054', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'Inside backticks, what does a bracketed key such as `[WebWork_HTMLLabel.ReturnButtonLabel]` produce?',
    options: ['The localised string for the user\'s language', 'A database lookup', 'A link to the WebWork module', 'An error unless escaped'], answer: 0,
    explain: 'Bracketed keys resolve to localised (xlate) strings, so pages can be translated without changing the template.' },
  { id: 'dev-q-oscript-055', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'Which two statements about the %L prefix in WebLingo output are correct? (Choose two.)',
    options: ['`` `%Lvalue` `` writes the value literally', 'It should be used only for values you built and trust, such as a URL', 'It is required for every value', 'It escapes HTML twice', 'It translates the value'], answer: [0, 1],
    explain: '%L writes the value literally. User-supplied text must be written escaped, so reserve %L for values you constructed yourself.' },
  { id: 'dev-q-oscript-056', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'In a WebLingo page, `.HTMLPrefix()` and `.Img()` are called with a leading dot. Why does that work?',
    options: ['The page runs in the context of the request handler, so its features and scripts are reachable', 'They are JavaScript functions', 'They are SQL functions', 'The dot is ignored'], answer: 0,
    explain: 'WebLingo executes with the handler as this; .HTMLPrefix() gives the html folder location and .Img() the support URL.' },
  { id: 'dev-q-oscript-057', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'A customer wants to change a stock Classic UI page. Which approach is most upgrade-safe?',
    options: ['Edit the delivered .html in place', 'Provide the change from your own module (own handler/page or a supported override) and re-check after upgrades', 'Change the database', 'Disable WebLingo'], answer: 1,
    explain: 'In-place edits are overwritten by updates. Keep changes in your module and compare with the new stock file after every upgrade.' },
  { id: 'dev-q-oscript-058', domain: 'dev-oscript', guide: 'dev-weblingo',
    q: 'Which UI does NOT use WebLingo templates?',
    options: ['Classic UI', 'Smart View', 'The Classic Functions menu', 'The Classic properties pages'], answer: 1,
    explain: 'Smart View is a JavaScript application built on the REST API (and its UI SDK). WebLingo renders the Classic UI.' },

  // --- nodes and callbacks
  { id: 'dev-q-oscript-059', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'Which object implements what happens when a node of a given subtype is copied, moved or deleted?',
    options: ['WebNode', 'LLNode', 'CSNode', 'The WebLingo template'], answer: 1,
    explain: 'LLNode holds the data-side behaviour. Every UI and API ends up calling it, so rules enforced there apply everywhere.' },
  { id: 'dev-q-oscript-060', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'Which object controls how a node type appears in the Classic UI — icon, Add Item entry, Functions menu commands?',
    options: ['LLNode', 'WebNode', 'DAPINODE', 'KUAF'], answer: 1,
    explain: 'WebNode is the Classic UI side, registered in $WebNode.WebNodes by subtype.' },
  { id: 'dev-q-oscript-061', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'What is a CSNode?',
    options: ['A cluster node', 'A wrapper around LLNode that exposes a node type\'s properties and actions to REST v2 and Smart View', 'A SQL view', 'A WebLingo fragment'], answer: 1,
    explain: 'The REST layer is thin and routes most node requests to CSNode, which wraps LLNode.' },
  { id: 'dev-q-oscript-062', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'Which two objects does a new item type need at minimum to be created and shown in the Classic UI? (Choose two.)',
    options: ['An LLNode orphan with its subtype', 'A WebNode orphan with the same subtype', 'A LiveReport', 'A new KUAF row', 'An OTDS resource'], answer: [0, 1],
    explain: 'LLNode provides the behaviour and WebNode the Classic presentation, both keyed by the same subtype. CSNode support is added for REST v2 and Smart View.' },
  { id: 'dev-q-oscript-063', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'A rule must run whenever ANY item is moved into a records folder, whatever its type. What is the best mechanism?',
    options: ['Subclass every LLNode', 'A callback registered with the node callback framework', 'A LiveReport run nightly', 'A WebLingo change on the Move page'], answer: 1,
    explain: 'Callbacks are called for operations on all nodes, so one object covers every type and every UI or API. A UI-only check is bypassed by REST.' },
  { id: 'dev-q-oscript-064', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'A node read with DAPI.GetNodeByID is a DAPINODE. How are its fields named?',
    options: ['With a p prefix, e.g. pID, pName, pSubType, pParentID', 'In upper case, e.g. DATAID', 'With an f prefix, e.g. fName', 'As numbers only'], answer: 0,
    explain: 'DAPINODE fields start with p. Change nodes through LLNode methods rather than by assigning these fields.' },
  { id: 'dev-q-oscript-065', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'Which two statements about callbacks are true? (Choose two.)',
    options: ['They run inside matching operations of every user, so they must be fast', 'A callback that reports failure can block the operation', 'They only run in the Classic UI', 'They replace the need for fEnabled', 'They run once a day'], answer: [0, 1],
    explain: 'Callbacks run in-line for every matching operation, through every UI and API; a veto-style callback can stop the operation. They are registered like other objects (fEnabled TRUE).' },
  { id: 'dev-q-oscript-066', domain: 'dev-oscript', guide: 'dev-nodes',
    q: 'Why should a custom subtype number be reserved rather than picked at random?',
    options: ['Subtypes must be unique across OpenText and other installed modules', 'Random numbers are slower', 'Subtypes must be negative', 'The database rejects numbers above 1000'], answer: 0,
    explain: 'The subtype is the registry key for LLNode, WebNode and CSNode. A clash with another module makes one type replace the other.' },

  // --- database access
  { id: 'dev-q-oscript-067', domain: 'dev-oscript', guide: 'dev-database',
    q: 'Complete the safe query: `CAPI.Exec( prgCtx.fDBConnect.fConnection, "SELECT Name FROM DTree WHERE DataID = ___", id )`',
    options: [':A1', '%1', '?id', '" + id + "'], answer: 0,
    explain: 'CAPI binds extra arguments to :A1, :A2… in order. %1 is LiveReport syntax; concatenation invites SQL injection.' },
  { id: 'dev-q-oscript-068', domain: 'dev-oscript', guide: 'dev-database',
    q: 'Which two are benefits of bind variables in CAPI.Exec? (Choose two.)',
    options: ['They prevent SQL injection', 'They handle quoting and data types such as dates', 'They bypass permissions', 'They make SQL portable across all vendor functions', 'They commit the transaction'], answer: [0, 1],
    explain: 'Binding keeps user input out of the SQL text and handles types. It does not change permissions or vendor-specific syntax.' },
  { id: 'dev-q-oscript-069', domain: 'dev-oscript', guide: 'dev-database',
    q: 'Two INSERTs into a module table must succeed or fail together. What should the code do?',
    options: ['Run them in one transaction: start, execute both, end with commit or rollback depending on success', 'Run them in two different threads', 'Use a LiveReport', 'Insert into DTree instead'], answer: 0,
    explain: 'The connection object provides start/end transaction methods (StartTrans / EndTrans( ok ) in delivered code). Keep transactions short.' },
  { id: 'dev-q-oscript-070', domain: 'dev-oscript', guide: 'dev-database',
    q: 'Which approach should a module use to store its own data?',
    options: ['Add columns to DTree', 'Create its own tables with a module prefix from its installation code', 'Write into KUAF.UserData', 'Store it in WebLingo files'], answer: 1,
    explain: 'Modules own prefixed tables, created per supported database by install/upgrade code, and never modify core tables.' },
  { id: 'dev-q-oscript-071', domain: 'dev-oscript', guide: 'dev-database',
    q: 'Which two practices keep a module\'s custom table consistent with the repository? (Choose two.)',
    options: ['Store DataIDs rather than names or paths', 'Remove or flag rows when the referenced node is deleted (callback or agent)', 'Store full paths and update them nightly by hand', 'Never index the table', 'Copy DTree into it daily'], answer: [0, 1],
    explain: 'IDs never change while names and paths do; deleted nodes leave orphan rows unless something cleans them up.' },
  { id: 'dev-q-oscript-072', domain: 'dev-oscript', guide: 'dev-database',
    q: 'When should you use DAPI/LLNode rather than CAPI.Exec?',
    options: ['For anything that creates or changes nodes, so permissions, audit and callbacks apply', 'Never; CAPI is always preferred', 'Only for reading KUAF', 'Only in WebLingo'], answer: 0,
    explain: 'DAPI and LLNode work at node level with the user\'s session. CAPI runs raw SQL — fine for reads and your own tables.' },
  { id: 'dev-q-oscript-073', domain: 'dev-oscript', guide: 'dev-database',
    q: 'What does `DAPI.GetNodeByID( prgCtx.DapiSess(), DAPI.BY_DATAID, 2000 )` return if the node cannot be read?',
    options: ['An Error value — test it with IsError()', 'An empty string', 'The Enterprise Workspace always', 'A RecArray with no rows'], answer: 0,
    explain: 'DAPI calls return an Error on failure; always check IsError() before reading fields.' },

  // --- OUnit
  { id: 'dev-q-oscript-074', domain: 'dev-oscript', guide: 'dev-ounit',
    q: 'What is OUnit?',
    options: ['A unit-testing framework for OScript in the xUnit style', 'A load-testing tool for REST', 'A database monitoring tool', 'An OTDS add-on'], answer: 0,
    explain: 'OUnit brings xUnit-style test cases, set-up/tear-down and assertions to OScript; tests run inside a Content Server.' },
  { id: 'dev-q-oscript-075', domain: 'dev-oscript', guide: 'dev-ounit',
    q: 'Which two describe the role of set-up and tear-down in OUnit tests? (Choose two.)',
    options: ['Set-up prepares fixtures before each test', 'Tear-down removes what the test created so tests stay independent', 'Tear-down deploys the module', 'Set-up compiles the OSpace', 'They replace assertions'], answer: [0, 1],
    explain: 'Each test should start from a known state and leave none behind; set-up and tear-down provide that.' },
  { id: 'dev-q-oscript-076', domain: 'dev-oscript', guide: 'dev-ounit',
    q: 'Where should OUnit tests that create and delete items be run?',
    options: ['On production during business hours', 'On a development or test server', 'Only in the browser', 'Inside a LiveReport'], answer: 1,
    explain: 'Tests change data; run them where that is harmless and repeatable.' },
  { id: 'dev-q-oscript-077', domain: 'dev-oscript', guide: 'dev-ounit',
    q: 'A test passes when run alone but fails when the whole suite runs. What is the most likely cause?',
    options: ['Tests depend on each other\'s data or order', 'OUnit is randomised', 'The server is too fast', 'Assertions are case-sensitive'], answer: 0,
    explain: 'Shared fixtures or leftovers from another test break independence. Create and remove data per test.' },

  // --- debugging and profiling
  { id: 'dev-q-oscript-078', domain: 'dev-oscript', guide: 'dev-debugging',
    q: 'Which two capabilities does the CSIDE debugger provide? (Choose two.)',
    options: ['Breakpoints that stop a running script', 'Inspecting variables and stepping through code, including delivered scripts', 'Editing production data live', 'Recompiling the database', 'Automatic fixes'], answer: [0, 1],
    explain: 'CSIDE attaches to its development server: set breakpoints, inspect variables and this, step over/into and evaluate expressions.' },
  { id: 'dev-q-oscript-079', domain: 'dev-oscript', guide: 'dev-debugging',
    q: 'A page is slow and you suspect too many database calls. Which log shows each SQL statement and its duration?',
    options: ['The connect log', 'The audit trail', 'The browser console', 'The module ini file'], answer: 0,
    explain: 'Connect logs record SQL sent to the database with timings — the place to spot an N+1 pattern or a slow query.' },
  { id: 'dev-q-oscript-080', domain: 'dev-oscript', guide: 'dev-debugging',
    q: 'A loop calls DAPI.GetNodeByID once for each of 2,000 children. What is the better design?',
    options: ['One query (or call) that returns all the needed rows at once', 'Add Echo statements', 'Increase the timeout', 'Run it in WebLingo'], answer: 0,
    explain: 'The N+1 pattern multiplies round trips. Fetch the set in one statement and work in memory.' },
  { id: 'dev-q-oscript-081', domain: 'dev-oscript', guide: 'dev-debugging',
    q: 'Why should breakpoints never be used on a production server?',
    options: ['A breakpoint stops a server thread, leaving a user\'s request hanging', 'Breakpoints delete logs', 'They are illegal', 'They require OTDS'], answer: 0,
    explain: 'Debug on development or test with copied data; production users would see frozen requests.' },

  // --- deployment
  { id: 'dev-q-oscript-082', domain: 'dev-oscript', guide: 'dev-deploy',
    q: 'What is the correct order to deploy a module to a test server?',
    options: ['Copy to staging → Install Modules on the Administration pages → restart', 'Restart → copy the .oll into the database → Install', 'Edit opentext.ini → reindex → copy', 'Upload through Smart View → approve workflow'], answer: 0,
    explain: 'The installer lists modules found in staging; OSpaces load when the server restarts.' },
  { id: 'dev-q-oscript-083', domain: 'dev-oscript', guide: 'dev-deploy',
    q: 'Which two statements about uninstalling a module are correct? (Choose two.)',
    options: ['Modules that depend on it must be removed first', 'A restart is needed afterwards', 'Items it created are deleted automatically', 'It is done by deleting the ospace folder while the server runs', 'It also removes OTDS users'], answer: [0, 1],
    explain: 'Uninstall Modules enforces dependencies and needs a restart. Data created with the module stays and needs a plan.' },
  { id: 'dev-q-oscript-084', domain: 'dev-oscript', guide: 'dev-deploy',
    q: 'Version 1.1.0 of an installed module is ready. Which page installs it over 1.0.0?',
    options: ['Upgrade Modules', 'Install Modules with the old folder', 'Uninstall Modules', 'Search Administration'], answer: 0,
    explain: 'Upgrade Modules runs the module\'s upgrade code and replaces the old version; versions must increase.' },
  { id: 'dev-q-oscript-085', domain: 'dev-oscript', guide: 'dev-deploy',
    q: 'What does digitally signing a module give the administrator?',
    options: ['Proof of who published the module and that its files were not changed since signing', 'Faster OScript execution', 'Automatic upgrades', 'A licence key'], answer: 0,
    explain: 'A signature identifies the publisher and protects integrity; any change after signing invalidates it, so sign as the last build step.' },
  { id: 'dev-q-oscript-086', domain: 'dev-oscript', guide: 'dev-deploy',
    q: 'In a cluster with several Content Server instances, where must a new module be installed?',
    options: ['Only on the server that runs agents', 'On every Content Server instance, so all run the same code', 'Only on the database server', 'Only on the web server'], answer: 1,
    explain: 'All instances must load the same modules; a server without the module would behave differently for users routed to it.' },

  // ================================================================ dev-rest
  // --- fundamentals
  { id: 'dev-q-rest-001', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Which request obtains a Content Server ticket for a user name and password?',
    options: ['POST /api/v1/auth with form fields username and password', 'GET /api/v1/auth?user=…&pwd=…', 'POST /api/v2/login with JSON', 'GET /api/v1/serverinfo'], answer: 0,
    explain: 'POST /api/v1/auth returns JSON { "ticket": "…" }. Credentials never belong in a URL.' },
  { id: 'dev-q-rest-002', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Which HTTP header carries the Content Server ticket on later REST calls?',
    options: ['OTCSTicket', 'Authorization: Bearer', 'X-OT-Session', 'LLTicket'], answer: 0,
    explain: 'Send the ticket in the OTCSTicket header. Where OTDS is used, an OTDS token can be sent in an OTDSTicket header instead.' },
  { id: 'dev-q-rest-003', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Content Server returns an OTCSTicket header in a response. What should a client do with it?',
    options: ['Ignore it', 'Replace its stored ticket with the newer one', 'Sign out', 'Send both tickets on the next call'], answer: 1,
    explain: 'The server can hand back a refreshed ticket; keep the newest, as CS Academy\'s client does.' },
  { id: 'dev-q-rest-004', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'A REST client that worked for an hour now gets HTTP 401 on every call. What should it do?',
    options: ['Authenticate again to get a new ticket', 'Switch from v2 to v1', 'Retry the same request indefinitely', 'Clear the server cache'], answer: 0,
    explain: '401 means the ticket is missing or has expired. Sign in again (and keep refreshed tickets to delay expiry).' },
  { id: 'dev-q-rest-005', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'In which part of a `GET /api/v2/nodes/2000` response is the node\'s name found?',
    options: ['results.data.properties.name', 'data.name', 'node.name', 'collection.name'], answer: 0,
    explain: 'v2 wraps an element in results → data → properties. v1 answers { data: { name … } }.' },
  { id: 'dev-q-rest-006', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'In which part of a `GET /api/v1/nodes/2000` response is the node\'s name found?',
    options: ['data.name', 'results.data.properties.name', 'properties.name', 'items[0].name'], answer: 0,
    explain: 'v1 elements are { data: {…} }.' },
  { id: 'dev-q-rest-007', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Which two query parameters page through `GET /api/v2/nodes/{id}/nodes`? (Choose two.)',
    options: ['limit', 'page', 'offset', 'top', 'cursor'], answer: [0, 1],
    explain: 'limit sets the page size and page the 1-based page number. The total is reported in collection.paging.total_count.' },
  { id: 'dev-q-rest-008', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'A client needs only the id and name of 500 children. Which v2 parameter reduces the payload?',
    options: ['fields=properties{id,name}', 'expand=all', 'metadata', 'actions=delete'], answer: 0,
    explain: 'fields restricts which sections and properties come back. expand does the opposite: it inlines referenced objects.' },
  { id: 'dev-q-rest-009', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'What does the v2 `expand` parameter do, e.g. `expand=properties{owner_user_id}`?',
    options: ['Replaces the ID with the referenced object\'s details in the response', 'Adds more rows per page', 'Grants permissions', 'Downloads content'], answer: 0,
    explain: 'expand saves a second call by including the referenced member or node in the answer.' },
  { id: 'dev-q-rest-010', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Which two statements about REST v1 and v2 are true? (Choose two.)',
    options: ['Many resources exist in both versions with different response envelopes', 'Some resources, such as search and permissions, are v2 resources', 'v2 requires SOAP', 'v1 cannot authenticate', 'They use different databases'], answer: [0, 1],
    explain: 'Same server and data, different envelopes; newer resources such as /api/v2/search, /api/v2/nodes/{id}/permissions and /api/v2/members/assignments are v2.' },
  { id: 'dev-q-rest-011', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'A call to `/api/v1/nodes/2000` returns an HTML login page instead of JSON. What is the most likely cause?',
    options: ['The base URL is wrong or a proxy intercepted the call', 'Node 2000 is a folder', 'The ticket is too long', 'v1 is disabled for folders'], answer: 0,
    explain: 'The REST API always answers JSON. HTML means the request reached something else — check the base URL (ending in cs.exe, llisapi.dll or /cs).' },
  { id: 'dev-q-rest-012', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Where is the REST API found relative to the Classic UI URL `https://cs.example.com/otcs/cs.exe?func=llworkspace`?',
    options: ['https://cs.example.com/otcs/cs.exe/api/v1/…', 'https://cs.example.com/api/rest/…', 'https://cs.example.com/otcs/rest.exe/…', 'https://cs.example.com:2099/api/…'], answer: 0,
    explain: 'REST lives under the same gateway path, before ?func=: …/cs.exe/api/v1 and …/api/v2.' },
  { id: 'dev-q-rest-013', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'A GET for a node that does not exist or is out of the user\'s reach typically returns which answer?',
    options: ['HTTP 400 (404 on some installations) with an error such as “Could not get a node for …”', 'HTTP 200 with an empty object', 'HTTP 302 to the home page', 'HTTP 418'], answer: 0,
    explain: 'Error responses are JSON with an error string; for missing nodes the status is commonly 400 (sometimes 404).' },
  { id: 'dev-q-rest-014', domain: 'dev-rest', guide: 'dev-rest-fundamentals',
    q: 'Which two practices are correct for a REST client? (Choose two.)',
    options: ['Show the JSON error text from failed calls', 'Send credentials only to POST /api/v1/auth, never in URLs', 'Store the user\'s password in local storage for re-login', 'Ignore HTTP status codes', 'Put the ticket in the query string'], answer: [0, 1],
    explain: 'The error text is precise and helps users; credentials and tickets never belong in URLs, logs or browser storage.' },

  // --- recipes
  { id: 'dev-q-rest-015', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which request creates a folder named “Q3” under node 2000?',
    options: ['POST /api/v1/nodes with type=0, parent_id=2000, name=Q3', 'PUT /api/v1/nodes/2000 with name=Q3', 'GET /api/v1/nodes/2000/create?name=Q3', 'POST /api/v1/folders/2000'], answer: 0,
    explain: 'Nodes are created by POST /api/v1/nodes with the subtype (0 = folder), the parent and the name. PUT on an existing node updates it.' },
  { id: 'dev-q-rest-016', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which two are required to upload a new document with POST /api/v1/nodes? (Choose two.)',
    options: ['multipart/form-data encoding', 'A part named file containing the bytes', 'A JSON body with a local file path', 'A SOAP envelope', 'A version number'], answer: [0, 1],
    explain: 'Uploads are multipart: type=144, parent_id, name and a file part with the actual content. Sending a path as text fails with an upload-directory error.' },
  { id: 'dev-q-rest-017', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'An upload sent as application/x-www-form-urlencoded fails with “Could not get parent”. What is the fix?',
    options: ['Send the request as multipart/form-data with a file part', 'Use parent_id=-1', 'Use GET', 'Add the ticket twice'], answer: 0,
    explain: 'Forum reports show this error when the form is URL-encoded instead of multipart.' },
  { id: 'dev-q-rest-018', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which request adds a new version to document 123456?',
    options: ['POST /api/v1/nodes/123456/versions with a file part', 'PUT /api/v1/nodes/123456 with version=2', 'POST /api/v1/nodes with original_id=123456', 'GET /api/v1/nodes/123456/content'], answer: 0,
    explain: 'Versions are a sub-resource: POST adds one, GET lists them. original_id on POST /nodes makes a copy.' },
  { id: 'dev-q-rest-019', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which request downloads the current content of document 123456?',
    options: ['GET /api/v1/nodes/123456/content', 'GET /api/v1/nodes/123456/download.json', 'POST /api/v1/content', 'GET /api/v2/search?id=123456'], answer: 0,
    explain: 'GET …/content returns the bytes of the current version.' },
  { id: 'dev-q-rest-020', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'How is a node moved to another folder through REST?',
    options: ['PUT /api/v1/nodes/{id} with a new parent_id', 'DELETE then POST with the same id', 'POST /api/v1/nodes/{id}/move with SOAP', 'It cannot be done through REST'], answer: 0,
    explain: 'Updating parent_id on the node moves it; name and description are updated the same way.' },
  { id: 'dev-q-rest-021', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which request copies node 123456 into folder 4567?',
    options: ['POST /api/v1/nodes with original_id=123456 and parent_id=4567', 'PUT /api/v1/nodes/4567 with child=123456', 'GET /api/v1/nodes/123456/copy', 'POST /api/v1/copy/123456/4567'], answer: 0,
    explain: 'Creating a node with original_id copies the original into the given parent.' },
  { id: 'dev-q-rest-022', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Category attribute values in REST requests and v2 answers are keyed how?',
    options: ['{categoryId}_{attributeId}, e.g. 51234_2', 'By attribute display name only', 'By a GUID', 'By column position'], answer: 0,
    explain: 'Keys combine the category\'s node ID and the attribute ID, e.g. 51234_2 for attribute 2 of category 51234.' },
  { id: 'dev-q-rest-023', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which two calls are involved in applying a category to a document and then setting one of its attributes? (Choose two.)',
    options: ['POST /api/v1/nodes/{id}/categories with category_id', 'PUT /api/v1/nodes/{id}/categories/{category_id} with the attribute key and value', 'DELETE /api/v1/nodes/{id}', 'GET /api/v1/serverinfo', 'POST /api/v1/auth with category_id'], answer: [0, 1],
    explain: 'Apply the category with POST on the categories sub-resource, then update values with PUT on that category.' },
  { id: 'dev-q-rest-024', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'A client must give group 1001 See and See Contents on a node. Which resource is used?',
    options: ['POST /api/v2/nodes/{id}/permissions/custom with right_id 1001 and the permission list', 'PUT /api/v1/members/1001', 'POST /api/v1/auth', 'GET /api/v2/search'], answer: 0,
    explain: 'Assigned access entries are added on the v2 permissions/custom sub-resource with right_id and permissions such as see and see_contents.' },
  { id: 'dev-q-rest-025', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which two permission keywords are valid in the v2 permissions API? (Choose two.)',
    options: ['see_contents', 'edit_permissions', 'read_all', 'super_user', 'owner_only'], answer: [0, 1],
    explain: 'v2 uses lower-case keywords: see, see_contents, modify, edit_attributes, add_items, reserve, add_major_version, delete_versions, delete, edit_permissions.' },
  { id: 'dev-q-rest-026', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which endpoint runs a full-text search?',
    options: ['/api/v2/search with a where parameter', '/api/v1/nodes?q=…', '/api/v2/members?query=…', '/api/v1/searchindex'], answer: 0,
    explain: '/api/v2/search takes the query in where, plus paging parameters. /api/v2/members?query= searches users and groups, not content.' },
  { id: 'dev-q-rest-027', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which request returns the groups whose names match “finance”?',
    options: ['GET /api/v2/members?where_type=1&query=finance', 'GET /api/v2/search?where=finance', 'GET /api/v1/groups/finance', 'GET /api/v2/members/finance/members'], answer: 0,
    explain: 'Members are searched on /api/v2/members; where_type=1 restricts to groups (0 = users).' },
  { id: 'dev-q-rest-028', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'How can a client find the ID and name of the signed-in user?',
    options: ['GET /api/v1/auth with the ticket', 'GET /api/v1/serverinfo', 'Decode the ticket', 'GET /api/v2/search?where=me'], answer: 0,
    explain: 'GET /api/v1/auth with a valid ticket returns the current user\'s details; CS Academy uses it to read your user ID and log-in name.' },
  { id: 'dev-q-rest-029', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which two requests return information about the signed-in user\'s own work and membership? (Choose two.)',
    options: ['GET /api/v2/members/assignments', 'GET /api/v2/members/memberof', 'GET /api/v1/volumes/141', 'GET /api/v1/nodes/2000/content', 'GET /api/v1/serverinfo'], answer: [0, 1],
    explain: 'assignments lists the user\'s assignments and memberof the groups the user belongs to. Volume 141 is the Enterprise Workspace.' },
  { id: 'dev-q-rest-030', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Before creating an item, a client wants to know which item types the user may add to folder 2000. Which call answers this?',
    options: ['GET /api/v1/nodes/2000/addablenodetypes', 'GET /api/v1/nodes/2000/permissions/types', 'GET /api/v2/types', 'OPTIONS /api/v1/nodes/2000'], answer: 0,
    explain: 'addablenodetypes lists the subtypes the user can create in that container.' },
  { id: 'dev-q-rest-031', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'In browser JavaScript, a FormData upload fails because the developer set `Content-Type: multipart/form-data` manually. Why?',
    options: ['The manual header lacks the boundary the browser would add', 'Content Server rejects multipart', 'FormData cannot hold files', 'The ticket must be in the body'], answer: 0,
    explain: 'Let fetch set Content-Type for FormData so the boundary is included.' },
  { id: 'dev-q-rest-032', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'How do you send a structured value (for example a permissions object) in a form-encoded REST request?',
    options: ['As a JSON string in a form field named body', 'As XML in the URL', 'As separate headers', 'It is impossible'], answer: 0,
    explain: 'Content Server accepts a body form field containing JSON for structured parameters.' },
  { id: 'dev-q-rest-033', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'In Postman, what is the most practical way to reuse the ticket across requests?',
    options: ['Save it from the auth response into an environment variable and send OTCSTicket: {{ticket}}', 'Copy it into every URL', 'Disable authentication', 'Use Basic auth on every call'], answer: 0,
    explain: 'A test script on the auth request stores the ticket; other requests reference the variable in their header.' },
  { id: 'dev-q-rest-034', domain: 'dev-rest', guide: 'dev-rest-recipes',
    q: 'Which two requests are read-only? (Choose two.)',
    options: ['GET /api/v1/nodes/{id}/versions', 'GET /api/v2/nodes/{id}/permissions', 'DELETE /api/v1/nodes/{id}', 'POST /api/v1/nodes', 'PUT /api/v1/nodes/{id}'], answer: [0, 1],
    explain: 'GET reads; POST creates, PUT updates, DELETE removes. CS Academy\'s client only ever uses POST for /api/v1/auth and GET for everything else.' },

  // --- extending REST
  { id: 'dev-q-rest-035', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'In which language are custom REST API resources for Content Server written?',
    options: ['OScript, in a module', 'Java servlets only', 'PL/SQL', 'C# only'], answer: 0,
    explain: 'The REST framework is OScript; custom resources are OScript objects in your module that it routes URLs to.' },
  { id: 'dev-q-rest-036', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'Which two statements about custom REST resources are true? (Choose two.)',
    options: ['They should be stateless: each call carries its ticket and parameters', 'They can be added to both v1 and v2', 'They must be written in WebLingo', 'They bypass authentication', 'They require CWS'], answer: [0, 1],
    explain: 'The 4-0144 course extends both API versions with a stateless custom resource; the framework authenticates the call before your function runs.' },
  { id: 'dev-q-rest-037', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'A module defines a new node type that must appear in Smart View and work with GET /api/v2/nodes/{id}. What is the recommended approach?',
    options: ['Provide CSNode support for the type', 'Write a parallel set of /api/v2/acme/… URLs', 'Use a LiveReport', 'Modify the delivered REST OSpace'], answer: 0,
    explain: 'The REST layer maps node requests to CSNode; supporting it makes the standard endpoints and Smart View work.' },
  { id: 'dev-q-rest-038', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'A custom REST resource counts documents with raw SQL and returns the count to any user. What is the risk?',
    options: ['It ignores permissions and may reveal information users should not see', 'SQL cannot count', 'REST cannot return numbers', 'There is no risk'], answer: 0,
    explain: 'Raw SQL is not permission-filtered. Use DAPI/LLNode (which run as the user) or filter with DTreeACL.' },
  { id: 'dev-q-rest-039', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'Which two are good design rules for custom REST endpoints? (Choose two.)',
    options: ['Return JSON errors with an error string and a matching HTTP status', 'Support limit and page for potentially large lists', 'Use GET for operations that delete data', 'Return HTML error pages', 'Store session state on the server between calls'], answer: [0, 1],
    explain: 'Behave like the built-in resources: JSON errors, proper status codes, paging, HTTP verbs that match the action, statelessness.' },
  { id: 'dev-q-rest-040', domain: 'dev-rest', guide: 'dev-rest-extend',
    q: 'Before writing a custom resource for an action on an existing node type, what should you check first?',
    options: ['Whether the CSNode already provides the action so only a mapping is needed', 'Whether WebLingo supports it', 'Whether a LiveReport exists', 'Whether OTDS is installed'], answer: 0,
    explain: 'Community guidance: the REST layer is thin and any CSNode action can be exposed, at most with a mapping.' },

  // --- CWS
  { id: 'dev-q-rest-041', domain: 'dev-rest', guide: 'dev-cws',
    q: 'What are Content Web Services?',
    options: ['SOAP web services for Content Server, described by WSDL', 'The JSON REST API', 'A Smart View widget library', 'A database replication tool'], answer: 0,
    explain: 'CWS exposes Content Server through SOAP; clients generate typed proxies from each service\'s WSDL.' },
  { id: 'dev-q-rest-042', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Which CWS operation exchanges a user name and password for a token?',
    options: ['Authentication.AuthenticateUser', 'DocumentManagement.GetNode', 'MemberService.GetMember', 'ContentService.Download'], answer: 0,
    explain: 'AuthenticateUser on the Authentication service returns the token used on later calls.' },
  { id: 'dev-q-rest-043', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Where is the CWS authentication token sent on calls to DocumentManagement?',
    options: ['In the OTAuthentication SOAP header, element AuthenticationToken', 'In an OTCSTicket HTTP header', 'In the URL', 'In every operation\'s ID parameter'], answer: 0,
    explain: 'The token goes in the OTAuthentication header (namespace urn:api.ecm.opentext.com). “No valid token set for this call” usually means it was not placed there.' },
  { id: 'dev-q-rest-044', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Which two steps does OpenText\'s sample use to call CWS with OTDS single sign-on? (Choose two.)',
    options: ['Authenticate against OTDS to get an OTDS token', 'Call Authentication.ValidateUser with that token to get a CWS token', 'Call MemberService.CreateUser', 'Send the password in every SOAP body', 'Call the REST API first'], answer: [0, 1],
    explain: 'The OTDS token is validated by the CWS Authentication service, which returns the token for the OTAuthentication header.' },
  { id: 'dev-q-rest-045', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Which CWS service provides GetNode, ListNodes and CreateFolder?',
    options: ['DocumentManagement', 'Authentication', 'SearchService', 'MemberService'], answer: 0,
    explain: 'DocumentManagement handles nodes, versions, categories and related operations.' },
  { id: 'dev-q-rest-046', domain: 'dev-rest', guide: 'dev-cws',
    q: 'An integration uploads 2 GB video files through CWS. Which service should carry the content?',
    options: ['ContentService, streaming the bytes for a context ID', 'Authentication', 'An attachment inside every SOAP envelope', 'MemberService'], answer: 0,
    explain: 'ContentService streams large content for a context created through DocumentManagement, keeping big payloads out of the XML.' },
  { id: 'dev-q-rest-047', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Which service would you use to look up a user by log-in name in CWS?',
    options: ['MemberService', 'DocumentManagement', 'ContentService', 'Authentication'], answer: 0,
    explain: 'MemberService covers users and groups.' },
  { id: 'dev-q-rest-048', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Which two tools or steps are typical for a Java or .NET CWS client? (Choose two.)',
    options: ['Generate proxies from the WSDL (wsimport, service reference)', 'Test operations in SoapUI before coding', 'Parse JSON responses manually', 'Send the OTCSTicket header', 'Write WebLingo'], answer: [0, 1],
    explain: 'Proxies give typed classes for Node, Version and so on; SoapUI lets you explore operations without code.' },
  { id: 'dev-q-rest-049', domain: 'dev-rest', guide: 'dev-cws',
    q: 'A .NET client sets the token on an OTAuthentication object but gets “No valid token set for this call”. What should be checked first?',
    options: ['That the OTAuthentication object is actually passed as the SOAP header of the call', 'That the database is online', 'That the user has a favourite', 'That REST v2 is enabled'], answer: 0,
    explain: 'The token must travel in the outbound header; setting it on an object that is not sent has no effect.' },
  { id: 'dev-q-rest-050', domain: 'dev-rest', guide: 'dev-cws',
    q: 'Where is the WSDL of the DocumentManagement service on a Java (Tomcat) CWS deployment typically found?',
    options: ['…/cws/services/DocumentManagement?wsdl', '…/cs.exe/api/v1/wsdl', '…/otds/DocumentManagement', '…/cs.exe?func=wsdl'], answer: 0,
    explain: 'OpenText\'s samples point at /cws/services/<Service>?wsdl. The .NET edition is hosted under IIS with its own paths.' },

  // --- custom CWS and SDOs
  { id: 'dev-q-rest-051', domain: 'dev-rest', guide: 'dev-cws-custom',
    q: 'What is a Service Data Object (SDO) in Content Web Services?',
    options: ['A strongly typed data structure that a service accepts or returns', 'A database table', 'A REST ticket', 'A WebLingo fragment'], answer: 0,
    explain: 'SDOs have named, typed fields, so the WSDL describes them exactly and clients get generated classes.' },
  { id: 'dev-q-rest-052', domain: 'dev-rest', guide: 'dev-cws-custom',
    q: 'Which two are advantages of strongly typed SDOs over returning loose strings? (Choose two.)',
    options: ['Client generators create matching classes from the WSDL', 'Type errors are caught at compile time on the client', 'No authentication is needed', 'They bypass permissions', 'They need no deployment'], answer: [0, 1],
    explain: 'A typed contract is self-documenting and compiler-checked; it changes nothing about security or deployment.' },
  { id: 'dev-q-rest-053', domain: 'dev-rest', guide: 'dev-cws-custom',
    q: 'What should be designed first when building a custom Content Web Service?',
    options: ['The contract: operations, input/output SDOs and faults', 'The WebLingo page', 'The database indexes', 'The OTDS partition'], answer: 0,
    explain: 'Clients are generated from the contract; changing it later breaks them.' },
  { id: 'dev-q-rest-054', domain: 'dev-rest', guide: 'dev-cws-custom',
    q: 'Where does the business logic of a custom Content Web Service run?',
    options: ['In OScript inside Content Server, deployed as a module', 'In the client', 'In the WSDL', 'In SoapUI'], answer: 0,
    explain: 'Operations are backed by OScript in your module (calling DAPI, LLNode, CAPI); the CWS layer exposes them with a WSDL.' },
  { id: 'dev-q-rest-055', domain: 'dev-rest', guide: 'dev-choose-api',
    q: 'A JavaScript portal needs a list of the user\'s documents. Which interface is the best fit?',
    options: ['REST API', 'Content Web Services', 'A LiveReport with SQL', 'Direct database access'], answer: 0,
    explain: 'REST is browser-friendly JSON with ticket auth and runs as the user. CWS suits SOAP-based enterprise systems.' },
  { id: 'dev-q-rest-056', domain: 'dev-rest', guide: 'dev-choose-api',
    q: 'Which two scenarios favour Content Web Services over REST? (Choose two.)',
    options: ['An enterprise system that requires a WSDL contract and generated typed proxies', 'A SOAP-based integration platform already used by the company', 'A Smart View tile', 'A mobile web app in JavaScript', 'A quick browser test'], answer: [0, 1],
    explain: 'CWS fits SOAP tooling and typed contracts. Browser, mobile and Smart View work goes through REST.' },
];
