'use strict';
// Question bank — Administrator certification 5-0156. Multiple choice and
// true/false like the real exam, weighted by domain. All text original.

module.exports = [
  // ================================================================ sa-sysadmin
  { id: "sa-q-sys-001", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "Which Content Server tier performs permission checks when a user browses a folder?",
    options: ["The gateway (llisapi.dll or cs.exe)", "The Content Server engine", "The database server", "The web server"], answer: 1,
    explain: "The gateway only relays the request. The engine's worker thread runs the request handler, checks the ACLs and filters what the user may see; the database merely stores the ACL rows." },
  { id: "sa-q-sys-002", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "Content Server runs under IIS on Windows. Which gateway is typically used?",
    options: ["llisapi.dll (ISAPI)", "otds.war", "otadmin.exe", "cs.exe started per request"], answer: 0,
    explain: "llisapi.dll is the ISAPI extension that stays loaded in IIS. cs.exe is the CGI gateway; otadmin is the search Admin server, unrelated to request forwarding." },
  { id: "sa-q-sys-003", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "True or false: the web server that hosts the Content Server gateway stores document metadata.",
    options: ["True", "False"], answer: 1,
    explain: "False. Metadata is stored in the Content Server database and content in the storage provider. The web tier only forwards requests and serves static files." },
  { id: "sa-q-sys-004", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "Users see pages without icons or styles, but the content of each page is correct. What is the most likely cause?",
    options: ["The Search Federator is stopped", "OTDS rejected the user", "The database is out of space", "The web server mapping or URL for the support (/img/) directory is wrong"], answer: 3,
    explain: "Static files come from the support folder published by the web server. Correct content proves the engine and database work; only the static mapping is broken." },
  { id: "sa-q-sys-005", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "By default, on which TCP port does the Content Server engine listen for gateway requests?",
    options: ["8443", "1433", "2099", "5858"], answer: 2,
    explain: "2099 is the classic engine port. 5858 is the default for the search Admin server and 1433 is SQL Server." },
  { id: "sa-q-sys-006", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "Why can Content Server feel slow to everyone while its CPU is mostly idle?",
    options: ["Because OTDS caches tickets", "Because the fixed pool of worker threads is occupied by long requests, so new requests queue", "Because the index is in read-only mode", "Because opentext.ini is too large"], answer: 1,
    explain: "Each worker thread serves one request at a time. If slow reports or bulk actions hold all threads, other requests wait even though there is spare CPU." },
  { id: "sa-q-sys-007", domain: "sa-sysadmin", guide: "sa-install-upgrade",
    q: "Which three items does the Content Server web-based setup ask for after the binaries are installed? (Choose three.)",
    options: ["The OTSCM agent registration", "The administration password", "The database to create or connect to", "The licence", "The AD bind account"], answer: [1, 2, 3],
    explain: "The first browser visit runs setup: set the administration password, create or connect the database, apply the licence. Directory and OTSCM configuration come later and elsewhere." },
  { id: "sa-q-sys-008", domain: "sa-sysadmin", guide: "sa-install-upgrade",
    q: "Before installing Content Server on Windows with an EFS on a file share, which service-account choice is correct?",
    options: ["Run the service as the logged-on administrator", "Any account; the EFS is accessed by the web server", "Run the service as LocalSystem", "Run the service as a domain account with read/write access to the share"], answer: 3,
    explain: "The engine reads and writes the EFS itself. LocalSystem cannot authenticate to a remote share, so a domain service account with share and NTFS rights is required." },
  { id: "sa-q-sys-009", domain: "sa-sysadmin", guide: "sa-install-upgrade",
    q: "During a side-by-side upgrade, which database does the new Content Server version upgrade?",
    options: ["The OTDS database", "The production database in place", "A restored copy of the production database", "A new empty database"], answer: 2,
    explain: "Side-by-side upgrades point the new installation at a copy, leaving production untouched as the rollback. In-place updates change the live database instead." },
  { id: "sa-q-sys-010", domain: "sa-sysadmin", guide: "sa-install-upgrade",
    q: "True or false: when you upgrade the Content Server core, optional modules can stay at their old versions.",
    options: ["True", "False"], answer: 1,
    explain: "False. Modules must be at versions supported by the new core; an old module typically blocks the upgrade or fails to load. Check every module's compatibility." },
  { id: "sa-q-sys-011", domain: "sa-sysadmin", guide: "sa-install-upgrade",
    q: "Which folders should normally be excluded from on-access antivirus scanning on a Content Server host?",
    options: ["Nothing should ever be excluded", "The search index and logs folders", "The Windows system folder", "The users' Personal Workspaces"], answer: 1,
    explain: "Scanning index files while engines write them is a known cause of corruption and slowness; logs are written constantly. Coordinate any exclusion with security." },
  { id: "sa-q-sys-012", domain: "sa-sysadmin", guide: "sa-admin-pages",
    q: "Which URL opens the Content Server Administration pages?",
    options: ["…/cs.exe?func=admin.index", "…/cs.exe?func=ll&objType=admin", "…/otds-admin", "…/api/v1/admin"], answer: 0,
    explain: "admin.index is the Administration pages entry point. otds-admin is the OTDS administration client, a different application." },
  { id: "sa-q-sys-013", domain: "sa-sysadmin", guide: "sa-admin-pages",
    q: "True or false: a user with System Administration rights still has to enter the administration password to open the Administration pages.",
    options: ["True", "False"], answer: 0,
    explain: "True. The administration password is a second layer, asked once per admin session, on top of the account's privileges." },
  { id: "sa-q-sys-014", domain: "sa-sysadmin", guide: "sa-admin-pages",
    q: "Links in notification emails point to an internal host name that users cannot reach. Which setting should you correct?",
    options: ["The SMTP port", "The storage rule order", "The OTDS access role", "The base URL in the server parameters"], answer: 3,
    explain: "Emails and other generated links are built from the configured server URL. Set it to the load balancer or public name." },
  { id: "sa-q-sys-015", domain: "sa-sysadmin", guide: "sa-admin-pages",
    q: "Under which Administration pages section are storage rules configured?",
    options: ["Notification Administration", "Search Administration", "Storage Provider Settings", "Module Administration"], answer: 2,
    explain: "Storage Provider Settings holds both the providers and the ordered rules that choose one for each new version." },
  { id: "sa-q-sys-016", domain: "sa-sysadmin", guide: "sa-admin-pages",
    q: "Which Administration function should you run before an upgrade to find orphan rows and inconsistencies?",
    options: ["Resynchronize the data source", "Verify Content Server database", "Install Modules", "Purge audit log"], answer: 1,
    explain: "Database verification checks core tables for consistency problems that an upgrade could trip over." },
  { id: "sa-q-sys-017", domain: "sa-sysadmin", guide: "sa-opentext-ini",
    q: "An administrator changes a setting in opentext.ini on one instance of a cluster. What must they do for the change to take effect everywhere?",
    options: ["Restart that instance, and make the same change and restart on every other instance", "Run index verification", "Consolidate the OTDS resource", "Nothing; ini changes replicate through the database"], answer: 0,
    explain: "opentext.ini is per instance and read at start-up. Database-backed settings (such as KIni) are shared; ini settings are not." },
  { id: "sa-q-sys-018", domain: "sa-sysadmin", guide: "sa-opentext-ini",
    q: "True or false: settings stored in the KIni table apply to every instance of a cluster without editing each server.",
    options: ["True", "False"], answer: 0,
    explain: "True. KIni lives in the shared database, so every instance sees the same value. That is the key difference from opentext.ini." },
  { id: "sa-q-sys-019", domain: "sa-sysadmin", guide: "sa-opentext-ini",
    q: "After a manual edit to opentext.ini, the Content Server service no longer starts. What is the quickest safe recovery?",
    options: ["Restore the database", "Delete the logs folder", "Reinstall Content Server", "Restore the backed-up copy of opentext.ini and compare it with the edited version"], answer: 3,
    explain: "A typo in the ini can stop start-up. Restoring the previous copy brings the service back; a diff shows the mistake. Always back up the file before editing." },
  { id: "sa-q-sys-020", domain: "sa-sysadmin", guide: "sa-storage",
    q: "A storage rule is changed so that files larger than 100 MB go to a new EFS. What happens to large files added last year?",
    options: ["They become read-only", "They move to the new EFS at the next agent run", "They stay on their original provider until migrated", "They are deleted"], answer: 2,
    explain: "Storage rules are evaluated only when a version is written. Existing versions keep their provider reference until you move them with storage management tools." },
  { id: "sa-q-sys-021", domain: "sa-sysadmin", guide: "sa-storage",
    q: "Two storage rules match a new document. Which provider receives it?",
    options: ["The provider of the last matching rule", "The provider of the first matching rule in the list", "The provider with the most free space", "Both providers receive a copy"], answer: 1,
    explain: "Rules are processed top to bottom and the first match wins. Put specific rules first and the default rule last." },
  { id: "sa-q-sys-022", domain: "sa-sysadmin", guide: "sa-storage",
    q: "True or false: it is safe to rename sub-folders inside an External File Store to match business folder names.",
    options: ["True", "False"], answer: 1,
    explain: "False. The database stores each version's location reference. Renaming or moving EFS files by hand breaks those references and the documents can no longer be opened." },
  { id: "sa-q-sys-023", domain: "sa-sysadmin", guide: "sa-storage",
    q: "Which storage option is designed for compliant long-term storage with retention, compression and replication handled outside Content Server?",
    options: ["Archive Center through an archive storage provider", "The search index", "Internal database storage", "External File Store"], answer: 0,
    explain: "Archive Center manages logical archives with retention and media options. An EFS is a plain file store; internal storage puts blobs in the database." },
  { id: "sa-q-sys-024", domain: "sa-sysadmin", guide: "sa-storage",
    q: "Documents open from front-end 1 but every download fails on front-end 2. Uploads on front-end 2 also fail. What should you check first?",
    options: ["The search partition map", "The notification schedule", "The OTDS access role", "Whether front-end 2 reaches the EFS path (mapping, UNC path, service account rights)"], answer: 3,
    explain: "A failure limited to one instance points to that host. Different drive mappings or missing share rights are the classic cause; use the same UNC path everywhere." },
  { id: "sa-q-sys-025", domain: "sa-sysadmin", guide: "sa-database-backup",
    q: "Which database platforms are supported by current Content Server releases? (Choose two.)",
    options: ["Microsoft Access", "SQLite", "Microsoft SQL Server", "Oracle Database"], answer: [2, 3],
    explain: "SQL Server and Oracle are supported across releases (PostgreSQL on newer ones). Desktop and embedded databases are not supported." },
  { id: "sa-q-sys-026", domain: "sa-sysadmin", guide: "sa-database-backup",
    q: "In which order should the database and the External File Store be backed up to keep them consistent?",
    options: ["EFS first, then database", "Database first, then EFS", "Only the database is needed", "Order does not matter"], answer: 1,
    explain: "Files written after the database backup are harmless orphans. If the EFS is backed up first, rows written afterwards point to files missing from the backup." },
  { id: "sa-q-sys-027", domain: "sa-sysadmin", guide: "sa-database-backup",
    q: "True or false: the search index can always be rebuilt from the database and the content store.",
    options: ["True", "False"], answer: 0,
    explain: "True — but on large systems a full reindex can take days, so many sites also back up the index to meet their recovery-time objective." },
  { id: "sa-q-sys-028", domain: "sa-sysadmin", guide: "sa-database-backup",
    q: "A test system is built from last night's production backup. What should be done before it is started?",
    options: ["Disable notifications and agents, change SMTP, point storage and OTDS settings at test resources", "Delete all users", "Reindex the production search grid", "Nothing; it is isolated by default"], answer: 0,
    explain: "A restored copy still has real email addresses, production paths and the production OTDS resource. Isolate it before the first start." },
  { id: "sa-q-sys-029", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "Which process sends converted index data to the Index Engines?",
    options: ["Extractor", "Admin server", "Search Federator", "Update Distributor"], answer: 3,
    explain: "The Update Distributor chooses the partition for each object and hands batches to its Index Engine. The Federator distributes queries, not updates." },
  { id: "sa-q-sys-030", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "What is the correct order of the indexing data flow?",
    options: ["Extractor → Search Federator → Index Engine", "Update Distributor → Extractor → Document Conversion → Index Engine", "Extractor → Document Conversion → Update Distributor → Index Engine", "Document Conversion → Extractor → Search Engine → Index Engine"], answer: 2,
    explain: "The Extractor collects metadata and content, DCS converts files to text, the Update Distributor routes batches, the Index Engine writes the partition." },
  { id: "sa-q-sys-031", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "Which component receives a query from Content Server and merges the results of all partitions?",
    options: ["Document Conversion", "Search Federator", "Index Engine", "Update Distributor"], answer: 1,
    explain: "The Search Federator fans the query out to every Search Engine and merges their hits before Content Server applies permission filtering." },
  { id: "sa-q-sys-032", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "True or false: the Admin server indexes documents itself.",
    options: ["True", "False"], answer: 1,
    explain: "False. The Admin server (otadmin) starts, stops and monitors search processes on its host. Indexing is done by the data-flow processes and Index Engines." },
  { id: "sa-q-sys-033", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "What is an iPool in the search data flow?",
    options: ["A folder through which one search process passes numbered batches to the next", "A group of OTDS users", "A storage provider for images", "A pool of database connections"], answer: 0,
    explain: "Interchange pools connect the stages of the data flow. Counting waiting batches shows where a backlog builds up." },
  { id: "sa-q-sys-034", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "A partition is set to update-only. What does it still do?",
    options: ["Nothing; it is offline", "Only answer queries for administrators", "Accept new objects only", "Accept updates to objects it already holds and answer queries"], answer: 3,
    explain: "Update-only partitions take no new objects but keep their contents current and searchable — the usual state for a full partition." },
  { id: "sa-q-sys-035", domain: "sa-sysadmin", guide: "sa-search-architecture",
    q: "A Word document is found by its name but not by words in its text. Which process most likely failed for that file?",
    options: ["Update Distributor", "Search Federator", "Document Conversion", "Admin server"], answer: 2,
    explain: "Metadata was indexed, so the pipeline works; DCS could not extract text (encrypted, corrupt, unsupported or timed out)." },
  { id: "sa-q-sys-036", domain: "sa-sysadmin", guide: "sa-search-admin",
    q: "Where in the Classic UI do you start and stop individual search processes?",
    options: ["Enterprise Workspace ▸ Functions", "Search Administration ▸ Open the System Object Volume", "Personal Workspace ▸ Settings", "Module Administration"], answer: 1,
    explain: "Search processes are represented as objects in the System Object Volume, reached from Search Administration." },
  { id: "sa-q-sys-037", domain: "sa-sysadmin", guide: "sa-search-admin",
    q: "Indexing stopped after months of normal operation; all processes run and logs mention partitions being full. What is the standard fix?",
    options: ["Add a new partition and set the full ones to update-only", "Delete old documents", "Disable Document Conversion", "Run a full reindex"], answer: 0,
    explain: "Full partitions cannot take new objects. A new read-write partition absorbs new data; reindexing would not create capacity." },
  { id: "sa-q-sys-038", domain: "sa-sysadmin", guide: "sa-search-admin",
    q: "Many items are missing from search after the index was restored from a two-week-old backup. Which function finds and queues them most efficiently?",
    options: ["Full reindex of the data source", "Restarting the Search Federator", "Consolidating OTDS", "Index verification"], answer: 3,
    explain: "Index verification compares the database with the index and identifies missing or stale objects, which is far cheaper than a full reindex." },
  { id: "sa-q-sys-039", domain: "sa-sysadmin", guide: "sa-search-admin",
    q: "A user cannot find a document by search, but an administrator finds it immediately. What is the best first conclusion?",
    options: ["The partition is read-only", "The index is corrupt", "The item is indexed; check the user's permissions and search scope", "The Update Distributor is stopped"], answer: 2,
    explain: "Search results are filtered by permissions and slices. If an administrator finds it, the indexing pipeline worked." },
  { id: "sa-q-sys-040", domain: "sa-sysadmin", guide: "sa-agents",
    q: "Notification emails stopped after front-end servers were rebuilt. Users still see events in their settings. What should you check first?",
    options: ["The LiveReport permissions", "That at least one running instance is allowed to run agents, and that it reaches the SMTP server", "The storage rules", "The partition map"], answer: 1,
    explain: "Notifications are sent by the notification agent on the instance(s) that run agents. If none runs them, or SMTP is blocked from that host, nothing is sent." },
  { id: "sa-q-sys-041", domain: "sa-sysadmin", guide: "sa-agents",
    q: "True or false: Content Server sends a notification email immediately within the user request that triggered the event.",
    options: ["True", "False"], answer: 1,
    explain: "False. Events are recorded and the notification agent sends digests on its schedule through SMTP." },
  { id: "sa-q-sys-042", domain: "sa-sysadmin", guide: "sa-agents",
    q: "Which kind of work is handled by the Distributed Agent framework?",
    options: ["Long-running tasks such as copying or deleting large folder trees and purges", "Kerberos authentication", "Database backups", "Rendering Smart View pages"], answer: 0,
    explain: "Distributed Agents split long operations into tasks processed by workers on permitted instances, so user requests return quickly." },
  { id: "sa-q-sys-043", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "Which components are shared by all instances of a Content Server cluster? (Choose two.)",
    options: ["The content store (EFS)", "opentext.ini", "The logs folder", "The database"], answer: [0, 3],
    explain: "All instances use one database and one content store (and one search grid). Each instance keeps its own opentext.ini and logs." },
  { id: "sa-q-sys-044", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "Errors appear for some users at random. Investigation shows a patch present on two front-ends but missing on the third. What is the lesson?",
    options: ["Patches must be applied through OTDS", "Patches only need to be applied to the back-end", "Every instance must run the same version, modules and patches", "Load balancers should be removed"], answer: 2,
    explain: "The load balancer spreads users across instances, so a difference on one instance looks random. Keep instances identical and verify with System Reports." },
  { id: "sa-q-sys-045", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "Which role is typically assigned to back-end instances in a Content Server cluster?",
    options: ["Serving most user traffic", "Running agents, Distributed Agent workers and search administration", "Hosting the database", "Terminating TLS"], answer: 1,
    explain: "Back-ends keep batch and administrative work away from interactive users; front-ends sit in the load-balancer pool." },
  { id: "sa-q-sys-046", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "Which tool analyses summary timing logs to identify slow request types and peak periods?",
    options: ["OpenText Performance Analyzer", "System Center Manager", "OTDS admin client", "Transport Warehouse"], answer: 0,
    explain: "Performance Analyzer (OTPA) reads summary timing logs and reports transaction times, users and thread usage." },
  { id: "sa-q-sys-047", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "A load balancer keeps sending users to an instance whose engine has stopped, because its health check only opens a TCP connection to the web server. What should be improved?",
    options: ["Increase the number of threads", "Disable session affinity", "Add a search partition", "Health-check a URL that proves the engine answers"], answer: 3,
    explain: "A web server can answer while the engine behind the gateway is down. A meaningful health check exercises the full request path." },
  { id: "sa-q-sys-048", domain: "sa-sysadmin", guide: "sa-cluster-performance",
    q: "True or false: raising the number of worker threads always improves performance.",
    options: ["True", "False"], answer: 1,
    explain: "False. More threads only help if the database, storage and memory can absorb more parallel work; otherwise they move the queue to the database." },
  { id: "sa-q-sys-049", domain: "sa-sysadmin", guide: "sa-modules-patches",
    q: "What is the correct sequence to add an optional module?",
    options: ["Upload it to the Enterprise Workspace", "Copy the module into the patch folder and restart", "Run the module installer (to staging), then Module Administration ▸ Install Modules, then restart", "Import the module with a LiveReport"], answer: 2,
    explain: "Installers place modules in the staging folder; Install Modules activates them and Content Server then requires a restart." },
  { id: "sa-q-sys-050", domain: "sa-sysadmin", guide: "sa-modules-patches",
    q: "Where are hot-fix patch files placed when applied manually?",
    options: ["The Categories volume", "<OTHOME>/patch", "<OTHOME>/staging", "<OTHOME>/logs"], answer: 1,
    explain: "The engine loads patches from the patch folder at start-up. Staging is for modules." },
  { id: "sa-q-sys-051", domain: "sa-sysadmin", guide: "sa-modules-patches",
    q: "True or false: uninstalling a module always removes all of its data from the database.",
    options: ["True", "False"], answer: 1,
    explain: "False. Uninstall removes the module's code; its tables and data may remain, and items of its types become unusable. Plan removals carefully." },
  { id: "sa-q-sys-052", domain: "sa-sysadmin", guide: "sa-modules-patches",
    q: "After installing a cumulative update, what should usually happen to older patches in the patch folder that the update already contains?",
    options: ["Remove them as the update's readme instructs", "Move them to staging", "Rename them to .bak and keep them loaded", "Keep them; they are ignored"], answer: 0,
    explain: "Superseded patches can overwrite newer code from the update. Update readmes list which patches to delete." },
  { id: "sa-q-sys-053", domain: "sa-sysadmin", guide: "sa-modules-patches",
    q: "Which document lists the loaded patches and module versions of an instance?",
    options: ["The connect log", "The OTDS access log", "The DTree table", "The System Report"], answer: 3,
    explain: "The System Report includes versions, modules and loaded patches — compare reports of all instances after changes." },
  { id: "sa-q-sys-054", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "On Content Server 16 and later, which service is the only supported source of users, groups and single sign-on?",
    options: ["Archive Center", "Content Server Directory Services (CSDS)", "OpenText Directory Services (OTDS)", "The Search Federator"], answer: 2,
    explain: "CSDS was retired with version 16; OTDS provides identity, synchronisation, access control and SSO." },
  { id: "sa-q-sys-055", domain: "sa-sysadmin", guide: "sa-architecture",
    q: "True or false: search processes can run on hosts other than the Content Server engine host.",
    options: ["True", "False"], answer: 0,
    explain: "True. Any host with an Admin server can run search processes; large systems use dedicated search servers." },
  // ================================================================ sa-logging
  { id: "sa-q-log-001", domain: "sa-logging", guide: "sa-logging",
    q: "One specific page takes 30 seconds to load while all other pages are fast. Which log should you enable first to find the cause?",
    options: ["Document Conversion log", "Connect (SQL) log", "OTDS access log", "Web server access log"], answer: 1,
    explain: "A single slow page is usually one expensive SQL statement or many repeated ones. Connect logs show each statement and its elapsed time." },
  { id: "sa-q-log-002", domain: "sa-logging", guide: "sa-logging",
    q: "A user gets an error page with a traceback when adding a version. Which log should you read first?",
    options: ["The thread log of the instance at that time", "The OTDS log", "The Search Federator log", "The SMTP server log"], answer: 0,
    explain: "Thread logs record each request with its errors and OScript tracebacks. Use the connect log next if the error is a database error." },
  { id: "sa-q-log-003", domain: "sa-logging", guide: "sa-logging",
    q: "Where are the OTDS log files (such as otds.log) normally found?",
    options: ["In the DAuditNew table", "In the Windows temp folder", "In <OTHOME>/logs", "In the logs folder of the Tomcat server hosting OTDS"], answer: 3,
    explain: "OTDS is a web application running in Tomcat, so its logs are kept in that Tomcat's logs folder, not with the Content Server engine logs." },
  { id: "sa-q-log-004", domain: "sa-logging", guide: "sa-logging",
    q: "True or false: detailed thread and SQL logging should stay enabled permanently on production so that evidence is always available.",
    options: ["True", "False"], answer: 1,
    explain: "False. Verbose logs grow very fast, cost some performance and contain personal data. Enable them for a defined window, collect, then disable." },
  { id: "sa-q-log-005", domain: "sa-logging", guide: "sa-opentext-ini",
    q: "In opentext.ini, in which section is the engine's debug (logging) level usually set?",
    options: ["[search]", "[otds]", "[general]", "[dbconnection:…]"], answer: 2,
    explain: "The debug level lives in [general]; logging flags such as wantLogs and wantVerbose are in [options]." },
  { id: "sa-q-log-006", domain: "sa-logging", guide: "sa-opentext-ini",
    q: "Which two opentext.ini [options] flags are commonly set to TRUE when OpenText Support asks for detailed engine logs? (Choose two.)",
    options: ["searchDebug", "wantLogs", "wantVerbose", "enableOTDS"], answer: [1, 2],
    explain: "wantLogs switches logging on and wantVerbose adds detail. The other names are invented distractors — never add keys you have not verified, they are ignored silently." },
  { id: "sa-q-log-007", domain: "sa-logging", guide: "sa-logging",
    q: "After changing logging settings in opentext.ini, what is normally required?",
    options: ["A restart of that Content Server instance", "A database restore", "A reindex", "Nothing; the file is re-read on every request"], answer: 0,
    explain: "The engine reads opentext.ini at start-up, so ini-based logging changes take effect after a restart." },
  { id: "sa-q-log-008", domain: "sa-logging", guide: "sa-logging",
    q: "Which log provides the input for OpenText Performance Analyzer?",
    options: ["Connect logs", "OTDS directory-access log", "IIS error log", "Summary timing logs"], answer: 3,
    explain: "Summary timing logs give one line per request with its duration — exactly what OTPA aggregates." },
  { id: "sa-q-log-009", domain: "sa-logging", guide: "sa-logging",
    q: "Users get HTTP 500 errors before any Content Server page appears. Which logs are most useful first?",
    options: ["LiveReport output", "Search Engine logs", "Web server logs and the OS event log", "Connect logs"], answer: 2,
    explain: "If the failure happens before Content Server answers, the web tier or the engine service state is the place to look." },
  { id: "sa-q-log-010", domain: "sa-logging", guide: "sa-logging",
    q: "What does the Content Server System Report contain?",
    options: ["Only a list of users", "Version, modules, patches, database and OS details and configuration", "All documents added today", "Search query statistics only"], answer: 1,
    explain: "The System Report is a broad environment snapshot — ideal for Support cases and before/after comparisons." },
  { id: "sa-q-log-011", domain: "sa-logging", guide: "sa-logging",
    q: "True or false: thread and connect logs can contain user names and item names, so they must be handled as confidential.",
    options: ["True", "False"], answer: 0,
    explain: "True. Share them only through the support portal and delete local copies when the case is closed." },
  { id: "sa-q-log-012", domain: "sa-logging", guide: "sa-logging",
    q: "New documents are not searchable. Which logs should you read?",
    options: ["The logs of the search processes, starting after the growing iPool", "The OTDS logs", "The IIS access log", "The notification agent log"], answer: 0,
    explain: "Search processes keep their own logs. The process just after a growing iPool is the bottleneck and its log usually explains why." },
  { id: "sa-q-log-013", domain: "sa-logging", guide: "sa-troubleshooting-method",
    q: "What is the best first step when a user reports a problem?",
    options: ["Run a full reindex", "Restore last night's backup", "Restart all instances", "Collect the exact symptom, time, affected users and recent changes"], answer: 3,
    explain: "Defining and scoping the problem comes before any change. Most incidents follow a change, so ask what changed." },
  { id: "sa-q-log-014", domain: "sa-logging", guide: "sa-troubleshooting-method",
    q: "A problem occurs only when users are routed to front-end 3. What is the most likely class of cause?",
    options: ["A corrupt search index", "A shared-tier failure such as the database", "Something specific to that instance: configuration drift, missing patch or local path", "An AD outage"], answer: 2,
    explain: "Shared tiers would affect every instance. Compare ini files and System Reports and check host-specific paths." },
  { id: "sa-q-log-015", domain: "sa-logging", guide: "sa-troubleshooting-method",
    q: "True or false: when testing fixes, you should change several settings at once to save time.",
    options: ["True", "False"], answer: 1,
    explain: "False. Change one variable at a time; otherwise you cannot tell which change helped, and you may add new problems." },
  { id: "sa-q-log-016", domain: "sa-logging", guide: "sa-troubleshooting-method",
    q: "Before opening an OpenText Support case for a server error, which two items should you collect? (Choose two.)",
    options: ["Every user's password", "The System Report", "The relevant logs for the time of the error from all relevant instances", "A full export of the database"], answer: [1, 2],
    explain: "Support needs the environment (System Report) and evidence (logs with times). A database export is rarely needed and passwords are never shared." },
  { id: "sa-q-log-017", domain: "sa-logging", guide: "sa-troubleshooting-method",
    q: "Help-desk staff repeatedly escalate the same simple questions. What does the troubleshooting method recommend?",
    options: ["Record the solutions in a help-desk FAQ or runbook", "Ignore the questions", "Disable the feature", "Grant them System Administration rights"], answer: 0,
    explain: "The final step of the method is to record what you learned, so first-line staff can resolve recurring issues themselves." },
  { id: "sa-q-log-018", domain: "sa-logging", guide: "sa-runbook",
    q: "Nobody can sign in, and the OTDS sign-in page does not load at all. What is the most likely cause?",
    options: ["The Search Federator is stopped", "A storage rule is wrong", "A user is missing from the access role", "OTDS or the Tomcat hosting it is down or unreachable"], answer: 3,
    explain: "If the OTDS page itself does not load, the problem is the OTDS service or the network path to it, not individual accounts." },
  { id: "sa-q-log-019", domain: "sa-logging", guide: "sa-runbook",
    q: "The Content Server service will not start immediately after a hot fix was copied into the patch folder. What is a sensible first action?",
    options: ["Restore the EFS", "Reinstall the operating system", "Move the newly added patch out and retry, then check it matches the exact version", "Delete the logs folder"], answer: 2,
    explain: "A patch for another version or a superseded patch can stop the engine loading. Removing it isolates the cause quickly." },
  { id: "sa-q-log-020", domain: "sa-logging", guide: "sa-runbook",
    q: "Every page is slow for everyone, including simple ones. Connect logs show ordinary queries taking seconds. Where is the problem most likely?",
    options: ["In one user's browser", "In the database tier (blocking, statistics, I/O)", "In a single folder's ACL", "In OTDS"], answer: 1,
    explain: "When ordinary SQL is slow for everyone, look at the shared database: blocking chains, stale statistics, storage I/O." },
  { id: "sa-q-log-021", domain: "sa-logging", guide: "sa-runbook",
    q: "Downloads are slow, but connect logs show the SQL for the same requests completes quickly. Which tier should you investigate?",
    options: ["Storage (share latency, antivirus on the EFS, network path)", "OTDS", "The search grid", "The LiveReports"], answer: 0,
    explain: "If metadata queries are fast but fetching content is slow, the content store or the path to it is the bottleneck." },
  { id: "sa-q-log-022", domain: "sa-logging", guide: "sa-runbook",
    q: "True or false: a full reindex is usually the first fix for an indexing backlog.",
    options: ["True", "False"], answer: 1,
    explain: "False. Find the stopped or slow process from the iPool counts and fix it; a full reindex is the most expensive option and rarely needed." },
  { id: "sa-q-log-023", domain: "sa-logging", guide: "sa-search-admin",
    q: "Which daily check shows most quickly whether the search data flow is keeping up?",
    options: ["The number of users in KUAF", "The size of opentext.ini", "The audit table row count", "The number of batches waiting in each iPool"], answer: 3,
    explain: "Small, moving iPool counts are healthy; a growing one is a backlog in front of a slow process." },
  { id: "sa-q-log-024", domain: "sa-logging", guide: "sa-otds-troubleshooting",
    q: "Which OTDS log is most useful to see which authentication handler was used and whether a sign-in failed?",
    options: ["The DCS log", "The IIS access log", "The directory access log (for example directory-access.log)", "The Content Server connect log"], answer: 2,
    explain: "The OTDS access log records authentication events per user and handler; otds.log covers broader server activity." },
  { id: "sa-q-log-025", domain: "sa-logging", guide: "sa-logging",
    q: "In a three-instance cluster, you enable detailed logging to catch an intermittent error. Which approach ensures you capture it?",
    options: ["Enable it on the instance you are signed into and hope the error occurs there", "Enable logging on one instance and route a test user to it, or enable it on all instances for the window", "Enable it only on the database server", "Enable it in OTDS only"], answer: 1,
    explain: "The load balancer may send the failing request to any instance. Either pin the test to one instance or log on all of them." },
  { id: "sa-q-log-026", domain: "sa-logging", guide: "sa-agents",
    q: "Bulk delete jobs started in Smart View never finish. Where do you look first?",
    options: ["The Distributed Agent dashboard and the logs of the instances running workers", "The OTDS partition status", "The Search Federator log", "The IIS access log"], answer: 0,
    explain: "Bulk operations run as Distributed Agent tasks. The dashboard shows queued and failed tasks; worker instance logs explain failures." },
  { id: "sa-q-log-027", domain: "sa-logging", guide: "sa-cluster-performance",
    q: "Which source gives the clearest picture of thread usage and slow transaction types over a whole week?",
    options: ["One thread log from today", "The System Report", "The OTDS access log", "Summary timing logs analysed with Performance Analyzer"], answer: 3,
    explain: "Summary timings capture every request; OTPA turns them into trends. Thread logs are better for a single failing request." },
  // ================================================================ sa-schema
  { id: "sa-q-sch-001", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which table contains one row for every item (folder, document, workflow map, category…) in Content Server?",
    options: ["KUAF", "LLAttrData", "DTree", "DVersData"], answer: 2,
    explain: "DTree (a view over DTreeCore on 16+) is the node table. DVersData holds versions, KUAF users and groups, LLAttrData attribute values." },
  { id: "sa-q-sch-002", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which DTree column identifies the container of an item?",
    options: ["VersionNum", "ParentID", "OwnerID", "SubType"], answer: 1,
    explain: "ParentID is the DataID of the container and builds the hierarchy. SubType is the item type; VersionNum the current version." },
  { id: "sa-q-sch-003", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which SubType value identifies a standard document in DTree?",
    options: ["144", "299", "0", "131"], answer: 0,
    explain: "144 is Document; 0 is Folder, 131 Category and 299 LiveReport." },
  { id: "sa-q-sch-004", domain: "sa-schema", guide: "sa-sql-recipes",
    q: "How do you join DTree to DVersData to get the current version of each document?",
    options: ["DVersData.ID = DTree.ParentID", "DVersData.DocID = DTree.OwnerID", "DVersData.ProviderId = DTree.DataID", "DVersData.DocID = DTree.DataID AND DVersData.Version = DTree.VersionNum"], answer: 3,
    explain: "DocID points to the item; matching Version to DTree.VersionNum keeps only the current version." },
  { id: "sa-q-sch-005", domain: "sa-schema", guide: "sa-schema-tour",
    q: "In KUAF, which Type value marks a group?",
    options: ["144", "0", "1", "2"], answer: 2,
    explain: "Type 0 is a user and Type 1 a group." },
  { id: "sa-q-sch-006", domain: "sa-schema", guide: "sa-sql-recipes",
    q: "In KUAFChildren, what do the ID and ChildID columns represent?",
    options: ["ID = a version, ChildID = its document", "ID = the group, ChildID = a direct member", "ID = the member, ChildID = the group", "ID = an item, ChildID = its parent"], answer: 1,
    explain: "Each row links a group to one direct member, which may itself be a group. Nested membership needs a recursive query." },
  { id: "sa-q-sch-007", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which table stores the access control entries of items?",
    options: ["DTreeACL", "KUAFChildren", "DAuditNew", "ProviderData"], answer: 0,
    explain: "DTreeACL holds DataID, RightID, ACLType and the Permissions bit mask for each entry." },
  { id: "sa-q-sch-008", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which table stores the values that users enter in category attributes?",
    options: ["CatRegionMap", "DTree", "KIni", "LLAttrData"], answer: 3,
    explain: "LLAttrData stores attribute values in typed columns. CatRegionMap only maps attributes to search region names." },
  { id: "sa-q-sch-009", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which table helps you trace a document version to the file on the storage provider?",
    options: ["WSubWork", "KUAF", "ProviderData", "DTreeAncestors"], answer: 2,
    explain: "DVersData.ProviderId links to ProviderData, which records which provider holds the content and how to find it." },
  { id: "sa-q-sch-010", domain: "sa-schema", guide: "sa-sql-recipes",
    q: "Which table lets you list every item below a folder at any depth without a recursive query?",
    options: ["KUAFChildren", "DTreeAncestors", "DTreeNotify", "DVersData"], answer: 1,
    explain: "DTreeAncestors holds every (item, ancestor) pair, so WHERE AncestorID = folder returns the whole subtree." },
  { id: "sa-q-sch-011", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which tables hold workflow instances and their steps? (Choose two.)",
    options: ["WWork", "WSubWorkTask", "DVersData", "CatRegionMap"], answer: [0, 1],
    explain: "WWork holds workflow instances; WSubWork their sub-works; WSubWorkTask the individual steps with performers and status." },
  { id: "sa-q-sch-012", domain: "sa-schema", guide: "sa-schema-tour",
    q: "True or false: on Content Server 16 and later, DTree is a view, and the physical node table is DTreeCore.",
    options: ["True", "False"], answer: 0,
    explain: "True. DTree remains the convenient name to query; it combines DTreeCore with multilingual name data." },
  { id: "sa-q-sch-013", domain: "sa-schema", guide: "sa-schema-tour",
    q: "True or false: correcting a wrong document name directly with an UPDATE on DTree is a safe administrative shortcut.",
    options: ["True", "False"], answer: 1,
    explain: "False. Direct writes bypass caches, audit and search indexing events, leaving the system inconsistent. Use the UI, REST API or supported tools." },
  { id: "sa-q-sch-014", domain: "sa-schema", guide: "sa-schema-tour",
    q: "Which table records audited events such as who deleted an item and when?",
    options: ["DTreeNotify", "KIni", "LLAttrData", "DAuditNew"], answer: 3,
    explain: "DAuditNew stores the event name, item, performer and date for every audited event." },
  { id: "sa-q-sch-015", domain: "sa-schema", guide: "sa-livereports",
    q: "In the SQL of a LiveReport with two inputs, how is the second input referenced?",
    options: [":2", "@input2", "%2", "$2"], answer: 2,
    explain: "LiveReports substitute %1, %2 … with the values of their inputs in order." },
  { id: "sa-q-sch-016", domain: "sa-schema", guide: "sa-livereports",
    q: "What does a LiveReport sub-report provide?",
    options: ["A second database connection", "A drill-down: a column links to another LiveReport that receives the row's value as input", "A backup of the report", "A schedule for running the report"], answer: 1,
    explain: "Sub-reports turn a summary into an interactive drill-down by passing a column value to a detail report." },
  { id: "sa-q-sch-017", domain: "sa-schema", guide: "sa-livereports",
    q: "True or false: LiveReport results are automatically filtered by the item permissions of the person running the report.",
    options: ["True", "False"], answer: 1,
    explain: "False. The SQL runs with the database account; unless the query restricts rows, it can show items the user cannot open. Control who may run each report." },
  { id: "sa-q-sch-018", domain: "sa-schema", guide: "sa-livereports",
    q: "Besides a table, how else can a LiveReport present its results?",
    options: ["As a chart such as a bar or pie chart", "As a workflow map", "As a storage rule", "As an OTDS partition"], answer: 0,
    explain: "LiveReports can render simple charts from a label column and a value column." },
  { id: "sa-q-sch-019", domain: "sa-schema", guide: "sa-livereports",
    q: "Who should normally be allowed to create LiveReports?",
    options: ["Only OTDS administrators", "Anonymous users", "Every user", "Administrators or a small trained group holding the creation privilege"], answer: 3,
    explain: "LiveReports run raw SQL, so creation is a restricted privilege granted sparingly." },
  { id: "sa-q-sch-020", domain: "sa-schema", guide: "sa-sql-recipes",
    q: "You need to list who is on the ACL of an item, including special entries such as Public Access that have no KUAF row. Which join should you use from DTreeACL to KUAF?",
    options: ["CROSS JOIN", "No join is possible", "LEFT JOIN on KUAF.ID = DTreeACL.RightID", "INNER JOIN on KUAF.ID = DTreeACL.DataID"], answer: 2,
    explain: "A LEFT JOIN keeps ACL rows whose RightID is a special value without a KUAF row; matching is on RightID, not DataID." },
  { id: "sa-q-sch-021", domain: "sa-schema", guide: "sa-search-admin",
    q: "A search on a category attribute returns nothing although values exist. Which table tells you the search region name used for that attribute?",
    options: ["WWork", "CatRegionMap", "DTreeACL", "KUAFChildren"], answer: 1,
    explain: "CatRegionMap maps category attributes to search regions, so you can check what the index calls the field." },
  // ================================================================ sa-bizadmin
  { id: "sa-q-biz-001", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "In which volume are category definitions created and maintained?",
    options: ["Categories volume", "Facets volume", "Perspectives volume", "System Object Volume"], answer: 0,
    explain: "Categories live in the Categories volume. Facets and columns are in the Facets volume; search processes in the System Object Volume." },
  { id: "sa-q-biz-002", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "A business administrator adds attributes to a category used on 2 million items and upgrades them all. Which platform effects should the system administrator expect? (Choose two.)",
    options: ["A surge of indexing work on the search grid", "OTDS resynchronisation of all users", "A new storage provider being created", "Background processing to upgrade the items"], answer: [0, 3],
    explain: "Upgrading category versions changes many items, which runs as background work and generates re-extraction for search. Identity and storage are unaffected." },
  { id: "sa-q-biz-003", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Where are custom columns and facets defined?",
    options: ["In OTDS", "In the patch folder", "In the Facets volume", "In opentext.ini"], answer: 2,
    explain: "Columns and facets are items in the Facets volume, built from system or category attributes." },
  { id: "sa-q-biz-004", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "True or false: every facet shown on a busy container adds work to each browse or search that displays it.",
    options: ["True", "False"], answer: 0,
    explain: "True. Facet values must be computed for the result set, so keep the number of facets on heavily used containers modest." },
  { id: "sa-q-biz-005", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "A new custom column shows empty values for existing documents right after it is created. What is the most likely explanation?",
    options: ["The EFS is full", "Column values for existing items are still being populated in the background", "The category was deleted", "OTDS has not pushed the users"], answer: 1,
    explain: "Column and facet values are computed and stored for fast display; for existing items this can take time after creation." },
  { id: "sa-q-biz-006", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "What is a search form?",
    options: ["A saved configuration of the search page that users can reuse", "A storage rule for search results", "A LiveReport", "An OTDS handler"], answer: 0,
    explain: "Search forms store fields, scope and options so users need not rebuild a complex search; administrators can publish system-wide forms." },
  { id: "sa-q-biz-007", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Users report that a published search form returns nothing for an attribute value they know exists. Which two checks are most relevant? (Choose two.)",
    options: ["Whether the attribute is indexed under the expected region", "The SMTP server", "The OTSCM agent status", "The form's scope (slice)"], answer: [0, 3],
    explain: "A too-narrow scope or an attribute region that is not indexed as expected explains empty results; mail and OTSCM are unrelated." },
  { id: "sa-q-biz-008", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "True or false: an item purged from the Recycle Bin can be restored by the administrator from the Recycle Bin pages.",
    options: ["True", "False"], answer: 1,
    explain: "False. Purge is final within Content Server; only a backup restore can bring the item back." },
  { id: "sa-q-biz-009", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Which Recycle Bin setting most directly controls how long deleted items can still be restored?",
    options: ["The notification schedule", "The thread count", "The retention period before automatic purge", "The number of search partitions"], answer: 2,
    explain: "Items stay restorable until the retention period expires and the purge runs." },
  { id: "sa-q-biz-010", domain: "sa-bizadmin", guide: "sa-agents",
    q: "How are large Recycle Bin purges typically processed on Content Server 16 and later?",
    options: ["By the Search Federator", "As Distributed Agent tasks in the background", "Inside the user's browser", "By OTDS"], answer: 1,
    explain: "Long-running purges are split into Distributed Agent tasks so they do not block user requests." },
  { id: "sa-q-biz-011", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "The audit table has grown to hundreds of millions of rows. What is the supported way to reduce it?",
    options: ["Purge old audit records through the event auditing administration according to policy", "DELETE rows with SQL", "Drop the table", "Disable the database"], answer: 0,
    explain: "Use the auditing administration to purge, following your retention policy. Direct SQL deletes are unsupported and may destroy evidence." },
  { id: "sa-q-biz-012", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "True or false: auditing more event types increases the growth of the DAuditNew table and the write load on the database.",
    options: ["True", "False"], answer: 0,
    explain: "True. Every audited event writes a row. Choose auditing interests for real compliance or investigation needs." },
  { id: "sa-q-biz-013", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Where does an administrator choose which events Content Server audits?",
    options: ["In OTDS access roles", "In storage rules", "In the Search Manager", "In the event auditing administration (auditing interests)"], answer: 3,
    explain: "Auditing interests on the Administration pages decide which events are recorded." },
  { id: "sa-q-biz-014", domain: "sa-bizadmin", guide: "sa-agents",
    q: "Which three conditions must all be true for users to receive notification emails? (Choose three.)",
    options: ["The search index is rebuilt daily", "Notifications are enabled for the system", "SMTP is configured and reachable from the instance running the agent", "The notification agent runs on at least one instance", "Every user has System Administration rights"], answer: [1, 2, 3],
    explain: "The system switch, a working SMTP configuration and a running notification agent are all required; privileges and reindexing are irrelevant." },
  { id: "sa-q-biz-015", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Where are Smart View perspectives managed?",
    options: ["In OTDS resources", "In the Perspectives volume, with the Perspective Manager", "In opentext.ini", "In the System Object Volume"], answer: 1,
    explain: "Perspectives are configuration items in the Perspectives volume, edited with the Perspective Manager." },
  { id: "sa-q-biz-016", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Which tool is typically used to move business configuration such as categories and perspectives from a test system to production?",
    options: ["Transport Warehouse packages", "Copying database tables", "OTDS consolidation", "The patch folder"], answer: 0,
    explain: "Transport Warehouse packages configuration items for import elsewhere, avoiding manual re-creation or unsupported database copying." },
  { id: "sa-q-biz-017", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Which group, created at installation, is intended for people who manage business configuration without full system administration rights?",
    options: ["DefaultGroup", "Public Access", "otds.admin", "Business Administrators"], answer: 3,
    explain: "The Business Administrators group supports separating business configuration from platform administration." },
  { id: "sa-q-biz-018", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "True or false: system-wide version limits affect how fast storage grows.",
    options: ["True", "False"], answer: 0,
    explain: "True. Every kept version stores another copy of the file; limits reduce growth but must respect records requirements." },
  { id: "sa-q-biz-019", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Which responsibility belongs to the system administrator rather than the business administrator?",
    options: ["Designing which facets the legal team needs", "Deciding perspective layouts for workspaces", "Sizing the database for audit growth and fixing SMTP for notifications", "Choosing attribute names for a contracts category"], answer: 2,
    explain: "Business administrators design configuration; system administrators keep the platform able to run it." },
  { id: "sa-q-biz-020", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "After a category is changed, items still show the old attribute set. Why?",
    options: ["The storage rule overrides categories", "Items keep the old category version until they are upgraded", "The search index is corrupt", "OTDS blocked the change"], answer: 1,
    explain: "Category edits create a new version; applied items must be upgraded to receive it." },
  { id: "sa-q-biz-021", domain: "sa-bizadmin", guide: "sa-admin-pages",
    q: "Where are system-wide defaults for item behaviour such as versioning options typically configured?",
    options: ["In the feature configuration area of the Administration pages", "In the OTDS admin client", "In the System Object Volume", "In the search partition map"], answer: 0,
    explain: "Feature configuration pages hold system defaults for item behaviour; some can be overridden per container." },
  { id: "sa-q-biz-022", domain: "sa-bizadmin", guide: "sa-agents",
    q: "True or false: a test copy of production restored for training can send real notification emails to production users if notifications are left enabled.",
    options: ["True", "False"], answer: 0,
    explain: "True. The copy holds real addresses and interests. Disable notifications and change SMTP before starting it." },
  { id: "sa-q-biz-023", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Who should be allowed to query and purge audit records?",
    options: ["All users", "Anonymous users", "Only OTDS", "A small, named set of administrators or auditors"], answer: 3,
    explain: "Audit data may be legal evidence. Restrict who can read it and especially who can purge it." },
  { id: "sa-q-biz-024", domain: "sa-bizadmin", guide: "sa-bizadmin-for-sysadmins",
    q: "Which statement about category attribute values and search is correct?",
    options: ["Only the category name is indexed", "Attribute values are stored in OTDS", "Each category attribute becomes a search region that can be queried", "Category values are never indexed"], answer: 2,
    explain: "Attribute values are indexed as regions (mapped in CatRegionMap) and stored in LLAttrData." },
  // ================================================================ sa-otds
  { id: "sa-q-otds-001", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "In OTDS, what is a resource?",
    options: ["A storage provider", "The OTDS representation of an application, such as a Content Server system", "A group of AD users", "A Kerberos ticket"], answer: 1,
    explain: "Each application using OTDS is a resource with its own ID, mappings and, for Content Server, a push connector." },
  { id: "sa-q-otds-002", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "What does an OTDS access role control?",
    options: ["Which users, groups or partitions may use a resource and are pushed to it", "Item permissions inside Content Server", "The order of storage rules", "The search partitions a user may query"], answer: 0,
    explain: "Access roles connect identities to resources. Item permissions are still Content Server ACLs." },
  { id: "sa-q-otds-003", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "A new employee exists in AD and in the OTDS synchronized partition, but cannot sign in to Content Server and has no Content Server account. What is the most likely cause?",
    options: ["The search index is stale", "The EFS is full", "The user lacks System Administration rights", "The user is not a member of the access role for the Content Server resource"], answer: 3,
    explain: "Only access-role members are pushed to the resource and allowed to sign in." },
  { id: "sa-q-otds-004", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "True or false: a synchronized user partition copies users' AD passwords into OTDS.",
    options: ["True", "False"], answer: 1,
    explain: "False. Passwords stay in the directory; OTDS checks them against AD/LDAP at sign-in." },
  { id: "sa-q-otds-005", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "Which partition type is best for external partners who are not in your Active Directory?",
    options: ["The otds.admin system partition", "A Content Server resource", "Non-synchronized user partition", "Synchronized user partition"], answer: 2,
    explain: "Non-synchronized partitions hold users maintained directly in OTDS, with OTDS password policies." },
  { id: "sa-q-otds-006", domain: "sa-otds", guide: "sa-otds-resource",
    q: "Which two values must Content Server be given to integrate with OTDS? (Choose two.)",
    options: ["The Kerberos keytab", "The OTDS server URL", "The resource ID", "The AD bind password"], answer: [1, 2],
    explain: "With the OTDS URL and the resource ID, Content Server activates its resource. Directory and Kerberos settings live in OTDS." },
  { id: "sa-q-otds-007", domain: "sa-otds", guide: "sa-otds-resource",
    q: "What does the Content Server push connector do?",
    options: ["Creates, updates and disables users and groups in Content Server from OTDS", "Pushes documents into OTDS", "Pushes search results to users", "Pushes patches to servers"], answer: 0,
    explain: "It keeps KUAF and KUAFChildren in step with OTDS for the members of the access role." },
  { id: "sa-q-otds-008", domain: "sa-otds", guide: "sa-otds-resource",
    q: "After adding a large AD group to the access role, you want its members in Content Server now rather than waiting. Which OTDS action do you run?",
    options: ["Delete the partition", "Restart the Search Federator", "Reindex Content Server", "Consolidate the resource"], answer: 3,
    explain: "Consolidation reconciles OTDS with the resource and pushes any missing users and groups." },
  { id: "sa-q-otds-009", domain: "sa-otds", guide: "sa-otds-resource",
    q: "True or false: changing the resource mapping that produces the Content Server login name after go-live can create duplicate users.",
    options: ["True", "False"], answer: 0,
    explain: "True. Content Server identifies users by name; a new format looks like a new user. Decide the login format before go-live." },
  { id: "sa-q-otds-010", domain: "sa-otds", guide: "sa-otds-resource",
    q: "Which account is the built-in OTDS administrator, mapped to the Content Server Admin user on 16.x?",
    options: ["administrator@local", "root@otds", "otadmin@otds.admin", "admin@contentserver"], answer: 2,
    explain: "otadmin@otds.admin is created with OTDS. Protect it and use named administrator accounts for daily work." },
  { id: "sa-q-otds-011", domain: "sa-otds", guide: "sa-otds-sso",
    q: "Which OTDS authentication handler provides integrated Windows authentication for domain-joined PCs?",
    options: ["Password form", "HTTP Negotiate (Kerberos/SPNEGO)", "SAML 2.0", "OAuth client credentials"], answer: 1,
    explain: "HTTP Negotiate uses the user's Windows Kerberos ticket for silent sign-in." },
  { id: "sa-q-otds-012", domain: "sa-otds", guide: "sa-otds-sso",
    q: "The company wants users to sign in through its central identity provider (ADFS or Entra ID) with the IdP's multi-factor authentication. Which OTDS feature fits best?",
    options: ["A SAML 2.0 authentication handler", "A non-synchronized partition", "A push connector", "A storage provider"], answer: 0,
    explain: "SAML federates OTDS with the corporate IdP, which performs authentication including MFA." },
  { id: "sa-q-otds-013", domain: "sa-otds", guide: "sa-otds-sso",
    q: "Domain users get a password prompt instead of silent sign-in. Which are likely causes? (Choose two.)",
    options: ["The OTDS URL is not in the browser's Local intranet zone", "The search partition is full", "The Recycle Bin retention is too short", "The SPN for the OTDS host name is missing or duplicated"], answer: [0, 3],
    explain: "Kerberos needs exactly one SPN for the host name users reach and a browser willing to negotiate with that site." },
  { id: "sa-q-otds-014", domain: "sa-otds", guide: "sa-otds-sso",
    q: "True or false: once SSO authenticates a user, OTDS automatically grants them access to every Content Server item.",
    options: ["True", "False"], answer: 1,
    explain: "False. SSO proves identity. The user must be pushed via the access role, hold the log-in privilege, and item access still follows Content Server permissions." },
  { id: "sa-q-otds-015", domain: "sa-otds", guide: "sa-otds-sso",
    q: "In which order does OTDS try its authentication handlers?",
    options: ["Randomly", "Always password first", "By their configured priority", "Alphabetically"], answer: 2,
    explain: "Handlers have priorities; a typical order is Kerberos, then SAML/OIDC, then the password form." },
  { id: "sa-q-otds-016", domain: "sa-otds", guide: "sa-otds-sync",
    q: "Which settings define a synchronized user partition? (Choose two.)",
    options: ["LiveReport inputs", "Connection details and bind account for the directory", "Search bases and LDAP filters for users and groups", "Storage rules"], answer: [1, 2],
    explain: "A synchronized partition needs to know how to connect and which part of the directory to read (plus mappings and monitoring)." },
  { id: "sa-q-otds-017", domain: "sa-otds", guide: "sa-otds-troubleshooting",
    q: "New AD users stopped appearing in OTDS yesterday. Existing users can still sign in with the password form. What is a likely cause?",
    options: ["The partition's bind account password expired or the LDAPS certificate changed", "The Search Federator is down", "A storage rule was reordered", "The patch folder is empty"], answer: 0,
    explain: "Synchronisation needs the bind account and a trusted secure connection; sign-in for existing users can still work through other paths." },
  { id: "sa-q-otds-018", domain: "sa-otds", guide: "sa-otds-troubleshooting",
    q: "Users bounce between Content Server and the OTDS sign-in page in a loop. Which cause is most plausible?",
    options: ["A full search partition", "Too many categories", "An expired LiveReport", "Mismatched host names or protocols, an untrusted Content Server URL in OTDS, or clock differences"], answer: 3,
    explain: "Redirect loops come from cookies or tickets that are not accepted: different host names (short vs FQDN, http vs https), trust settings or clock skew." },
  { id: "sa-q-otds-019", domain: "sa-otds", guide: "sa-otds-concepts",
    q: "From version 16, where are Content Server licence keys managed?",
    options: ["In the Categories volume", "In the search partition map", "In OTDS (license keys)", "In opentext.ini"], answer: 2,
    explain: "OTDS holds product licence keys and associates them with the resource that uses them." },
  { id: "sa-q-otds-020", domain: "sa-otds", guide: "sa-otds-sso",
    q: "Before enabling a new SAML handler with high priority, what precaution is recommended?",
    options: ["Reindex the search grid", "Make sure an administrator can still sign in with a password, such as otadmin through the OTDS sign-in page", "Delete all other handlers", "Disable the push connector"], answer: 1,
    explain: "A broken IdP configuration must not lock out the administrators who need to fix it." },
  // ================================================================ sa-otscm
  { id: "sa-q-scm-001", domain: "sa-otscm", guide: "sa-otscm",
    q: "What is OpenText System Center Manager primarily used for?",
    options: ["Automating installation, patching and updating of OpenText products", "Synchronising users from AD", "Indexing documents", "Designing workflow maps"], answer: 0,
    explain: "OTSCM centralises discovery, patching, updates and unattended installs; OTDS handles identity and the search grid indexing." },
  { id: "sa-q-scm-002", domain: "sa-otscm", guide: "sa-otscm",
    q: "What must be installed on each host that System Center Manager manages?",
    options: ["An Admin server", "A second OTDS", "A Search Federator", "An OTSCM agent"], answer: 3,
    explain: "The agent discovers installed products and carries out deployments on its host." },
  { id: "sa-q-scm-003", domain: "sa-otscm", guide: "sa-otscm",
    q: "True or false: right after installing the OTSCM server, you should apply its mandatory updates before managing other systems.",
    options: ["True", "False"], answer: 0,
    explain: "True. Bringing OTSCM itself up to date is the first step of the onboarding sequence." },
  { id: "sa-q-scm-004", domain: "sa-otscm", guide: "sa-otscm",
    q: "Put the onboarding in order: which step comes immediately after registering a system with an agent?",
    options: ["Creating an execution plan for OTDS", "Uninstalling the agent", "Discovering the OpenText products installed on it", "Deploying a language pack"], answer: 2,
    explain: "Register → discover products → enable the products to manage → deploy patches and updates." },
  { id: "sa-q-scm-005", domain: "sa-otscm", guide: "sa-otscm",
    q: "Which content can OTSCM deploy to a Content Suite installation? (Choose three.)",
    options: ["Language packs", "User passwords", "Search queries", "Patches", "Updates"], answer: [0, 3, 4],
    explain: "The OTSCM course covers deploying patches, updates and language packs; identity and search content are not OTSCM's job." },
  { id: "sa-q-scm-006", domain: "sa-otscm", guide: "sa-otscm",
    q: "What is an OTSCM execution plan?",
    options: ["A saved sequence of installation or update tasks that OTSCM runs unattended", "A SQL query plan", "A workflow map", "A storage rule"], answer: 0,
    explain: "Execution plans automate installations of products such as Content Server and OTDS, making environments reproducible." },
  { id: "sa-q-scm-007", domain: "sa-otscm", guide: "sa-otscm",
    q: "How can administrators authenticate to System Center Manager?",
    options: ["Only anonymously", "Only with the Content Server administration password", "Only with database credentials", "With local OTSCM users or through OTDS integration"], answer: 3,
    explain: "OTSCM supports local users and OTDS integration for named administrator accounts." },
  { id: "sa-q-scm-008", domain: "sa-otscm", guide: "sa-otscm",
    q: "True or false: because OTSCM automates deployments, backups before applying updates are no longer necessary.",
    options: ["True", "False"], answer: 1,
    explain: "False. Automation applies changes consistently but does not provide a rollback. Back up database, content store and installation home first." },
  { id: "sa-q-scm-009", domain: "sa-otscm", guide: "sa-otscm",
    q: "Why does System Center Manager reduce the risk of 'random' errors in a Content Server cluster?",
    options: ["It merges all instances into one", "It removes patches automatically every night", "It deploys the same package to every selected instance and records the result centrally", "It disables the load balancer"], answer: 2,
    explain: "A missing patch on one instance causes errors that look random; OTSCM's consistent deployment and history prevent and reveal this." },
  { id: "sa-q-scm-010", domain: "sa-otscm", guide: "sa-otscm",
    q: "True or false: an OTSCM agent must be able to communicate with the OTSCM server for deployments to work.",
    options: ["True", "False"], answer: 0,
    explain: "True. Agents receive and report tasks through the server, so firewall rules must allow their communication." },
  { id: "sa-q-scm-011", domain: "sa-otscm", guide: "sa-otscm",
    q: "Before OTSCM shows applicable patches for a Content Server installation on a registered system, what must you do?",
    options: ["Rebuild the search index", "Enable that product for management in OTSCM", "Create a LiveReport", "Add the host to an OTDS access role"], answer: 1,
    explain: "Discovered products must be enabled before OTSCM manages their patches and updates." },
  { id: "sa-q-scm-012", domain: "sa-otscm", guide: "sa-otscm",
    q: "Which is the best practice for rolling out a patch with OTSCM?",
    options: ["Deploy to a test system first, verify, then deploy to all production instances in a maintenance window", "Deploy to one production front-end only", "Deploy during peak hours to test load", "Skip the readme"], answer: 0,
    explain: "Use the same OTSCM process on test, verify, then deploy to every production instance in an agreed window." },
  { id: "sa-q-scm-013", domain: "sa-otscm", guide: "sa-cluster-performance",
    q: "On Content Server 16.x, which built-in Administration area distributed updates and patches to all cluster instances through a Cluster Agent?",
    options: ["Search Administration", "Notification Administration", "Storage Provider Settings", "Cluster Management"], answer: 3,
    explain: "Cluster Management with its Cluster Agent served this purpose on 16.x; System Center Manager is OpenText's broader tool for patch and update deployment." },
];
