'use strict';
// Question bank for the Business Workspaces skill path (domains ws-*).
// The path also draws on the 5-0159 workspace domains it includes.
// Format: curriculum/CONTENT.md.

module.exports = [
  // ---------------------------------------------------------------- ws-concepts
  { id: 'ws-q-concepts-001', domain: 'ws-concepts', q: 'What is a business workspace?', options: ['A container that holds all content about one business object, created from a template, with metadata, a team and a layout', 'A personal folder for drafts', 'A search form for business data', 'A workflow map for approvals'], answer: 0, explain: 'A business workspace gathers everything about one business object (customer, contract, project…) in one container built from a template.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-002', domain: 'ws-concepts', q: 'Which object decides the name of a new business workspace?', options: ['The workspace type', 'The workspace template', 'The perspective', 'The location folder'], answer: 0, explain: 'The workspace type holds the name pattern built from attributes or business object properties.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-003', domain: 'ws-concepts', q: 'Which object decides the folders and roles a new workspace gets?', options: ['The workspace template', 'The workspace type', 'The classification', 'The external system'], answer: 0, explain: 'The template is copied at creation: content, roles, permissions and categories.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-004', domain: 'ws-concepts', q: 'Which two statements about business workspaces without any ERP or CRM integration are true? (Choose two.)', options: ['They still have workspace types, templates and roles', 'Their metadata is entered in Content Server', 'They cannot have a perspective', 'They can only be created by the Admin user'], answer: [0, 1], explain: 'Unconnected workspaces work the same way; only the source of metadata differs — users type it.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-005', domain: 'ws-concepts', q: 'An SAP customer already exists, and its workspace is created from it the first time a user opens it. What kind of workspace is this?', options: ['A late workspace', 'An early workspace', 'A project', 'A community'], answer: 0, explain: 'Late workspaces are created from an existing business object; early ones exist before the object and are linked later.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-006', domain: 'ws-concepts', q: 'A bid team must store documents before the opportunity exists in the CRM. Which approach fits?', options: ['Create an early workspace and link it to the opportunity later', 'Wait for the CRM record', 'Use the Personal Workspace and move documents later', 'Create a workspace type per bid'], answer: 0, explain: 'Early workspaces are created first and connected once the business object exists.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-007', domain: 'ws-concepts', q: 'Which container is the best fit for “everything about customer 10023, its data and the account team”?', options: ['A business workspace', 'A collection', 'A discussion', 'A virtual folder'], answer: 0, explain: 'Business object with its own identity, data and team → business workspace.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-008', domain: 'ws-concepts', q: 'Which statement about template changes is true?', options: ['They apply only to workspaces created after the change', 'They update every existing workspace overnight', 'They require recreating the workspace type', 'They are blocked once a workspace exists'], answer: 0, explain: 'The template is a master copy used at creation; existing workspaces are not changed.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-009', domain: 'ws-concepts', q: 'What decides the Smart View layout a workspace opens in?', options: ['A perspective whose rules match it', 'The template\'s first folder', 'The location folder\'s appearance', 'The user\'s browser'], answer: 0, explain: 'Perspectives (with rules, usually by workspace type) define the layout.', guide: 'ws-how-they-work' },
  { id: 'ws-q-concepts-010', domain: 'ws-concepts', q: 'Which two parts belong to how workspaces connect to a leading application? (Choose two.)', options: ['External system', 'Business object type', 'Facet tree', 'Search slice'], answer: [0, 1], explain: 'The external system describes the connected application; the business object type maps its objects and properties to a workspace type.', guide: 'ws-how-they-work' },

  // ---------------------------------------------------------------- ws-infra
  { id: 'ws-q-infra-001', domain: 'ws-infra', q: 'In what order should the building blocks be created for a new kind of workspace?', options: ['Category, classification, location, then workspace type and template', 'Template, then type, then category', 'Perspective, type, template, category', 'Any order — they are independent'], answer: 0, explain: 'Each object refers to earlier ones: the type uses the category, the template uses type and classification.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-002', domain: 'ws-infra', q: 'Users don\'t see “Customer” in the + menu of the Customers folder, although the type and template exist. What is the most likely cause?', options: ['The folder and the template don\'t share a classification', 'The category has too many attributes', 'The perspective is missing', 'The folder has a description'], answer: 0, explain: 'Templates are offered where their classification matches the folder\'s.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-infra-003', domain: 'ws-infra', q: 'Which attributes should be mandatory in a workspace category?', options: ['Those used by the name pattern and the location path', 'All of them, always', 'None — mandatory fields slow users down', 'Only date attributes'], answer: 0, explain: 'Empty pattern or path attributes produce blank names or odd folders.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-004', domain: 'ws-infra', q: 'Where are category definitions created?', options: ['In the Categories volume', 'In the Document Templates volume', 'In the Classifications volume', 'In the workspace type'], answer: 0, explain: 'Categories live in the Categories volume.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-005', domain: 'ws-infra', q: 'Generated sub-folders under a workspace location (e.g. by region) get their permissions how?', options: ['They inherit from the location folder', 'From the workspace type', 'From the template roles', 'They get Public Access only'], answer: 0, explain: 'Like any new item, they inherit from their parent — set permissions on the root carefully.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-006', domain: 'ws-infra', q: 'Which two things should you do to the location folder of a workspace type? (Choose two.)', options: ['Give it the template\'s classification so users can create workspaces there', 'Set its permissions, which generated sub-folders inherit', 'Store the workspace templates in it', 'Add the workspace type as a category'], answer: [0, 1], explain: 'The classification offers the template; the permissions are inherited. Templates belong in the Document Templates volume.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-007', domain: 'ws-infra', q: 'Why use a pop-up list for the Region attribute that drives the location sub-path?', options: ['Controlled values avoid misspelled duplicate folders', 'Lists are required for all attributes', 'It makes the attribute optional', 'Perspectives can only show lists'], answer: 0, explain: 'Free text like “EMEA”, “Emea”, “E.M.E.A.” would create several folders.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-008', domain: 'ws-infra', q: 'Where should a new workspace configuration be built and tested first?', options: ['On a development or training system', 'Directly in production', 'In a user\'s Personal Workspace', 'In the Recycle Bin'], answer: 0, explain: 'Build and test on development, then move it with Transport.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-infra-009', domain: 'ws-infra', q: 'A typical pattern for template classifications is…', options: ['One classification tree for workspace templates, with one classification per workspace type', 'One classification per workspace', 'No classifications — templates are offered everywhere', 'A classification per user'], answer: 0, explain: 'A small dedicated tree (e.g. Workspace Templates ▸ Customer) keeps the offer of templates controlled.', guide: 'ws-setup-roadmap' },

  // ---------------------------------------------------------------- ws-types
  { id: 'ws-q-types-001', domain: 'ws-types', q: 'Where are workspace templates stored?', options: ['Document Templates volume', 'Categories volume', 'Personal Workspace of the administrator', 'Perspectives volume'], answer: 0, explain: 'Workspace templates live in the Document Templates volume.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-002', domain: 'ws-types', q: 'Which three things does a workspace template need to be usable? (Choose three.)', options: ['A workspace type', 'A classification', 'A category', 'A LiveReport'], answer: [0, 1, 2], explain: 'Type, classification and category are the essential trio; content and roles make it useful.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-003', domain: 'ws-types', q: 'Key accounts need extra folders and a stricter team than normal customers. Best design?', options: ['Two templates for the same Customer workspace type', 'A second workspace type “Key Customer”', 'One template edited by hand per customer', 'A separate category per customer'], answer: 0, explain: 'One type can have several templates; choose one at creation when structure or team differ.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-004', domain: 'ws-types', q: 'Which name pattern is best for customer workspaces?', options: ['Customer Number – Customer Name', 'Customer Name only', 'Status – Customer Name', 'Created date'], answer: 0, explain: 'Start with a unique, stable key and add a readable part; avoid free text only and values that change.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-005', domain: 'ws-types', q: 'Workspaces created through the REST API without a parent folder land where?', options: ['In the workspace type\'s location (plus any attribute sub-path)', 'In the API user\'s Personal Workspace', 'In the Enterprise Workspace root', 'They cannot be created'], answer: 0, explain: 'The type\'s location is used whenever no folder is chosen.', guide: 'ws-create' },
  { id: 'ws-q-types-006', domain: 'ws-types', q: 'What is copied from the template into each new workspace? (Choose two.)', options: ['Its folder structure', 'Its roles and their permissions', 'Its name', 'Its location'], answer: [0, 1], explain: 'Content and roles come from the template; name and location are worked out by the workspace type.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-007', domain: 'ws-types', q: 'What is the risk of an attribute-based sub-path built on an attribute that changes often, like Status?', options: ['The workspace may not move when the value changes, so the path and metadata drift apart', 'The workspace is deleted', 'The template is replaced', 'Nothing'], answer: 0, explain: 'Base paths on stable, mandatory attributes.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-008', domain: 'ws-types', q: 'Why should a workspace template never be used as a real workspace?', options: ['Everything in it is copied into every future workspace', 'Templates cannot hold documents', 'It slows down search', 'Templates are read-only'], answer: 0, explain: 'Live documents in a template end up in every new workspace.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-types-009', domain: 'ws-types', q: 'After creating the type and template, what is the best way to verify the setup?', options: ['Create a test workspace and check name, location, content, team and layout', 'Restart Content Server', 'Run a full reindex', 'Ask users to report problems'], answer: 0, explain: 'A fresh test workspace shows every part of the configuration at once.', guide: 'ws-setup-roadmap' },

  // ---------------------------------------------------------------- ws-roles
  { id: 'ws-q-roles-001', domain: 'ws-roles', q: 'Where are the roles of a business workspace defined?', options: ['In the workspace template', 'In OTDS', 'In the location folder', 'In the perspective'], answer: 0, explain: 'The template defines the roles and their permissions; each workspace gets its own participants.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-roles-002', domain: 'ws-roles', q: 'A sales rep leaves the ACME account. What is the right way to remove their access?', options: ['Remove them from the role in the workspace team', 'Edit the permissions of every folder in the workspace', 'Delete their user account', 'Move the workspace'], answer: 0, explain: 'Roles carry the permissions — manage people in roles, not ACLs.', guide: 'ws-working-in' },
  { id: 'ws-q-roles-003', domain: 'ws-roles', q: 'Which statement about template roles and workspace participants is true?', options: ['The template defines which roles exist; participants are added per workspace', 'Participants must be the same in every workspace', 'Roles are defined separately in each workspace by users', 'Participants are set in the workspace type'], answer: 0, explain: 'Roles are part of the template; people are assigned per workspace (default participants may come from the template).', guide: 'ws-working-in' },
  { id: 'ws-q-roles-004', domain: 'ws-roles', q: 'Which two are good practice for workspace roles? (Choose two.)', options: ['Name roles after the business job (Account Manager, Readers)', 'Give each role permissions that match its job', 'Give every role Edit Permissions', 'Use one role for everyone'], answer: [0, 1], explain: 'Clear roles with matching permissions make access predictable.', guide: 'ws-setup-roadmap' },
  { id: 'ws-q-roles-005', domain: 'ws-roles', q: 'Who can usually add participants to a workspace\'s team?', options: ['Members of a role allowed to manage the team', 'Anyone who can see the workspace', 'Only the Admin user', 'Nobody after creation'], answer: 0, explain: 'Team management is a right given to particular roles.', guide: 'ws-working-in' },
  { id: 'ws-q-roles-006', domain: 'ws-roles', q: 'A participant in the Readers role cannot add documents. Is this expected?', options: ['Yes — Readers typically only have See and See Contents', 'No — every participant can add documents', 'No — it is a perspective problem', 'Only if the workspace is late'], answer: 0, explain: 'Rights come from the role\'s permissions.', guide: 'ws-working-in' },

  // ---------------------------------------------------------------- ws-using
  { id: 'ws-q-using-001', domain: 'ws-using', q: 'A user creates a workspace in Customers ▸ EMEA in Smart View. Where is it created?', options: ['In Customers ▸ EMEA', 'Always at the root of the type\'s location', 'In their Personal Workspace', 'In Document Templates'], answer: 0, explain: 'Created in a folder, it lands there; the type\'s location applies when no folder is chosen.', guide: 'ws-create' },
  { id: 'ws-q-using-002', domain: 'ws-using', q: 'Workspaces created from SAP appear in the wrong folder. What do you check first?', options: ['The workspace type\'s location and sub-path attributes', 'The template\'s folders', 'The perspective rules', 'The Recycle Bin'], answer: 0, explain: 'Workspaces from the business application go to the type\'s location.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-using-003', domain: 'ws-using', q: 'A new workspace is named “ – ACME Corp”. What happened?', options: ['An attribute used in the name pattern was empty', 'The template has no folders', 'The user lacks permissions', 'The perspective is missing'], answer: 0, explain: 'Blank parts of a name come from empty pattern attributes.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-using-004', domain: 'ws-using', q: 'A workspace opens as a plain folder list. Which object do you check?', options: ['The perspective and its rules', 'The category', 'The location', 'The classification'], answer: 0, explain: 'No matching perspective → generic browse view.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-using-005', domain: 'ws-using', q: 'Before creating a workspace with required metadata through the REST API, what should a client request?', options: ['The create form for the template', 'The audit log', 'A LiveReport', 'The OTDS partition'], answer: 0, explain: 'The create form lists the fields the chosen template needs.', guide: 'ws-create' },
  { id: 'ws-q-using-006', domain: 'ws-using', q: 'What is the most reliable way to get the exact body of a workspace-creation REST request for your release?', options: ['Create one in Smart View with the browser developer tools open and copy the request', 'Guess from an older release', 'Read the database', 'Ask users'], answer: 0, explain: 'The body has changed between releases; Smart View itself uses the API.', guide: 'ws-create' },
  { id: 'ws-q-using-007', domain: 'ws-using', q: 'Which widget lists a customer\'s contracts and projects?', options: ['Related workspaces', 'Team', 'Header', 'Search'], answer: 0, explain: 'Relationships between workspace types are shown by the related workspaces widget.', guide: 'ws-working-in' },
  { id: 'ws-q-using-008', domain: 'ws-using', q: 'A workspace shows that the Tax certificate is missing and the Credit check expires soon. Which feature does this?', options: ['Smart document types with required documents', 'Facets', 'Generations', 'Appearances'], answer: 0, explain: 'Smart document types classify documents and track required ones.', guide: 'ws-working-in' },
  { id: 'ws-q-using-009', domain: 'ws-using', q: 'Which two are ways workspaces are created automatically, without a user in Smart View? (Choose two.)', options: ['By the leading application when a business object is created', 'By a REST API call from an integration', 'By changing a perspective', 'By marking a guide as read'], answer: [0, 1], explain: 'Integrations, events, scripts and Business Scenarios create workspaces unattended.', guide: 'ws-create' },
  { id: 'ws-q-using-010', domain: 'ws-using', q: 'You changed a workspace configuration on development. How should it reach production?', options: ['With a transport package, after testing', 'Rebuilt by hand in production', 'By copying the database', 'It cannot be moved'], answer: 0, explain: 'Transport moves configuration objects between environments.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-using-011', domain: 'ws-using', q: 'Why include the category and classifications in the same transport as the workspace type and template?', options: ['The type and template depend on them', 'Transport requires every object', 'They are optional extras', 'To make the package bigger'], answer: 0, explain: 'Dependencies must exist in the target before the objects that refer to them.', guide: 'ws-troubleshooting' },
  { id: 'ws-q-using-012', domain: 'ws-using', q: 'What is the fastest regression test after a workspace configuration change?', options: ['Create a fresh test workspace and check it', 'Restart the server', 'Reindex the system', 'Clear the browser cache'], answer: 0, explain: 'A new workspace exercises name, location, template, roles and perspective in one go.', guide: 'ws-troubleshooting' },
];
