'use strict';
// Builds the Internet Explorer 11 front end (used on Windows Server 2016, whose
// only built-in browser is IE11):
//
//   public/legacy/app.legacy.js      polyfills + public/app.js transpiled to ES5
//   public/legacy/styles.legacy.css  public/styles.css + tools/ie11.css with the
//                                    CSS variables resolved (light theme)
//
// Rebuild after changing public/app.js, public/styles.css or tools/ie11.css:
//   npm install            (once; build tools only — the app has no runtime dependencies)
//   npm run build:legacy
//
// The output is committed, so servers running the app never need npm.

const fs = require('fs');
const path = require('path');
const { ROOT, sourceHash } = require('./legacy-sources');

function need(name) {
  try { return require(name); } catch {
    console.error(`Missing build dependency "${name}". Run "npm install" in ${ROOT} first.`);
    process.exit(1);
  }
}
const Babel = need('@babel/standalone');
const acorn = need('acorn');

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const pkgFile = (spec) => fs.readFileSync(require.resolve(spec), 'utf8');
const outDir = path.join(ROOT, 'public', 'legacy');
const hash = sourceHash();
const stamp = `/* Generated by tools/build-legacy.js — source hash ${hash}. Do not edit; edit public/app.js, public/styles.css or tools/ie11.css and rebuild. */\n`;

// ---------------------------------------------------------------- JavaScript

const app = Babel.transform(read('public/app.js'), {
  presets: [['env', { targets: { ie: '11' }, modules: false }]],
  sourceType: 'script',
  comments: false,
}).code;

// DOM APIs IE11 lacks that no polyfill below provides. app.js must avoid them.
const IE_MISSING = [/\.closest\(/, /\.append\(/, /\.prepend\(/, /\.replaceWith\(/, /\.remove\(\)/, /\.isConnected\b/,
  /\.toggle\([^)]*,/, /scrollTo\(\{/, /\.requestSubmit\(/, /\bnew URL\(/, /\bURLSearchParams\b/];
const offenders = IE_MISSING.filter((re) => re.test(app));
if (offenders.length) {
  console.error(`app.js uses DOM APIs Internet Explorer 11 does not have: ${offenders.map(String).join(', ')}`);
  process.exit(1);
}

const polyfills = [
  // Everything ES2015+ the transpiled code relies on: Promise, Symbol, Object.assign/entries/values,
  // Array.from/includes/find, String.includes/startsWith, NodeList.forEach, …
  ['core-js', pkgFile('core-js-bundle/minified.js')],
  // fetch() on top of XMLHttpRequest.
  ['whatwg-fetch', pkgFile('whatwg-fetch/dist/fetch.umd.js')],
];
// Only needed if Babel emitted references to the global runtime instead of inlining it.
if (/\bregeneratorRuntime\b/.test(app) && !/function _regenerator/.test(app)) {
  polyfills.push(['regenerator-runtime', pkgFile('regenerator-runtime/runtime.js')]);
}

const js = stamp + polyfills.map(([name, code]) => `/* --- ${name} --- */\n${code.replace(/\/\/# sourceMappingURL=.*$/gm, '')}\n;`).join('\n') +
  `\n/* --- CS Academy (public/app.js, transpiled) --- */\n${app}\n`;

try {
  acorn.parse(js, { ecmaVersion: 5, sourceType: 'script' });
} catch (e) {
  const line = js.split('\n')[e.loc.line - 1] || '';
  console.error(`Legacy bundle is not valid ES5 at line ${e.loc.line}: ${e.message}\n  ${line.slice(Math.max(0, e.loc.column - 60), e.loc.column + 60)}`);
  process.exit(1);
}

// ---------------------------------------------------------------- CSS

// Removes a `selector { … }` block, braces balanced.
function dropBlock(css, startToken) {
  let i = css.indexOf(startToken);
  while (i !== -1) {
    let depth = 0;
    let j = css.indexOf('{', i);
    for (; j < css.length; j++) {
      if (css[j] === '{') depth++;
      else if (css[j] === '}' && --depth === 0) break;
    }
    css = css.slice(0, i) + css.slice(j + 1);
    i = css.indexOf(startToken);
  }
  return css;
}

let css = (read('public/styles.css') + '\n' + read('tools/ie11.css')).replace(/\/\*[\s\S]*?\*\//g, '');
const rootBlock = /:root\s*\{([^}]*)\}/.exec(css);
const tokens = {};
for (const m of rootBlock[1].matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)) tokens[m[1]] = m[2].trim();

css = css.replace(rootBlock[0], '');
css = dropBlock(css, '@media (prefers-color-scheme: dark)');
css = dropBlock(css, ':root[data-theme="dark"]');
css = css.replace(/var\(--([\w-]+)\)/g, (whole, name) => {
  if (!(name in tokens)) throw new Error(`Unknown CSS variable --${name}`);
  return tokens[name];
});
// Declarations IE11 can't parse; each has a plain fallback declared just before it in styles.css.
css = css.replace(/([{;])\s*[\w-]+\s*:[^;{}]*(?:color-mix|clamp|min)\([^;{}]*;/g, '$1');
if (/var\(--|color-mix\(/.test(css)) throw new Error('Unresolved modern CSS left in the legacy stylesheet');

// ---------------------------------------------------------------- write

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'app.legacy.js'), js);
fs.writeFileSync(path.join(outDir, 'styles.legacy.css'), stamp + css);
const kb = (s) => `${Math.round(Buffer.byteLength(s) / 1024)} KB`;
console.log(`Built public/legacy/app.legacy.js (${kb(js)}, ES5 verified) and styles.legacy.css (${kb(css)}) — source hash ${hash}`);
